import type { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  // ——— Lug'at ———
  {
    id: "v-a1-01",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "Apple so'zining ma'nosi qaysi?",
    options: ["Olma", "Armud", "Uzum", "Shaftoli"],
    answer: 0,
    explain: "Apple — olma. Pear — armud, grape — uzum, peach — shaftoli.",
  },
  {
    id: "v-a1-02",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "Book so'zining ma'nosi qaysi?",
    options: ["Daftar", "Kitob", "Qalam", "Stol"],
    answer: 1,
    explain: "Book — kitob. Notebook — daftar, pen — qalam, table — stol.",
  },
  {
    id: "v-a1-03",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "Water so'zining ma'nosi qaysi?",
    options: ["Sut", "Choy", "Suv", "Sharbat"],
    answer: 2,
    explain: "Water — suv. Milk — sut, tea — choy, juice — sharbat.",
  },
  {
    id: "v-a1-04",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "Thank you ning o'zbekchasi?",
    options: ["Kechirasiz", "Rahmat", "Iltimos", "Xayr"],
    answer: 1,
    explain: "Thank you — rahmat. Sorry — kechirasiz, please — iltimos, goodbye — xayr.",
  },
  {
    id: "v-a1-05",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "Qaysi so'z «do'st» degani?",
    options: ["Family", "Friend", "Neighbor", "Teacher"],
    answer: 1,
    explain: "Friend — do'st. Family — oila, neighbor — qo'shni, teacher — o'qituvchi.",
  },
  {
    id: "v-a1-06",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "Good morning qachon aytiladi?",
    options: ["Kechqurun", "Tunda", "Ertalab", "Tushdan keyin"],
    answer: 2,
    explain: "Good morning — xayrli tong, odatda ertalab aytiladi.",
  },
  {
    id: "v-a1-07",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "House so'zining ma'nosi?",
    options: ["Maktab", "Do'kon", "Uy", "Bog'"],
    answer: 2,
    explain: "House — uy. School — maktab, shop — do'kon, garden — bog'.",
  },
  {
    id: "v-a1-08",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "Qaysi rang «qizil»?",
    options: ["Blue", "Green", "Red", "Black"],
    answer: 2,
    explain: "Red — qizil. Blue — ko'k, green — yashil, black — qora.",
  },
  {
    id: "v-a1-09",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "I am a student. gapining tarjimasi?",
    options: [
      "Men o'qituvchiman",
      "Men o'quvchiman",
      "Men ishchiman",
      "Men shifokorman",
    ],
    answer: 1,
    explain: "Student — o'quvchi / talaba. Teacher — o'qituvchi.",
  },
  {
    id: "v-a1-10",
    skill: "vocab",
    level: "A1",
    kind: "mcq",
    prompt: "Hungry nima demak?",
    options: ["Charchagan", "Chanqagan", "Och", "Xursand"],
    answer: 2,
    explain: "Hungry — och. Thirsty — chanqagan, tired — charchagan, happy — xursand.",
  },
  {
    id: "v-a2-01",
    skill: "vocab",
    level: "A2",
    kind: "mcq",
    prompt: "Appointment so'zining eng yaqin ma'nosi?",
    options: ["Uchrashuv", "Bayram", "Safar", "Dars"],
    answer: 0,
    explain: "Appointment — belgilangan uchrashuv (shifokor, ish va hokazo).",
  },
  {
    id: "v-a2-02",
    skill: "vocab",
    level: "A2",
    kind: "mcq",
    prompt: "Borrow va lend farqi qaysi?",
    options: [
      "Ikkalasi ham «bermoq»",
      "Borrow — olmoq, lend — bermoq",
      "Borrow — bermoq, lend — olmoq",
      "Farqi yo'q",
    ],
    answer: 1,
    explain: "I borrow a book from you. You lend a book to me.",
  },
  {
    id: "v-a2-03",
    skill: "vocab",
    level: "A2",
    kind: "mcq",
    prompt: "Weather so'zining ma'nosi?",
    options: ["Havo harorati", "Ob-havo", "Mavsum", "Iqlim"],
    answer: 1,
    explain: "Weather — ob-havo. Climate — iqlim, season — mavsum, temperature — harorat.",
  },
  {
    id: "v-a2-04",
    skill: "vocab",
    level: "A2",
    kind: "mcq",
    prompt: "Qaysi juftlik sinonim?",
    options: ["big — small", "begin — start", "hot — cold", "fast — slow"],
    answer: 1,
    explain: "Begin va start — boshlamoq. Qolganlari antonimlar.",
  },
  {
    id: "v-a2-05",
    skill: "vocab",
    level: "A2",
    kind: "mcq",
    prompt: "Airport qayer?",
    options: ["Avtobus bekati", "Aeroport", "Vokzal", "Port"],
    answer: 1,
    explain: "Airport — aeroport. Station — vokzal, bus stop — avtobus bekati.",
  },
  {
    id: "v-a2-06",
    skill: "vocab",
    level: "A2",
    kind: "mcq",
    prompt: "Look after ning ma'nosi?",
    options: ["Qaramoq", "Parvarish qilmoq", "Qidirmoq", "Kutmoq"],
    answer: 1,
    explain: "Look after — parvarish qilmoq / g'amxo'rlik qilmoq. Look for — qidirmoq.",
  },
  {
    id: "v-b1-01",
    skill: "vocab",
    level: "B1",
    kind: "mcq",
    prompt: "Postpone so'zining ma'nosi?",
    options: ["Bekor qilmoq", "Kechiktirmoq", "Tezlashtirmoq", "Boshlamoq"],
    answer: 1,
    explain: "Postpone — keyinga surmoq, kechiktirmoq. Cancel — bekor qilmoq.",
  },
  {
    id: "v-b1-02",
    skill: "vocab",
    level: "B1",
    kind: "mcq",
    prompt: "I look forward to seeing you. nimani bildiradi?",
    options: [
      "Sizni ko'rishni intiqlik bilan kutaman",
      "Sizni qidiryapman",
      "Sizga qarab turibman",
      "Sizni eslayman",
    ],
    answer: 0,
    explain: "Look forward to + -ing — nimadirni intiqlik bilan kutmoq.",
  },
  {
    id: "v-b1-03",
    skill: "vocab",
    level: "B1",
    kind: "mcq",
    prompt: "Nevertheless o'rniga qaysi so'z keladi?",
    options: ["Therefore", "However", "Because", "Meanwhile"],
    answer: 1,
    explain: "Nevertheless ≈ however — shunga qaramay.",
  },
  {
    id: "v-b1-04",
    skill: "vocab",
    level: "B1",
    kind: "mcq",
    prompt: "A coincidence nima?",
    options: ["Reja", "Tasodif", "Muammo", "Muvaffaqiyat"],
    answer: 1,
    explain: "Coincidence — kutilmagan mos kelish, tasodif.",
  },

  // ——— Tarjima ———
  {
    id: "t-a1-01",
    skill: "translate",
    level: "A1",
    kind: "type",
    prompt: "Tarjima qiling: Mening ismim Ali.",
    answers: ["My name is Ali", "My name's Ali"],
    placeholder: "English",
    explain: "My name is / My name's + ism.",
  },
  {
    id: "t-a1-02",
    skill: "translate",
    level: "A1",
    kind: "type",
    prompt: "Tarjima qiling: Men o'quvchiman.",
    answers: ["I am a student", "I'm a student"],
    placeholder: "English",
    explain: "I am / I'm a student. Artikl a kasb oldida kerak.",
  },
  {
    id: "t-a1-03",
    skill: "translate",
    level: "A1",
    kind: "mcq",
    prompt: "How are you? ning tarjimasi?",
    options: [
      "Siz kimsiz?",
      "Yaxshimisiz? / Qalaysiz?",
      "Qayerdansiz?",
      "Nima qilyapsiz?",
    ],
    answer: 1,
    explain: "How are you? — Qalaysiz? Javob: I'm fine, thank you.",
  },
  {
    id: "t-a1-04",
    skill: "translate",
    level: "A1",
    kind: "type",
    prompt: "Tarjima qiling: Men Toshkentdanman.",
    answers: ["I am from Tashkent", "I'm from Tashkent"],
    placeholder: "English",
    explain: "I am from + joy. From — -dan.",
  },
  {
    id: "t-a1-05",
    skill: "translate",
    level: "A1",
    kind: "mcq",
    prompt: "Nice to meet you. ning tarjimasi?",
    options: [
      "Sizni ko'rganimdan xursandman",
      "Tanishganimdan xursandman",
      "Yaxshi dam oling",
      "Keyinroq ko'rishamiz",
    ],
    answer: 1,
    explain: "Nice to meet you — tanishganimdan xursandman (birinchi uchrashuv).",
  },
  {
    id: "t-a1-06",
    skill: "translate",
    level: "A1",
    kind: "type",
    prompt: "Tarjima qiling: Bu kitob.",
    answers: ["This is a book", "It's a book", "It is a book"],
    placeholder: "English",
    explain: "This is a book. This — yaqin narsa.",
  },
  {
    id: "t-a1-07",
    skill: "translate",
    level: "A1",
    kind: "mcq",
    prompt: "See you tomorrow. ning tarjimasi?",
    options: [
      "Ertaga ko'rishamiz",
      "Bugun ko'rishamiz",
      "Kecha ko'rishgan edik",
      "Hozir ko'rishamiz",
    ],
    answer: 0,
    explain: "Tomorrow — ertalab emas, ertaga. Today — bugun, yesterday — kecha.",
  },
  {
    id: "t-a2-01",
    skill: "translate",
    level: "A2",
    kind: "type",
    prompt: "Tarjima qiling: Men har kuni ertalab qahva ichaman.",
    answers: [
      "I drink coffee every morning",
      "I have coffee every morning",
      "Every morning I drink coffee",
    ],
    placeholder: "English",
    explain: "Present simple odatlar uchun: I drink coffee every morning.",
  },
  {
    id: "t-a2-02",
    skill: "translate",
    level: "A2",
    kind: "type",
    prompt: "Tarjima qiling: U hozir ishlayapti.",
    answers: ["He is working now", "He's working now", "She is working now", "She's working now"],
    placeholder: "English",
    explain: "Hozirgi jarayon — Present Continuous: is/are + -ing.",
  },
  {
    id: "t-a2-03",
    skill: "translate",
    level: "A2",
    kind: "mcq",
    prompt: "Could you help me, please? ning tarjimasi?",
    options: [
      "Menga yordam bera olasizmi, iltimos?",
      "Menga yordam berishingiz shart",
      "Men sizga yordam beraman",
      "Yordam kerak emas",
    ],
    answer: 0,
    explain: "Could you … please? — muloyim iltimos.",
  },
  {
    id: "t-a2-04",
    skill: "translate",
    level: "A2",
    kind: "type",
    prompt: "Tarjima qiling: Kecha men kino ko'rdim.",
    answers: [
      "I watched a movie yesterday",
      "I watched a film yesterday",
      "Yesterday I watched a movie",
      "Yesterday I watched a film",
    ],
    placeholder: "English",
    explain: "O'tgan oddiy zamon: watched. Yesterday — kecha.",
  },
  {
    id: "t-a2-05",
    skill: "translate",
    level: "A2",
    kind: "mcq",
    prompt: "I would like a glass of water. ning tarjimasi?",
    options: [
      "Men suv ichdim",
      "Men bir stakan suv olmoqchiman",
      "Menga suv yoqadi",
      "Suv yo'q",
    ],
    answer: 1,
    explain: "I would like — muloyim «xohlayman» (buyurtma, iltimos).",
  },
  {
    id: "t-b1-01",
    skill: "translate",
    level: "B1",
    kind: "type",
    prompt: "Tarjima qiling: Agar yomg'ir yog'sa, uyda qolaman.",
    answers: [
      "If it rains I will stay at home",
      "If it rains I'll stay at home",
      "If it rains I will stay home",
      "If it rains I'll stay home",
    ],
    placeholder: "English",
    explain: "First conditional: If + present, will + verb.",
  },
  {
    id: "t-b1-02",
    skill: "translate",
    level: "B1",
    kind: "mcq",
    prompt: "I have already finished my homework. ning tarjimasi?",
    options: [
      "Men hozir uy vazifasini qilyapman",
      "Men uy vazifasini allaqachon tugatganman",
      "Men uy vazifasini ertaga qilaman",
      "Men uy vazifasini qilmaganman",
    ],
    answer: 1,
    explain: "Present Perfect + already — allaqachon bajarilgan ish.",
  },
  {
    id: "t-b1-03",
    skill: "translate",
    level: "B1",
    kind: "type",
    prompt: "Tarjima qiling: Bu kitobni o'qiganman.",
    answers: [
      "I have read this book",
      "I've read this book",
      "I have read that book",
      "I've read that book",
    ],
    placeholder: "English",
    explain: "Tajriba — Present Perfect: have/has + V3 (read / read).",
  },

  // ——— Grammatika: xato topish ———
  {
    id: "g-a1-01",
    skill: "grammar",
    level: "A1",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["She", "go", "to", "school", "every", "day"],
    wrongIndex: 1,
    correction: "goes",
    explain: "He/She/It bilan Present Simple da fe'lga -s qo'shiladi: she goes.",
  },
  {
    id: "g-a1-02",
    skill: "grammar",
    level: "A1",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["He", "don't", "like", "coffee"],
    wrongIndex: 1,
    correction: "doesn't",
    explain: "He/She/It + doesn't. Don't — I/you/we/they uchun.",
  },
  {
    id: "g-a1-03",
    skill: "grammar",
    level: "A1",
    kind: "mcq",
    prompt: "Qaysi gap to'g'ri?",
    options: [
      "I am 20 years",
      "I have 20 years",
      "I am 20 years old",
      "I have 20 years old",
    ],
    answer: 2,
    explain: "Yosh: I am 20 years old. «I have 20 years» — kalit xato.",
  },
  {
    id: "g-a1-04",
    skill: "grammar",
    level: "A1",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["I", "am", "agree", "with", "you"],
    wrongIndex: 1,
    correction: "",
    explain: "Agree — fe'l, oldida am bo'lmaydi: I agree with you.",
  },
  {
    id: "g-a1-05",
    skill: "grammar",
    level: "A1",
    kind: "mcq",
    prompt: "Bo'sh joyni to'ldiring: She ___ a teacher.",
    options: ["am", "is", "are", "be"],
    answer: 1,
    explain: "He/She/It + is. I am, you/we/they are.",
  },
  {
    id: "g-a1-06",
    skill: "grammar",
    level: "A1",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["There", "is", "many", "books", "on", "the", "table"],
    wrongIndex: 1,
    correction: "are",
    explain: "Ko'plik: there are many books. There is — birlik uchun.",
  },
  {
    id: "g-a1-07",
    skill: "grammar",
    level: "A1",
    kind: "mcq",
    prompt: "Qaysi biri to'g'ri?",
    options: ["a apple", "an apple", "an book", "a hour"],
    answer: 1,
    explain: "Unli tovush oldida an: an apple, an hour. A book.",
  },
  {
    id: "g-a2-01",
    skill: "grammar",
    level: "A2",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["I", "am", "interested", "on", "music"],
    wrongIndex: 3,
    correction: "in",
    explain: "Interested in — qiziqmoq. Dependent preposition: in.",
  },
  {
    id: "g-a2-02",
    skill: "grammar",
    level: "A2",
    kind: "mcq",
    prompt: "We went to the park ___ Sunday.",
    options: ["in", "at", "on", "by"],
    answer: 2,
    explain: "Kunlar bilan on: on Monday, on Sunday. In June, at 5 o'clock.",
  },
  {
    id: "g-a2-03",
    skill: "grammar",
    level: "A2",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["She", "didn't", "went", "to", "the", "party"],
    wrongIndex: 2,
    correction: "go",
    explain: "Did / didn't dan keyin fe'l 1-shaklda: didn't go. Went — o'tgan shakl, did bilan qo'shilmaydi.",
  },
  {
    id: "g-a2-04",
    skill: "grammar",
    level: "A2",
    kind: "mcq",
    prompt: "There aren't ___ chairs in the room.",
    options: ["much", "many", "a little", "little"],
    answer: 1,
    explain: "Many — sanaladigan ko'plik (chairs). Much — sanalmaydigan (water, time).",
  },
  {
    id: "g-a2-05",
    skill: "grammar",
    level: "A2",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["I", "have", "lived", "here", "since", "two", "years"],
    wrongIndex: 4,
    correction: "for",
    explain: "For + muddat (for two years). Since + boshlanish nuqtasi (since 2022).",
  },
  {
    id: "g-b1-01",
    skill: "grammar",
    level: "B1",
    kind: "mcq",
    prompt: "Qaysi gap to'g'ri?",
    options: [
      "Despite of the rain, we went out",
      "Despite the rain, we went out",
      "Despite of rain, we went out",
      "Despite the rain but we went out",
    ],
    answer: 1,
    explain: "Despite + noun (of yo'q). In spite of + noun.",
  },
  {
    id: "g-b1-02",
    skill: "grammar",
    level: "B1",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["The", "informations", "is", "useful"],
    wrongIndex: 1,
    correction: "information",
    explain: "Information sanalmaydi: information (ko'plik -s yo'q). The information is useful.",
  },
  {
    id: "g-b1-03",
    skill: "grammar",
    level: "B1",
    kind: "mcq",
    prompt: "If I ___ rich, I would travel more.",
    options: ["am", "was", "were", "will be"],
    answer: 2,
    explain: "Second conditional: If + past, would + verb. If I were rich… (were rasmiy/to'g'ri variant).",
  },
  {
    id: "g-b1-04",
    skill: "grammar",
    level: "B1",
    kind: "tap-error",
    prompt: "Xato so'zni bosing.",
    tokens: ["This", "is", "more", "better", "than", "that"],
    wrongIndex: 2,
    correction: "",
    explain: "Better allaqachon qiyosiy: better (more better emas). This is better than that.",
  },

  // ——— Yozish ———
  {
    id: "w-a1-01",
    skill: "writing",
    level: "A1",
    kind: "order",
    prompt: "Gap tuzing: Men ingliz tilini o'rganaman.",
    words: ["I", "learn", "English"],
    answer: "I learn English",
    explain: "Odatiy tartib: Subject + Verb + Object.",
  },
  {
    id: "w-a1-02",
    skill: "writing",
    level: "A1",
    kind: "type",
    prompt: "Yozing: Men 25 yoshdaman.",
    answers: ["I am 25 years old", "I'm 25 years old", "I am 25", "I'm 25"],
    placeholder: "To'liq gap",
    explain: "I am 25 years old — eng to'liq va tabiiy shakl.",
  },
  {
    id: "w-a1-03",
    skill: "writing",
    level: "A1",
    kind: "order",
    prompt: "Savol tuzing: Bu nima?",
    words: ["What", "is", "this?"],
    answer: "What is this?",
    explain: "What is this? — yaqin narsa haqida savol.",
  },
  {
    id: "w-a1-04",
    skill: "writing",
    level: "A1",
    kind: "type",
    prompt: "Yozing: Ular o'qituvchi emas.",
    answers: ["They are not teachers", "They're not teachers", "They aren't teachers"],
    placeholder: "To'liq gap",
    explain: "They are not / aren't + ko'plik: teachers.",
  },
  {
    id: "w-a1-05",
    skill: "writing",
    level: "A1",
    kind: "order",
    prompt: "Gap tuzing: Uning mushugi bor.",
    words: ["She", "has", "a", "cat"],
    answer: "She has a cat",
    explain: "Have/has: I/you/we/they have, he/she/it has.",
  },
  {
    id: "w-a1-06",
    skill: "writing",
    level: "A1",
    kind: "type",
    prompt: "Yozing: Bu mening ukam.",
    answers: ["This is my brother", "He's my brother", "He is my brother"],
    placeholder: "To'liq gap",
    explain: "This is my brother. Brother — aka/uka.",
  },
  {
    id: "w-a2-01",
    skill: "writing",
    level: "A2",
    kind: "order",
    prompt: "Gap tuzing: U kecha kino ko'rdi.",
    words: ["He", "watched", "a", "movie", "yesterday"],
    answer: "He watched a movie yesterday",
    explain: "Past Simple + yesterday. Time expression odatda oxirida.",
  },
  {
    id: "w-a2-02",
    skill: "writing",
    level: "A2",
    kind: "type",
    prompt: "Yozing: Hozir yomg'ir yog'yapti.",
    answers: ["It is raining now", "It's raining now", "It is raining", "It's raining"],
    placeholder: "To'liq gap",
    explain: "Ob-havo: It is raining. Present Continuous.",
  },
  {
    id: "w-a2-03",
    skill: "writing",
    level: "A2",
    kind: "order",
    prompt: "Gap tuzing: Biz dam olish kunlari futbol o'ynaymiz.",
    words: ["We", "play", "football", "at", "the", "weekend"],
    answer: "We play football at the weekend",
    explain: "At the weekend (UK) / on the weekend (US). Ikkalasi ham ishlatiladi; bu mashqda at the weekend.",
  },
  {
    id: "w-a2-04",
    skill: "writing",
    level: "A2",
    kind: "type",
    prompt: "Yozing: Men hech qachon Londonda bo'lmaganman.",
    answers: [
      "I have never been to London",
      "I've never been to London",
      "I have never been in London",
    ],
    placeholder: "To'liq gap",
    explain: "Have been to + shahar — borib kelgan tajriba. Never — hech qachon.",
  },
  {
    id: "w-a2-05",
    skill: "writing",
    level: "A2",
    kind: "order",
    prompt: "Savol tuzing: Siz qayerda yashaysiz?",
    words: ["Where", "do", "you", "live?"],
    answer: "Where do you live?",
    explain: "Present Simple savol: Where + do/does + subject + verb.",
  },
  {
    id: "w-b1-01",
    skill: "writing",
    level: "B1",
    kind: "type",
    prompt: "Yozing: Men ishga piyoda borishni afzal ko'raman.",
    answers: [
      "I prefer to walk to work",
      "I prefer walking to work",
      "I would rather walk to work",
      "I'd rather walk to work",
    ],
    placeholder: "To'liq gap",
    explain: "Prefer to walk / prefer walking — ikkalasi ham to'g'ri.",
  },
  {
    id: "w-b1-02",
    skill: "writing",
    level: "B1",
    kind: "order",
    prompt: "Gap tuzing: U ketishidan oldin menga qo'ng'iroq qildi.",
    words: ["She", "called", "me", "before", "she", "left"],
    answer: "She called me before she left",
    explain: "Before + o'tgan zamon. Ikki o'tgan harakat ketma-ketligi.",
  },
  {
    id: "w-b1-03",
    skill: "writing",
    level: "B1",
    kind: "type",
    prompt: "Yozing: Bu masalani muhokama qilishimiz kerak.",
    answers: [
      "We need to discuss this issue",
      "We have to discuss this issue",
      "We should discuss this issue",
      "We need to talk about this issue",
    ],
    placeholder: "To'liq gap",
    explain: "Need to / have to / should — majburiyat yoki maslahat.",
  },

  // ——— Eshitish ———
  {
    id: "l-a1-01",
    skill: "listening",
    level: "A1",
    kind: "listen-mcq",
    speak: "My name is Sarah.",
    options: [
      "Mening ismim Sara",
      "Men Sarani taniman",
      "Sara o'qituvchi",
      "Sara uyda",
    ],
    answer: 0,
    explain: "My name is Sarah — o'zini tanishtirish.",
  },
  {
    id: "l-a1-02",
    skill: "listening",
    level: "A1",
    kind: "listen-mcq",
    speak: "I am from Uzbekistan.",
    options: [
      "Men O'zbekistonga boraman",
      "Men O'zbekistondanman",
      "Men O'zbekistonda yashayman",
      "Men o'zbek tilini bilaman",
    ],
    answer: 1,
    explain: "I am from + mamlakat — kelib chiqish.",
  },
  {
    id: "l-a1-03",
    skill: "listening",
    level: "A1",
    kind: "listen-type",
    speak: "How are you?",
    answers: ["How are you", "How are you?"],
    explain: "Qisqa, kundalik savol. How are you?",
  },
  {
    id: "l-a1-04",
    skill: "listening",
    level: "A1",
    kind: "listen-mcq",
    speak: "The book is on the table.",
    options: [
      "Kitob stolda",
      "Kitob sumkada",
      "Stol kitob ustida",
      "Kitob polida",
    ],
    answer: 0,
    explain: "On the table — stol ustida / stolda.",
  },
  {
    id: "l-a1-05",
    skill: "listening",
    level: "A1",
    kind: "listen-type",
    speak: "See you tomorrow.",
    answers: ["See you tomorrow", "See you tomorrow."],
    explain: "See you tomorrow — ertalab emas, ertaga ko'rishamiz.",
  },
  {
    id: "l-a1-06",
    skill: "listening",
    level: "A1",
    kind: "listen-mcq",
    speak: "I would like a cup of tea.",
    options: [
      "Men choy ichdim",
      "Men bir piyola choy olmoqchiman",
      "Choy yoqmaydi",
      "Qahva iltimos",
    ],
    answer: 1,
    explain: "I would like — xohlayman / buyurtma.",
  },
  {
    id: "l-a2-01",
    skill: "listening",
    level: "A2",
    kind: "listen-mcq",
    speak: "The weather is nice today.",
    options: [
      "Bugun ob-havo yomon",
      "Bugun ob-havo yaxshi",
      "Kecha ob-havo yaxshi edi",
      "Ertaga yomg'ir yog'adi",
    ],
    answer: 1,
    explain: "Nice — yoqimli, yaxshi. Today — bugun.",
  },
  {
    id: "l-a2-02",
    skill: "listening",
    level: "A2",
    kind: "listen-type",
    speak: "Can I have the menu, please?",
    answers: [
      "Can I have the menu please",
      "Can I have the menu, please",
      "Can I have the menu, please?",
    ],
    explain: "Restoranda menyu so'rash. Can I have … please?",
  },
  {
    id: "l-a2-03",
    skill: "listening",
    level: "A2",
    kind: "listen-mcq",
    speak: "She is wearing a blue jacket.",
    options: [
      "U ko'k kurtka kiygan",
      "U qizil ko'ylak kiygan",
      "Kurtkasi qora",
      "U kurtka olmadi",
    ],
    answer: 0,
    explain: "Is wearing — hozir kiyib turibdi. Blue jacket — ko'k kurtka.",
  },
  {
    id: "l-a2-04",
    skill: "listening",
    level: "A2",
    kind: "listen-type",
    speak: "I usually get up at seven.",
    answers: [
      "I usually get up at seven",
      "I usually get up at 7",
      "I usually get up at seven o'clock",
    ],
    explain: "Usually — odatda. Get up — turmoq.",
  },
  {
    id: "l-a2-05",
    skill: "listening",
    level: "A2",
    kind: "listen-mcq",
    speak: "Don't forget to lock the door.",
    options: [
      "Eshikni ochishni unutmang",
      "Eshikni qulflashni unutmang",
      "Eshik ochiq",
      "Kalitni olib keting",
    ],
    answer: 1,
    explain: "Lock the door — eshikni qulflamoq. Don't forget — unutmang.",
  },
  {
    id: "l-b1-01",
    skill: "listening",
    level: "B1",
    kind: "listen-mcq",
    speak: "I'm looking forward to the weekend.",
    options: [
      "Dam olish kunini intiqlik bilan kutaman",
      "Dam olish kuni bekor bo'ldi",
      "Ish kunini kutaman",
      "Dam olishda ishlayman",
    ],
    answer: 0,
    explain: "Look forward to — intiqlik bilan kutmoq.",
  },
  {
    id: "l-b1-02",
    skill: "listening",
    level: "B1",
    kind: "listen-type",
    speak: "Would you mind closing the window?",
    answers: [
      "Would you mind closing the window",
      "Would you mind closing the window?",
    ],
    explain: "Would you mind + -ing — juda muloyim iltimos.",
  },
  {
    id: "l-b1-03",
    skill: "listening",
    level: "B1",
    kind: "listen-mcq",
    speak: "The meeting has been postponed until Friday.",
    options: [
      "Yig'ilish juma kuni bo'lib o'tdi",
      "Yig'ilish bekor qilindi",
      "Yig'ilish jumaga ko'chirildi",
      "Yig'ilish dushanbada",
    ],
    answer: 2,
    explain: "Has been postponed until Friday — jumaga qoldirildi.",
  },
  {
    id: "l-b1-04",
    skill: "listening",
    level: "B1",
    kind: "listen-type",
    speak: "Please take a seat and wait a moment.",
    answers: [
      "Please take a seat and wait a moment",
      "Please take a seat and wait a moment.",
    ],
    explain: "Take a seat — o'tiring. Wait a moment — bir zum kuting.",
  },
];

const LEVEL_RANK: Record<"A1" | "A2" | "B1", number> = { A1: 1, A2: 2, B1: 3 };

export function hashString(seed: string): number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function seededShuffle<T>(items: T[], seed: string): T[] {
  const arr = [...items];
  let h = hashString(seed);
  for (let i = arr.length - 1; i > 0; i--) {
    h = (Math.imul(h, 1664525) + 1013904223) >>> 0;
    const j = h % (i + 1);
    const tmp = arr[i]!;
    arr[i] = arr[j]!;
    arr[j] = tmp;
  }
  return arr;
}

export function exercisesFor(
  skill: "vocab" | "translate" | "grammar" | "writing" | "listening" | "mix" | "review",
  level: "A1" | "A2" | "B1",
  weakIds: string[] = [],
): Exercise[] {
  const rank = LEVEL_RANK[level];
  if (skill === "review") {
    const set = new Set(weakIds);
    return EXERCISES.filter((e) => set.has(e.id) && LEVEL_RANK[e.level] <= rank);
  }
  return EXERCISES.filter((e) => {
    if (LEVEL_RANK[e.level] > rank) return false;
    if (skill === "mix") return true;
    return e.skill === skill;
  });
}

export function pickSession(
  pool: Exercise[],
  count: number,
  seenIds: string[],
  seed: string,
): Exercise[] {
  if (pool.length === 0) return [];
  const seen = new Set(seenIds);
  const fresh = pool.filter((e) => !seen.has(e.id));
  const source = fresh.length >= count ? fresh : pool;
  return seededShuffle(source, seed).slice(0, Math.min(count, source.length));
}

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}
