import type { Lesson } from "@/lib/types";
import { pack, W, ph } from "@/lib/content/pack";

const L = "a2" as const;
const g = (
  title: string, titleUz: string, meaning: string, meaningUz: string, form: string, formUz: string,
  why: string, whyUz: string, examples: { en: string; uz: string }[],
  negative: { form: string; examples: { en: string; uz: string }[] },
  question: { form: string; examples: { en: string; uz: string }[] },
  mistakes: { wrong: string; right: string; why: string; whyUz: string }[],
  contrast?: { vs: string; a: string; b: string; note: string; noteUz: string },
) => ({ title, titleUz, meaning, meaningUz, form, formUz, why, whyUz, examples, negative, question, mistakes, contrast });

export const lessons: Lesson[] = [
  pack({
    id: "a2-30", day: 30, level: L, topic: "Countable and uncountable", topicUz: "Sanaladigan va sanalmaydigan",
    cefrCanDo: "I can use some, any, much, many, a lot of with food and objects.",
    cefrCanDoUz: "Ovqat va narsalar bilan some, any, much, many, a lot of ishlataman.",
    grammar: g("some / any / much / many", "some / any / much / many",
      "Countable nouns have a plural (apples). Uncountable nouns do not (water, rice, information). some in positives, any in negatives and questions. many + countable, much + uncountable.",
      "Sanaladigan otlar ko‘plikda (apples). Sanalmaydiganlar yo‘q (water). some — tasdiq, any — inkor/savol. many — sanaladigan, much — sanalmaydigan.",
      "a/an + singular countable. some rice. How much water? How many apples?",
      "a/an + birlik. some rice. How much / How many?",
      "English counts some things that Uzbek does not split the same way (advice, information).",
      "Inglizcha ba’zi otlarni sanalmaydigan qiladi: advice, information.",
      [{ en: "I need some water.", uz: "Menga suv kerak." }, { en: "Are there any eggs?", uz: "Tuxum bormi?" }, { en: "How much rice do we have?", uz: "Qancha guruchimiz bor?" }],
      { form: "I haven't got any milk. There isn't much time.", examples: [{ en: "We haven't got any sugar.", uz: "Shakarmiz yo‘q." }] },
      { form: "How much / How many…?", examples: [{ en: "How many tomatoes are there?", uz: "Nechta pomidor bor?" }] },
      [{ wrong: "an information", right: "some information", why: "information is uncountable.", whyUz: "information sanalmaydi." }, { wrong: "How much apples?", right: "How many apples?", why: "apples are countable → many.", whyUz: "apples sanaladi — many." }],
      { vs: "much vs many vs a lot of", a: "many books / much time", b: "a lot of books / a lot of time", note: "a lot of works with both, especially in positives.", noteUz: "a lot of ikkalasi bilan, asosan tasdiqda." },
    ),
    vocabulary: [
      W(L, "w-a2-some", "some", "bir oz / bir nechta", "determiner", "/sʌm/", "an amount, in positive sentences", "I bought some bread.", "Non oldim.", "quantity", "ShoppingBag"),
      W(L, "w-a2-any", "any", "biror / hech", "determiner", "/ˈeni/", "in questions and negatives", "Have we got any milk?", "Sutimiz bormi?", "quantity", "CircleHelp"),
      W(L, "w-a2-rice", "rice", "guruch", "noun", "/raɪs/", "a common uncountable food", "We eat a lot of rice.", "Ko‘p guruch yeymiz.", "food", "Wheat"),
      W(L, "w-a2-water", "water", "suv", "noun", "/ˈwɔːtə/", "the liquid we drink", "I don't drink much water.", "Ko‘p suv ichmayman.", "food", "Droplets"),
      W(L, "w-a2-bread", "bread", "non", "noun", "/bred/", "uncountable baked food", "some bread, not a bread", "non — sanalmaydi", "food", "Croissant"),
      W(L, "w-a2-egg", "egg", "tuxum", "noun", "/eɡ/", "countable food", "six eggs", "olti tuxum", "food", "Egg"),
      W(L, "w-a2-advice", "advice", "maslahat", "noun", "/ədˈvaɪs/", "uncountable: ideas to help someone", "Can I have some advice?", "Maslahat bera olasizmi?", "study", "MessageCircle"),
      W(L, "w-a2-bottle", "bottle", "shisha", "noun", "/ˈbɒtl/", "a container; a bottle of water", "two bottles of water", "ikki shisha suv", "food", "BottleWine"),
    ],
    phrases: [
      ph("p-a2-some", "I'd like some…", "Menga … kerak.", "/aɪd laɪk sʌm/", "I'd like some tea, please.", "Choy, iltimos.", "Order two uncountable foods."),
      ph("p-a2-any", "Have we got any…?", "… bormi?", "/hæv wiː ɡɒt ˈeni/", "Have we got any eggs?", "Tuxum bormi?", "Ask about the fridge."),
      ph("p-a2-how-much", "How much…?", "Qancha…? (sanalmaydigan)", "/haʊ mʌtʃ/", "How much water do you drink?", "Qancha suv ichasiz?", "Ask how much rice."),
      ph("p-a2-how-many", "How many…?", "Nechta…?", "/haʊ ˈmeni/", "How many apples are there?", "Nechta olma bor?", "Ask how many chairs."),
    ],
    listenTitle: "In the kitchen", listenTitleUz: "Oshxonada",
    lines: [
      { en: "Have we got any milk?", uz: "Sut bormi?" }, { en: "Yes. There's some milk in the fridge.", uz: "Ha. Muzlatgichda sut bor." },
      { en: "How many eggs are there?", uz: "Nechta tuxum?" }, { en: "Six. And some bread.", uz: "Olti. Va non." },
      { en: "We haven't got any sugar.", uz: "Shakar yo‘q." }, { en: "I'll buy some.", uz: "Olib kelaman." },
    ],
    readTitle: "Shopping list", readTitleUz: "Xarid ro‘yxati",
    readText: "This is my shopping list. I need some rice, some bread and a bottle of water. I don't need any sugar. How many tomatoes? Five. How much tea? Not much — one small box. Information about prices is on the board. Advice from my neighbour: buy fruit in the morning. I haven't got much time today, but I have many bags. At the market I always buy some greens and I never leave without bread. If there aren't any eggs, I will come back tomorrow.",
    speaking: { prompt: "Look in your kitchen. Use some, any, much, many.", promptUz: "Oshxonangiz haqida some/any/much/many.", scaffolding: ["We've got some…", "There isn't any…"] },
    writing: { prompt: "Write a shopping paragraph with countable and uncountable nouns.", promptUz: "Xarid haqida paragraf.", minWords: 90, scaffolding: ["I need some…", "How many…"] },
  }),
  pack({
    id: "a2-31", day: 31, level: L, topic: "Comparatives", topicUz: "Qiyosiy daraja",
    cefrCanDo: "I can compare two things with -er, more, and than.",
    cefrCanDoUz: "Ikki narsani -er, more va than bilan solishtiraman.",
    grammar: g("Comparatives", "Qiyosiy daraja",
      "We compare two people or things. Short adjectives: cheaper, bigger. Long adjectives: more expensive. Irregular: good-better, bad-worse, far-further.",
      "Ikki narsani solishtiramiz. Qisqa sifat: cheaper. Uzun: more expensive. good-better.",
      "adj-er than / more + adj than. as + adj + as for equal.",
      "adj-er than / more + adj than. Teng: as … as.",
      "English comparison sits on the adjective, not only with ‘qaraganda’.",
      "Qiyos sifatga qo‘shiladi.",
      [{ en: "This bag is cheaper than that one.", uz: "Bu sumka undan arzonroq." }, { en: "English is more useful than I thought.", uz: "Ingliz tili o‘ylaganimdan foydaliroq." }, { en: "She is as tall as her brother.", uz: "U akasidek uzun." }],
      { form: "not as … as; less + adj", examples: [{ en: "This hotel is not as big as that one.", uz: "Bu mehmonxona u qadar katta emas." }] },
      { form: "Which is cheaper?", examples: [{ en: "Which city is bigger, Tashkent or Bukhara?", uz: "Qaysi shahar kattaroq?" }] },
      [{ wrong: "more cheaper", right: "cheaper", why: "Do not mix more and -er.", whyUz: "more va -er birga emas." }, { wrong: "bigger that my house", right: "bigger than my house", why: "than, not that.", whyUz: "than, that emas." }],
    ),
    vocabulary: [
      W(L, "w-a2-cheap", "cheap", "arzon", "adjective", "/tʃiːp/", "low price", "This café is cheaper.", "Bu kafe arzonroq.", "shopping", "BadgePercent", { antonyms: ["expensive"] }),
      W(L, "w-a2-expensive", "expensive", "qimmat", "adjective", "/ɪkˈspensɪv/", "high price", "more expensive than gold", "oltindan qimmatroq", "shopping", "Gem"),
      W(L, "w-a2-better", "better", "yaxshiroq", "adjective", "/ˈbetə/", "comparative of good", "This tea is better.", "Bu choy yaxshiroq.", "quality", "ThumbsUp"),
      W(L, "w-a2-worse", "worse", "yomonroq", "adjective", "/wɜːs/", "comparative of bad", "The weather is worse today.", "Bugun ob-havo yomonroq.", "quality", "ThumbsDown"),
      W(L, "w-a2-than", "than", "qaraganda", "conjunction", "/ðæn/", "used after comparatives", "faster than a bus", "avtobusdan tezroq", "grammar", "ArrowRight"),
      W(L, "w-a2-tall", "tall", "baland (odam)", "adjective", "/tɔːl/", "of more than average height", "taller than me", "mendan uzunroq", "people", "Ruler"),
      W(L, "w-a2-useful", "useful", "foydali", "adjective", "/ˈjuːsfəl/", "helpful", "more useful for work", "ish uchun foydaliroq", "study", "Wrench"),
      W(L, "w-a2-quiet", "quiet", "sokin", "adjective", "/ˈkwaɪət/", "with little noise", "quieter than the centre", "markazdan sokinroq", "city", "VolumeX"),
    ],
    phrases: [
      ph("p-a2-er", "…er than…", "…dan …roq", "/ə ðæn/", "Buses are cheaper than taxis.", "Avtobus taksidan arzon.", "Compare two vehicles."),
      ph("p-a2-more", "more … than", "…dan ko‘proq …", "/mɔː ðæn/", "This book is more interesting than that one.", "Bu kitob qiziqarroq.", "Compare two lessons."),
      ph("p-a2-as-as", "as … as", "…dek", "/æz æz/", "I'm as busy as you.", "Sen kabi bandman.", "Say two things are equal."),
      ph("p-a2-better", "This is better.", "Bu yaxshiroq.", "/ðɪs ɪz ˈbetə/", "This seat is better.", "Bu joy yaxshiroq.", "Choose the better option aloud."),
    ],
    listenTitle: "Two cafés", listenTitleUz: "Ikki kafe",
    lines: [
      { en: "This café is cheaper than the one near the park.", uz: "Bu kafe bog‘ yonidagidan arzonroq." },
      { en: "But that one is quieter.", uz: "Lekin u sokinroq." },
      { en: "The tea here is better.", uz: "Bu yerdagi choy yaxshiroq." },
      { en: "Is it more expensive?", uz: "Qimmatroqmi?" },
      { en: "A little. Not as expensive as the hotel café.", uz: "Biroz. Mehmonxona kafesidek emas." },
      { en: "Then this is better for us.", uz: "Unda biz uchun yaxshiroq." },
    ],
    readTitle: "City or town?", readTitleUz: "Shahar yoki tuman?",
    readText: "Tashkent is bigger than Bukhara, but Bukhara is quieter than Tashkent. Public transport in the capital is more useful if you work late. Houses in a small town are often cheaper than city flats. Life is not better or worse — it is different. My cousin says village air is cleaner than city air. I think city libraries are more useful for students. Which is better for you? Write two sentences with than and one with as…as.",
    speaking: { prompt: "Compare your town and another city with five comparatives.", promptUz: "Shahringizni boshqasi bilan 5 qiyos.", scaffolding: ["bigger than", "more expensive than"] },
    writing: { prompt: "Write 100 words comparing two places you know.", promptUz: "Ikki joyni solishtirib 100 so‘z.", minWords: 100, scaffolding: ["…er than", "more … than"] },
  }),
  pack({
    id: "a2-32", day: 32, level: L, topic: "Superlatives", topicUz: "Ortlitirish darajasi",
    cefrCanDo: "I can use the -est / the most to say which is number one in a group.",
    cefrCanDoUz: "Guruhda birinchisini the -est / the most bilan aytaman.",
    grammar: g("Superlatives", "Ortlitirish darajasi",
      "Use superlatives for one item in a group of three or more: the cheapest, the most interesting, the best.",
      "Uch va undan ko‘p ichida birinchisi: the cheapest, the most interesting, the best.",
      "the + adj-est / the most + adj. Irregular: good-the best, bad-the worst.",
      "the + adj-est / the most + adj. good — the best.",
      "English needs the before the superlative in most cases.",
      "Ko‘pincha the shart.",
      [{ en: "This is the cheapest café in the street.", uz: "Bu ko‘chadagi eng arzon kafe." }, { en: "It was the most interesting lesson.", uz: "Eng qiziq dars edi." }, { en: "She is the best student in the class.", uz: "Sinfdagi eng yaxshi o‘quvchi." }],
      { form: "not the best; one of the most…", examples: [{ en: "It isn't the most expensive hotel.", uz: "Eng qimmat mehmonxona emas." }] },
      { form: "What is the …-est…?", examples: [{ en: "What is the longest river in Uzbekistan?", uz: "O‘zbekistondagi eng uzun daryo qaysi?" }] },
      [{ wrong: "the most cheapest", right: "the cheapest", why: "Don't mix most and -est.", whyUz: "most va -est birga emas." }, { wrong: "best student in class (no the)", right: "the best student in the class", why: "Usually the + superlative.", whyUz: "the kerak." }],
    ),
    vocabulary: [
      W(L, "w-a2-best", "best", "eng yaxshi", "adjective", "/best/", "superlative of good", "the best idea", "eng yaxshi g‘oya", "quality", "Trophy"),
      W(L, "w-a2-worst", "worst", "eng yomon", "adjective", "/wɜːst/", "superlative of bad", "the worst day", "eng yomon kun", "quality", "CloudLightning"),
      W(L, "w-a2-most", "most", "eng ko‘p / the most", "adverb", "/məʊst/", "used with long adjectives", "the most popular song", "eng mashhur qo‘shiq", "grammar", "Star"),
      W(L, "w-a2-popular", "popular", "mashhur", "adjective", "/ˈpɒpjələ/", "liked by many people", "the most popular café", "eng mashhur kafe", "city", "Heart"),
      W(L, "w-a2-long", "long", "uzun", "adjective", "/lɒŋ/", "great in length", "the longest street", "eng uzun ko‘cha", "size", "Ruler"),
      W(L, "w-a2-high", "high", "baland", "adjective", "/haɪ/", "a long way up", "the highest mountain", "eng baland tog‘", "nature", "Mountain"),
      W(L, "w-a2-in-group", "in the class", "sinfda", "phrase", "/ɪn ðə klɑːs/", "the group we compare in", "the youngest in the class", "sinfdagi eng yosh", "school", "Users"),
      W(L, "w-a2-ever", "ever", "qachonlardir", "adverb", "/ˈevə/", "at any time; often with superlatives", "the best film I have ever seen", "ko‘rgan eng yaxshi filmim", "time", "Infinity"),
    ],
    phrases: [
      ph("p-a2-the-est", "the …-est in…", "…dagi eng …", "/ðə ɪn/", "the tallest building in the city", "shahardagi eng baland bino", "Name the tallest person you know."),
      ph("p-a2-the-most", "the most …", "eng …", "/ðə məʊst/", "the most difficult exercise", "eng qiyin mashq", "Say the most useful app for you."),
      ph("p-a2-best-i", "the best I've ever…", "hayotimdagi eng yaxshi…", "/ðə best aɪv ˈevə/", "the best meal I've ever had", "yegan eng yaxshi taom", "Talk about your best trip."),
      ph("p-a2-one-of", "one of the most…", "eng …lardan biri", "/wʌn əv ðə məʊst/", "one of the most famous squares", "eng mashhur maydonlardan", "Name one of the most popular songs."),
    ],
    listenTitle: "The best day", listenTitleUz: "Eng yaxshi kun",
    lines: [
      { en: "It was the best day of the month.", uz: "Oydagi eng yaxshi kun edi." },
      { en: "We climbed the highest hill near the town.", uz: "Shaharga yaqin eng baland tepalikka chiqdik." },
      { en: "It wasn't the most difficult walk.", uz: "Eng qiyin sayr emasdi." },
      { en: "The worst part was the bus home.", uz: "Eng yomoni uyga avtobus edi." },
      { en: "Still, it was the most popular trip this year.", uz: "Baribir yilning eng mashhur safari." },
      { en: "What's the best photo?", uz: "Eng yaxshi rasm qaysi?" },
    ],
    readTitle: "Records at school", readTitleUz: "Maktab rekordlari",
    readText: "Our school has unofficial records. Aziz is the tallest student in year ten. Madina writes the most interesting stories. The worst coffee is in the old machine near the gym. The best view is from the top floor. The longest lesson on Friday is history, but it is not the most difficult. The most popular club is the English drama group. What is the best thing in your school? What is the worst? Write with the and a superlative every time.",
    speaking: { prompt: "Give five superlatives about your city or school.", promptUz: "Shahar/maktab haqida 5 superlative.", scaffolding: ["the best…", "the most…"] },
    writing: { prompt: "Write 100 words using at least six superlatives.", promptUz: "Kamida 6 superlative bilan 100 so‘z.", minWords: 100, scaffolding: ["the cheapest", "the most useful"] },
  }),
  pack({
    id: "a2-33", day: 33, level: L, topic: "Present Perfect introduction", topicUz: "Present Perfect kirish",
    cefrCanDo: "I can use have/has + past participle with ever, never, been and gone.",
    cefrCanDoUz: "ever, never, been, gone bilan have/has + V3 ishlataman.",
    grammar: g("Present Perfect (intro)", "Hozirgi tugallangan (kirish)",
      "Use Present Perfect for life experience without a finished time: I have been to Khiva. been = went and returned. gone = went and is still there.",
      "Hayotiy tajriba, aniq tugagan vaqt yo‘q: I have been to Khiva. been — borib qaytgan. gone — hali u yerda.",
      "have/has + past participle. ever in questions, never in negatives.",
      "have/has + V3. savolda ever, inkorda never.",
      "The time is not the point; the experience is.",
      "Vaqt emas, tajriba muhim.",
      [{ en: "I have never seen the sea.", uz: "Dengizni hech ko‘rmaganman." }, { en: "Have you ever been to Khiva?", uz: "Xivada bo‘lganmisiz?" }, { en: "She has gone to the shop.", uz: "U do‘konga ketgan (hali yo‘q)." }],
      { form: "haven't / hasn't + V3; never", examples: [{ en: "I haven't finished yet.", uz: "Hali tugatmadim." }] },
      { form: "Have you ever…?", examples: [{ en: "Have you ever eaten sushi?", uz: "Sushi yeganmisiz?" }] },
      [{ wrong: "I have seen it yesterday.", right: "I saw it yesterday.", why: "yesterday needs Past Simple.", whyUz: "yesterday — Past Simple." }, { wrong: "She has went.", right: "She has gone.", why: "Use the past participle gone.", whyUz: "V3: gone." }],
      { vs: "been vs gone", a: "She has been to the shop (and she's back).", b: "She has gone to the shop (she's there now).", note: "been = experience or return; gone = not here.", noteUz: "been — qaytgan; gone — hali u yerda." },
    ),
    vocabulary: [
      W(L, "w-a2-ever", "ever", "qachonlardir", "adverb", "/ˈevə/", "at any time in your life", "Have you ever…?", "Qachonlardir … qilganmisiz?", "time", "Infinity"),
      W(L, "w-a2-never", "never", "hech qachon", "adverb", "/ˈnevə/", "not at any time", "I have never flown.", "Hech uchmaganman.", "time", "Ban"),
      W(L, "w-a2-been", "been", "bo‘lgan", "verb", "/biːn/", "past participle of be; went and returned", "I have been to Kokand.", "Qo‘qonda bo‘lganman.", "travel", "Map"),
      W(L, "w-a2-gone", "gone", "ketgan", "verb", "/ɡɒn/", "past participle of go; not here now", "He has gone home.", "U uyga ketgan.", "travel", "LogOut"),
      W(L, "w-a2-yet", "yet", "hali", "adverb", "/jet/", "until now, in questions and negatives", "Have you finished yet?", "Hali tugatdingizmi?", "time", "Clock"),
      W(L, "w-a2-already", "already", "allaqachon", "adverb", "/ɔːlˈredi/", "sooner than expected", "I have already eaten.", "Allaqachon yedim.", "time", "Check"),
      W(L, "w-a2-just", "just", "hozirgina", "adverb", "/dʒʌst/", "a very short time ago", "She has just arrived.", "U hozirgina keldi.", "time", "Timer"),
      W(L, "w-a2-finish", "finish", "tugatmoq", "verb", "/ˈfɪnɪʃ/", "complete something", "I haven't finished yet.", "Hali tugatmadim.", "daily", "Flag"),
    ],
    phrases: [
      ph("p-a2-have-you", "Have you ever…?", "… qilganmisiz?", "/hæv juː ˈevə/", "Have you ever been to the mountains?", "Tog‘da bo‘lganmisiz?", "Ask three ever-questions."),
      ph("p-a2-never", "I have never…", "Hech qachon … qilmaganman.", "/aɪ hæv ˈnevə/", "I have never ridden a horse.", "Hech ot minmaganman.", "Say two never-experiences."),
      ph("p-a2-already", "I have already…", "Allaqachon…", "/aɪ hæv ɔːlˈredi/", "I have already done my homework.", "Uy vazifamni qildim.", "Say what you have already done today."),
      ph("p-a2-yet", "I haven't … yet.", "Hali … qilmadim.", "/aɪ ˈhævnt jet/", "I haven't called her yet.", "Hali qo‘ng‘iroq qilmadim.", "Say two things you haven't done yet."),
    ],
    listenTitle: "Have you ever…?", listenTitleUz: "Qachonlardir…?",
    lines: [
      { en: "Have you ever been to Khiva?", uz: "Xivada bo‘lganmisiz?" },
      { en: "Yes, I have. I went last spring.", uz: "Ha. O‘tgan bahorda bordim." },
      { en: "Has Ali gone to the shop?", uz: "Ali do‘konga ketdimi?" },
      { en: "Yes. He hasn't come back yet.", uz: "Ha. Hali qaytmadi." },
      { en: "I have never seen the desert.", uz: "Cho‘lni hech ko‘rmaganman." },
      { en: "I've just booked a trip.", uz: "Hozirgina safar band qildim." },
    ],
    readTitle: "Travel club notes", readTitleUz: "Sayohat klubi",
    readText: "Our travel club asks one question every week: Have you ever slept in a tent? I have never slept in a tent, but I have been to the mountains. Madina has already visited three regions this year. Aziz has gone to Nukus — he isn't in class today. I haven't finished my list yet. I have just started a notebook of places. Experience lives in the Present Perfect. Dates live in the Past Simple. I have been to Khiva (experience). I went to Khiva in 2024 (time).",
    speaking: { prompt: "Ask and answer five Have you ever questions.", promptUz: "5 ta Have you ever savol.", scaffolding: ["Have you ever…?", "Yes, I have. / No, I haven't."] },
    writing: { prompt: "Write 100 words about life experience with ever/never/already/yet.", promptUz: "Tajriba haqida 100 so‘z.", minWords: 100, scaffolding: ["I have never…", "I haven't … yet"] },
  }),
  pack({
    id: "a2-34", day: 34, level: L, topic: "Present Perfect vs Past Simple", topicUz: "Present Perfect va Past Simple",
    cefrCanDo: "I can choose between experience (no time) and a finished past time.",
    cefrCanDoUz: "Tajriba (vaqt yo‘q) va tugagan o‘tgan vaqtni ajrataman.",
    grammar: g("PP vs Past Simple", "PP va o‘tgan oddiy",
      "Present Perfect: no finished time (ever, never, already, yet, this week). Past Simple: finished time (yesterday, in 2019, last Monday).",
      "Present Perfect — tugagan vaqt yo‘q. Past Simple — kecha, 2019, o‘tgan dushanba.",
      "Have you been to Samarkand? Yes. I went in 2022.",
      "Have you been…? Yes. I went in 2022.",
      "First mention experience, then give the time in Past Simple.",
      "Avval tajriba, keyin vaqt — Past Simple.",
      [{ en: "I have seen that film. I saw it last Friday.", uz: "O‘sha filmni ko‘rganman. O‘tgan juma ko‘rdim." }, { en: "She has lived here since 2020.", uz: "U 2020 dan beri shu yerda yashaydi." }, { en: "Did you go out yesterday? Yes, I did.", uz: "Kecha tashqariga chiqdingizmi?" }],
      { form: "I didn't go (time) vs I haven't been (experience)", examples: [{ en: "I didn't go yesterday. I haven't been this month.", uz: "Kecha bormadim. Bu oy bo‘lmaganman." }] },
      { form: "Have you…? vs Did you…?", examples: [{ en: "Did you see her yesterday? Have you seen her this week?", uz: "Kecha ko‘rdingizmi? Shu hafta ko‘rdingizmi?" }] },
      [{ wrong: "I have gone there yesterday.", right: "I went there yesterday.", why: "yesterday = Past Simple.", whyUz: "yesterday — Past Simple." }, { wrong: "I saw that film ever.", right: "I have seen that film.", why: "ever belongs with Present Perfect.", whyUz: "ever — Present Perfect." }],
    ),
    vocabulary: [
      W(L, "w-a2-since", "since", "…dan beri", "preposition", "/sɪns/", "from a point in time until now", "since 2020, since Monday", "2020 dan beri", "time", "CalendarClock"),
      W(L, "w-a2-for", "for", "davomida", "preposition", "/fɔː/", "a period of time", "for three years", "uch yil davomida", "time", "Timer"),
      W(L, "w-a2-ago", "ago", "oldin", "adverb", "/əˈɡəʊ/", "before now, with Past Simple", "two days ago", "ikki kun oldin", "time", "History"),
      W(L, "w-a2-this-week", "this week", "shu hafta", "phrase", "/ðɪs wiːk/", "unfinished time period", "I have worked a lot this week.", "Shu hafta ko‘p ishladim.", "time", "Calendar"),
      W(L, "w-a2-live", "live", "yashamoq", "verb", "/lɪv/", "have your home in a place", "I have lived here for a year.", "Bir yildan beri shu yerda yashayman.", "home", "House"),
      W(L, "w-a2-meet", "meet", "uchrashmoq", "verb", "/miːt/", "see someone for the first time or by plan", "Have you met her?", "U bilan tanishganmisiz?", "people", "Handshake"),
      W(L, "w-a2-lose", "lose", "yo‘qotmoq", "verb", "/luːz/", "not have something any more", "I have lost my keys.", "Kalitlarimni yo‘qotdim.", "daily", "KeyRound"),
      W(L, "w-a2-find", "find", "topmoq", "verb", "/faɪnd/", "discover something", "I found them yesterday.", "Kecha topdim.", "daily", "Search"),
    ],
    phrases: [
      ph("p-a2-since", "I have … since…", "…dan beri …", "/sɪns/", "I have lived here since 2021.", "2021 dan beri shu yerdaman.", "Say how long you have studied English."),
      ph("p-a2-for", "I have … for…", "… davomida", "/fɔː/", "I have known her for six years.", "Olti yildan beri taniyman.", "Use for + a period."),
      ph("p-a2-ago", "… ago", "… oldin", "/əˈɡəʊ/", "I met her two years ago.", "Ikki yil oldin tanishdik.", "Give a finished time with ago."),
      ph("p-a2-this-week", "this week I have…", "shu hafta men…", "/ðɪs wiːk/", "This week I have written three emails.", "Shu hafta uchta xat yozdim.", "Say two things you have done this week."),
    ],
    listenTitle: "Keys", listenTitleUz: "Kalitlar",
    lines: [
      { en: "Have you seen my keys?", uz: "Kalitlarimni ko‘rdingizmi?" },
      { en: "I saw them yesterday on the table.", uz: "Kecha stolda ko‘rdim." },
      { en: "I have looked this morning. They aren't there.", uz: "Bugun ertalab qaredim. Yo‘q." },
      { en: "Have you lost them again?", uz: "Yana yo‘qotdingizmi?" },
      { en: "I haven't lost them. I found them last week.", uz: "Yo‘qotmadim. O‘tgan hafta topdim." },
      { en: "Then you put them somewhere this week.", uz: "Demak shu hafta biror yerga qo‘ygansiz." },
    ],
    readTitle: "Two tenses, one story", readTitleUz: "Ikki zamon, bitta hikoya",
    readText: "I have known my friend Nilufar for ten years. I met her in school in 2015. This week we have spoken every day, but yesterday we didn't meet because she went to the dentist. She has lived in Andijan since 2020. She moved there after university. Have you ever had a friend like that — someone you have known for years, even if you didn't talk yesterday? Choose the tense with the time word, or with the missing time.",
    speaking: { prompt: "Tell a mini story: experience then a dated event.", promptUz: "Avval tajriba, keyin sana.", scaffolding: ["I have…", "I … yesterday."] },
    writing: { prompt: "Write 110 words mixing Present Perfect and Past Simple correctly.", promptUz: "Ikki zamonni aralashtirib 110 so‘z.", minWords: 110, scaffolding: ["I have lived…", "I moved…"] },
  }),
];
