import type { Lesson } from "@/lib/types";
import { pack, W, ph } from "@/lib/content/pack";

const L = "a2" as const;

function g(
  title: string,
  titleUz: string,
  meaning: string,
  meaningUz: string,
  form: string,
  formUz: string,
  why: string,
  whyUz: string,
  examples: { en: string; uz: string }[],
  negative: { form: string; examples: { en: string; uz: string }[] },
  question: { form: string; examples: { en: string; uz: string }[] },
  mistakes: { wrong: string; right: string; why: string; whyUz: string }[],
  contrast?: { vs: string; a: string; b: string; note: string; noteUz: string },
) {
  return { title, titleUz, meaning, meaningUz, form, formUz, why, whyUz, examples, negative, question, mistakes, contrast };
}

export const lessons: Lesson[] = [
  pack({
    id: "a2-27",
    day: 27,
    level: L,
    topic: "Past Simple regular verbs",
    topicUz: "O‘tgan oddiy zamon: qoidali fe’llar",
    cefrCanDo: "I can talk about finished past actions with regular -ed verbs.",
    cefrCanDoUz: "Qoidali -ed fe’llar bilan tugallangan o‘tgan ishlarni aytaman.",
    grammar: g(
      "Past Simple regular",
      "O‘tgan oddiy: qoidali",
      "Use Past Simple for a finished action at a known time: yesterday, last week, in 2020.",
      "Tugallangan, vaqti ma’lum ish: yesterday, last week.",
      "verb + ed (work→worked, play→played, study→studied). I/you/he/she/we/they all use the same past form.",
      "fe’l + ed. Barcha egalar uchun bir xil shakl.",
      "English marks finished time on the verb, not only with a time word.",
      "Ingliz tili tugallanganlikni fe’lda ham ko‘rsatadi.",
      [
        { en: "I visited my aunt yesterday.", uz: "Kecha xolamnikiga bordim." },
        { en: "She studied English last year.", uz: "U o‘tgan yili ingliz tilini o‘rgandi." },
        { en: "We played football on Sunday.", uz: "Yakshanba kuni futbol o‘ynadik." },
      ],
      { form: "did not / didn't + base verb (not worked)", examples: [{ en: "I didn't visit my aunt.", uz: "Xolamnikiga bormadim." }] },
      { form: "Did + subject + base verb?", examples: [{ en: "Did you visit your aunt?", uz: "Xolangiznikiga bordingizmi?" }] },
      [
        { wrong: "I didn't visited my aunt.", right: "I didn't visit my aunt.", why: "After didn't use the base form.", whyUz: "didn't dan keyin asosiy fe’l." },
        { wrong: "She studyed English.", right: "She studied English.", why: "y after a consonant → ied.", whyUz: "undosh + y → ied." },
      ],
      { vs: "Present Simple vs Past Simple", a: "I visit my aunt every Friday.", b: "I visited my aunt yesterday.", note: "Habits now vs finished past.", noteUz: "Odat vs tugagan o‘tmish." },
    ),
    vocabulary: [
      W(L, "w-a2-visit", "visit", "tashrif buyurmoq", "verb", "/ˈvɪzɪt/", "go to see a person or place", "I visited Samarkand last month.", "O‘tgan oy Samarqandga bordim.", "travel", "MapPin", { family: [{ form: "visitor", pos: "noun" }] }),
      W(L, "w-a2-yesterday", "yesterday", "kecha", "adverb", "/ˈjestədeɪ/", "the day before today", "Yesterday I stayed at home.", "Kecha uyda qoldim.", "time", "Calendar"),
      W(L, "w-a2-last", "last week", "o‘tgan hafta", "phrase", "/lɑːst wiːk/", "the week before this one", "We travelled last week.", "O‘tgan hafta sayohat qildik.", "time", "Calendar"),
      W(L, "w-a2-play", "play", "o‘ynamoq", "verb", "/pleɪ/", "take part in a game or music", "They played tennis.", "Ular tennis o‘ynashdi.", "hobbies", "Trophy"),
      W(L, "w-a2-study", "study", "o‘qimoq", "verb", "/ˈstʌdi/", "learn about a subject", "He studied for two hours.", "U ikki soat o‘qidi.", "school", "BookOpen"),
      W(L, "w-a2-stay", "stay", "qolmoq", "verb", "/steɪ/", "remain in a place", "We stayed in a small hotel.", "Kichik mehmonxonada qoldik.", "travel", "Hotel"),
      W(L, "w-a2-arrive", "arrive", "yetib kelmoq", "verb", "/əˈraɪv/", "reach a place", "The bus arrived at six.", "Avtobus oltida keldi.", "travel", "Bus"),
      W(L, "w-a2-enjoy", "enjoy", "rohatlanmoq", "verb", "/ɪnˈdʒɔɪ/", "like doing something", "I enjoyed the concert.", "Konsert menga yoqdi.", "feelings", "Smile"),
    ],
    phrases: [
      ph("p-a2-yday", "Yesterday I…", "Kecha men…", "/ˈjestədeɪ aɪ/", "Yesterday I cooked dinner.", "Kecha kechki ovqat pishirdim.", "Say three things you did yesterday."),
      ph("p-a2-last", "Last weekend we…", "O‘tgan dam olishda biz…", "/lɑːst ˈwiːkend wiː/", "Last weekend we visited friends.", "O‘tgan damda do‘stlarnikiga bordik.", "Talk about last weekend."),
      ph("p-a2-didnt", "I didn't…", "Men … qilmadim.", "/aɪ ˈdɪdnt/", "I didn't watch TV.", "TV ko‘rmadim.", "Say two things you didn't do."),
      ph("p-a2-did-you", "Did you…?", "… qildingizmi?", "/dɪd juː/", "Did you enjoy it?", "Yoqdimi?", "Ask two past questions."),
    ],
    listenTitle: "A quiet Sunday",
    listenTitleUz: "Sokin yakshanba",
    lines: [
      { en: "Did you stay at home yesterday?", uz: "Kecha uyda qoldingizmi?" },
      { en: "Yes. I cooked and I cleaned.", uz: "Ha. Pishirdim va tozaladim." },
      { en: "I visited my aunt in the afternoon.", uz: "Tushdan keyin xolamnikiga bordim." },
      { en: "Did she cook too?", uz: "U ham pishirdimi?" },
      { en: "No, she didn't. We played cards.", uz: "Yo‘q. Qarta o‘ynadik." },
      { en: "I enjoyed the day.", uz: "Kun yoqdi." },
    ],
    readTitle: "My weekend",
    readTitleUz: "Dam olish kunim",
    readText:
      "Last Saturday I stayed in Tashkent. I visited my cousin in the morning and we walked in the park. In the afternoon I cooked plov with my mother. We didn't watch TV. We talked and we listened to music. In the evening my friends arrived. We played a board game and I enjoyed every minute. Yesterday was quiet but happy. I didn't travel, but I didn't feel bored. Next weekend I want to visit Bukhara. Did you stay at home last weekend too? Call me and tell me.",
    speaking: { prompt: "Tell me what you did last weekend. Use four regular past verbs.", promptUz: "O‘tgan damda nima qilganingizni ayting.", scaffolding: ["Yesterday I…", "I didn't…", "Did you…?"] },
    writing: { prompt: "Write 90 words about last weekend using regular Past Simple.", promptUz: "O‘tgan dam haqida 90 so‘z.", minWords: 90, scaffolding: ["Last Saturday I…", "I didn't…"] },
  }),
  pack({
    id: "a2-28",
    day: 28,
    level: L,
    topic: "Past Simple irregular verbs",
    topicUz: "O‘tgan oddiy: noto‘g‘ri fe’llar",
    cefrCanDo: "I can use common irregular past forms: went, had, saw, made, took.",
    cefrCanDoUz: "Went, had, saw, made, took kabi noto‘g‘ri o‘tgan shakllarni ishlataman.",
    grammar: g(
      "Irregular past",
      "Noto‘g‘ri o‘tgan shakl",
      "Many common verbs do not take -ed. You learn the past form as a new word: go→went.",
      "Ko‘p ishlatiladigan fe’llar -ed olmaydi. O‘tgan shakl alohida yodlanadi.",
      "go-went, have-had, see-saw, make-made, take-took, come-came, get-got, eat-ate, drink-drank, write-wrote.",
      "go-went, have-had, see-saw…",
      "These verbs are everywhere in stories. Without them you cannot narrate a day.",
      "Hikoya qilish uchun shu fe’llar shart.",
      [
        { en: "I went to the market.", uz: "Bozorga bordim." },
        { en: "She had a great time.", uz: "U zo‘r vaqt o‘tkazdi." },
        { en: "We saw an old mosque.", uz: "Eski masjidni ko‘rdik." },
      ],
      { form: "didn't + base (didn't go, not didn't went)", examples: [{ en: "I didn't go out.", uz: "Tashqariga chiqmadim." }] },
      { form: "Did you go…?", examples: [{ en: "Did you see the film?", uz: "Filmni ko‘rdingizmi?" }] },
      [
        { wrong: "I goed to school.", right: "I went to school.", why: "go is irregular: went.", whyUz: "go → went." },
        { wrong: "Did you went home?", right: "Did you go home?", why: "After did use the base form.", whyUz: "did dan keyin asosiy fe’l." },
      ],
    ),
    vocabulary: [
      W(L, "w-a2-go", "go", "bormoq", "verb", "/ɡəʊ/", "move or travel", "I went to work by bus.", "Ishga avtobusda bordim.", "travel", "Footprints", { family: [{ form: "went", pos: "verb" }] }),
      W(L, "w-a2-see", "see", "ko‘rmoq", "verb", "/siː/", "notice with your eyes", "I saw my teacher.", "O‘qituvchimni ko‘rdim.", "senses", "Eye"),
      W(L, "w-a2-have", "have", "eга bo‘lmoq / qilmoq", "verb", "/hæv/", "possess or experience", "We had breakfast at eight.", "Sakkizda nonushta qildik.", "daily", "Coffee"),
      W(L, "w-a2-make", "make", "yasamoq", "verb", "/meɪk/", "create or produce", "She made tea.", "U choy qildi.", "daily", "Hammer"),
      W(L, "w-a2-take", "take", "olmoq", "verb", "/teɪk/", "move something with you", "He took a taxi.", "U taksi oldi.", "travel", "Car"),
      W(L, "w-a2-come", "come", "kelmoq", "verb", "/kʌm/", "move towards the speaker", "They came late.", "Ular kech kelishdi.", "travel", "LogIn"),
      W(L, "w-a2-eat", "eat", "yemoq", "verb", "/iːt/", "put food in your mouth", "I ate laghman.", "Lag‘mon yedim.", "food", "Utensils"),
      W(L, "w-a2-write", "write", "yozmoq", "verb", "/raɪt/", "make words on paper or screen", "I wrote a short email.", "Qisqa xat yozdim.", "school", "PenLine"),
    ],
    phrases: [
      ph("p-a2-went", "I went to…", "Men … ga bordim.", "/aɪ went tə/", "I went to the bazaar.", "Bozorga bordim.", "Say three places you went."),
      ph("p-a2-had-time", "I had a great time.", "Zo‘r vaqt o‘tkazdim.", "/aɪ hæd ə ɡreɪt taɪm/", "We had a great time in Khiva.", "Xivada zo‘r vaqt.", "Use had a great time."),
      ph("p-a2-saw", "I saw…", "Men … ni ko‘rdim.", "/aɪ sɔː/", "I saw my neighbours.", "Qo‘shnilarni ko‘rdim.", "Say two things you saw."),
      ph("p-a2-didnt-go", "I didn't go…", "… ga bormadim.", "/aɪ ˈdɪdnt ɡəʊ/", "I didn't go out last night.", "Kecha tashqariga chiqmadim.", "Say where you didn't go."),
    ],
    listenTitle: "A trip to the bazaar",
    listenTitleUz: "Bozorga safar",
    lines: [
      { en: "I went to the bazaar at nine.", uz: "To‘qqizda bozorga bordim." },
      { en: "I saw a lot of fruit.", uz: "Ko‘p meva ko‘rdim." },
      { en: "I had a cup of tea.", uz: "Bir piyola choy ichdim." },
      { en: "My friend came with me.", uz: "Do‘stim bilan keldi." },
      { en: "We ate bread and took photos.", uz: "Non yedik va rasm oldik." },
      { en: "I didn't buy a carpet.", uz: "Gilam olmadim." },
    ],
    readTitle: "Friday in the old city",
    readTitleUz: "Eski shaharda juma",
    readText:
      "On Friday I went to the old city with my brother. We took a bus and we came back late. I saw beautiful wood doors and I wrote three new words in my notebook. We had lunch in a small chaikhana. I ate somsa and I drank green tea. My brother made a joke and I laughed. We didn't go to the museum because it closed at five. I had a great time. Did you go out on Friday? Write to me and tell me what you saw.",
    speaking: { prompt: "Narrate yesterday with five irregular verbs.", promptUz: "Kechagi kuningizni 5 noto‘g‘ri fe’l bilan aytib bering.", scaffolding: ["I went…", "I saw…", "I had…"] },
    writing: { prompt: "Write 100 words about a short trip using irregular past verbs.", promptUz: "Qisqa safar haqida 100 so‘z.", minWords: 100, scaffolding: ["I went to…", "I didn't…"] },
  }),
  pack({
    id: "a2-29",
    day: 29,
    level: L,
    topic: "Past Simple vs Past Continuous",
    topicUz: "Past Simple va Past Continuous",
    cefrCanDo: "I can contrast a finished action with an action in progress in the past.",
    cefrCanDoUz: "Tugagan ishni o‘tmishda davom etayotgan ish bilan solishtiraman.",
    grammar: g(
      "Past Simple vs Past Continuous",
      "O‘tgan oddiy va o‘tgan davomiy",
      "Past Continuous = an action in progress at a past moment. Past Simple = a shorter finished action that interrupts it.",
      "Past Continuous — o‘tmishda davom etayotgan jarayon. Past Simple — uni to‘xtatgan qisqa ish.",
      "was/were + -ing. I was watching TV when he called.",
      "was/were + -ing. I was watching TV when he called.",
      "This pair tells a story with background and event.",
      "Fon va voqea bilan hikoya qilish uchun.",
      [
        { en: "I was watching TV when he called.", uz: "U qo‘ng‘iroq qilganda TV ko‘rayotgan edim." },
        { en: "While she was cooking, I set the table.", uz: "U pishirayotganda men dasturxon yozdim." },
        { en: "They were walking home when it started to rain.", uz: "Yomg‘ir boshlaganda ular uyga ketayotgan edi." },
      ],
      { form: "wasn't/weren't + -ing", examples: [{ en: "I wasn't sleeping.", uz: "Uxlamayotgan edim." }] },
      { form: "Was/Were + subject + -ing?", examples: [{ en: "Were you working at 8?", uz: "Sakkizda ishlayotgan edingizmi?" }] },
      [
        { wrong: "I was watch TV when he called.", right: "I was watching TV when he called.", why: "Need -ing after was.", whyUz: "was dan keyin -ing." },
        { wrong: "When he was calling, I watched TV. (for interruption)", right: "I was watching TV when he called.", why: "Long action = continuous; short interrupt = simple.", whyUz: "Uzun — continuous, qisqa — simple." },
      ],
      { vs: "when vs while", a: "when + Past Simple (the event)", b: "while + Past Continuous (the background)", note: "while I was working / when the phone rang", noteUz: "while — fon, when — voqea." },
    ),
    vocabulary: [
      W(L, "w-a2-when", "when", "qachon / -ganda", "conjunction", "/wen/", "at the time that", "I was cooking when you arrived.", "Siz kelganingizda pishirayotgan edim.", "grammar", "Clock"),
      W(L, "w-a2-while", "while", "paytda", "conjunction", "/waɪl/", "during the time that", "While I was reading, she slept.", "Men o‘qiyotganda u uxlar edi.", "grammar", "Clock"),
      W(L, "w-a2-call", "call", "qo‘ng‘iroq qilmoq", "verb", "/kɔːl/", "phone someone", "He called me at ten.", "U o‘nda qo‘ng‘iroq qildi.", "daily", "Phone"),
      W(L, "w-a2-rain", "rain", "yomg‘ir", "noun", "/reɪn/", "water from the sky", "It started to rain.", "Yomg‘ir boshladi.", "weather", "CloudRain"),
      W(L, "w-a2-walk", "walk", "yurmoq", "verb", "/wɔːk/", "move on foot", "We were walking to school.", "Maktabga ketayotgan edik.", "daily", "Footprints"),
      W(L, "w-a2-sleep", "sleep", "uxlamoq", "verb", "/sliːp/", "rest at night", "She was sleeping.", "U uxlayotgan edi.", "daily", "Moon"),
      W(L, "w-a2-cook", "cook", "pishirmoq", "verb", "/kʊk/", "prepare food", "I was cooking dinner.", "Kechki ovqat pishirayotgan edim.", "food", "ChefHat"),
      W(L, "w-a2-start", "start", "boshlanmoq", "verb", "/stɑːt/", "begin", "The film started at nine.", "Film to‘qqizda boshlandi.", "time", "Play"),
    ],
    phrases: [
      ph("p-a2-when-he", "I was … when he…", "U … qilganda men … edim.", "/aɪ wəz wen hiː/", "I was having a shower when he called.", "U qo‘ng‘iroq qilganda dushda edim.", "Make two when-sentences."),
      ph("p-a2-while-i", "While I was…", "Men … paytda", "/waɪl aɪ wəz/", "While I was working, it started to rain.", "Ishlayotganimda yomg‘ir boshlandi.", "Make a while-sentence."),
      ph("p-a2-wasnt", "I wasn't sleeping.", "Uxlamayotgan edim.", "/aɪ ˈwɒznt ˈsliːpɪŋ/", "I wasn't sleeping. I was reading.", "Uxlamayotgan edim. O‘qiyotgan edim.", "Say what you weren't doing at 9pm."),
      ph("p-a2-were-you", "What were you doing?", "Nima qilayotgan edingiz?", "/wɒt wə juː ˈduːɪŋ/", "What were you doing at six?", "Oltida nima qilayotgan edingiz?", "Ask a friend about 7pm yesterday."),
    ],
    listenTitle: "When the phone rang",
    listenTitleUz: "Telefon jiringlaganda",
    lines: [
      { en: "What were you doing at seven?", uz: "Yetida nima qilayotgan edingiz?" },
      { en: "I was cooking when you called.", uz: "Siz qo‘ng‘iroq qilganda pishirayotgan edim." },
      { en: "I wasn't watching TV.", uz: "TV ko‘rmayotgan edim." },
      { en: "While I was cooking, it started to rain.", uz: "Pishirayotganimda yomg‘ir boshlandi." },
      { en: "Were you walking home?", uz: "Uyga ketayotgan edingizmi?" },
      { en: "No. I was already at home.", uz: "Yo‘q. Allaqachon uyda edim." },
    ],
    readTitle: "A noisy evening",
    readTitleUz: "Shovqinli oqshom",
    readText:
      "Yesterday evening I was sitting in the kitchen. I was cooking soup when my sister called. While we were talking, someone knocked at the door. I wasn't expecting a visitor. It was our neighbour. He was holding a wet umbrella because it was raining. We were laughing when the electricity stopped. I didn't panic. I found a candle and we continued our conversation. What were you doing at that time? Maybe you were sleeping, or maybe you were walking home in the rain.",
    speaking: { prompt: "Describe yesterday 7pm: background + one interruption.", promptUz: "Kecha soat 7: fon + bitta voqea.", scaffolding: ["I was… when…", "While I was…"] },
    writing: { prompt: "Write 110 words: an evening with Past Simple and Past Continuous.", promptUz: "Oqshom haqida 110 so‘z.", minWords: 110, scaffolding: ["I was…", "when…"] },
  }),
];
