import type { Lesson, Exercise } from "@/lib/types";
import { pack, W, ph } from "@/lib/content/pack";
import { tr, gap, mcq, errx, order } from "@/lib/content/helpers";

const DOMAIN_EXAMPLES: Record<string, { en: string; uz: string }[]> = {
  work: [
    { en: "The team had already agreed on the deadline before the meeting started.", uz: "Jamoa yig‘ilish boshlanishidan oldin muddatga kelishib bo‘lgan edi." },
    { en: "If the schedule changes, we will inform everyone immediately.", uz: "Agar jadval o‘zgarsa, hammaga darhol xabar beramiz." },
  ],
  technology: [
    { en: "The system is being tested before the update is released.", uz: "Yangilanish chiqarilishidan oldin tizim sinovdan o‘tkazilmoqda." },
    { en: "The results suggest that the new interface is easier to use.", uz: "Natijalar yangi interfeysdan foydalanish osonroq ekanini ko‘rsatmoqda." },
  ],
  education: [
    { en: "Students who practise regularly tend to remember new structures longer.", uz: "Muntazam mashq qiladigan talabalar yangi tuzilmalarni uzoqroq eslab qolishga moyil." },
    { en: "The evidence should be considered before a final conclusion is made.", uz: "Yakuniy xulosa chiqarilishidan oldin dalil hisobga olinishi kerak." },
  ],
  society: [
    { en: "Although the policy was ambitious, its implementation remained uneven.", uz: "Siyosat katta maqsadlarni ko‘zlagan bo‘lsa-da, uning amalga oshirilishi bir xil bo‘lmadi." },
    { en: "The issue has become more complicated than it first appeared.", uz: "Masala dastlab ko‘ringanidan ko‘ra murakkabroq bo‘lib chiqdi." },
  ],
  environment: [
    { en: "By 2030, the city will have reduced its energy consumption significantly.", uz: "2030-yilga kelib, shahar energiya sarfini sezilarli darajada kamaytirgan bo‘ladi." },
    { en: "The researchers warned that the habitat could disappear without protection.", uz: "Tadqiqotchilar himoya bo‘lmasa, yashash muhiti yo‘qolishi mumkinligidan ogohlantirdi." },
  ],
  health: [
    { en: "She had been feeling tired for weeks before she changed her routine.", uz: "U kundalik tartibini o‘zgartirishidan oldin bir necha hafta davomida charchoqni his qilgan edi." },
    { en: "Patients should be given clear instructions before leaving the clinic.", uz: "Bemorlar klinikadan chiqishidan oldin ularga aniq ko‘rsatmalar berilishi kerak." },
  ],
  media: [
    { en: "The journalist checked the original source before publishing the claim.", uz: "Jurnalist da’voni e’lon qilishdan oldin asl manbani tekshirdi." },
    { en: "The report may have been misunderstood because the headline was too brief.", uz: "Sarlavha juda qisqa bo‘lgani uchun hisobot noto‘g‘ri tushunilgan bo‘lishi mumkin." },
  ],
  culture: [
    { en: "The festival, which attracts visitors every year, preserves a local tradition.", uz: "Har yili mehmonlarni jalb qiladigan festival mahalliy an’anani saqlab qoladi." },
    { en: "What matters most is how the tradition is passed to younger generations.", uz: "Eng muhimi, an’ananing yosh avlodlarga qanday o‘tkazilishidir." },
  ],
  science: [
    { en: "The study appears to indicate a link between the two variables.", uz: "Tadqiqot ikki o‘zgaruvchi o‘rtasida bog‘liqlik borligini ko‘rsatayotganga o‘xshaydi." },
    { en: "No matter how carefully the experiment is designed, uncertainty remains.", uz: "Tajriba qanchalik ehtiyotkorlik bilan tuzilmasin, noaniqlik saqlanib qoladi." },
  ],
  business: [
    { en: "The company would have avoided the loss if it had reviewed the contract earlier.", uz: "Agar kompaniya shartnomani oldinroq ko‘rib chiqqanida, zararning oldini olgan bo‘lardi." },
    { en: "The proposal warrants further consideration before the board makes a decision.", uz: "Kengash qaror qabul qilishidan oldin taklif qo‘shimcha ko‘rib chiqishga loyiq." },
  ],
};

function grammar(title: string, meaning: string, form: string, ex: string, exUz: string, wrong: string, right: string, domain = "education"): any {
  const pool = DOMAIN_EXAMPLES[domain] ?? DOMAIN_EXAMPLES.education;
  const examples = [{ en: ex, uz: exUz }, ...pool.filter((x) => x.en !== ex).slice(0, 2)];
  return {
    title, titleUz: title, meaning, meaningUz: meaning, form, formUz: form, why: meaning, whyUz: meaning,
    examples,
    negative: { form: `Negative/contrast form: ${form}`, examples: [{ en: pool[0]!.en, uz: pool[0]!.uz }] },
    question: { form: `Question pattern: ${form}`, examples: [{ en: `Why does this structure fit the context?`, uz: `Nima uchun bu tuzilma ushbu kontekstga mos keladi?` }] },
    mistakes: [{ wrong, right, why: meaning, whyUz: meaning }, { wrong, right, why: `Check the form and the time reference.`, whyUz: `Shakl va vaqt ma’nosini tekshiring.` }],
  };
}

function makeLesson(
  id: string, day: number, level: Lesson["level"], topic: string, topicUz: string, gTitle: string, form: string, ex: string, exUz: string,
  domain: string, cefr: string, cefrUz: string,
): Lesson {
  const domainWords: Record<string, Array<[string,string,string,string,string]>> = {
    work: [
      ["deadline","muddat","noun","/ˈdedlaɪn/","the latest time something must be completed"],["colleague","hamkasb","noun","/ˈkɒliːɡ/","a person you work with"],["negotiate","muzokara qilmoq","verb","/nɪˈɡəʊʃieɪt/","try to reach an agreement"],["efficient","samarali","adjective","/ɪˈfɪʃənt/","working well without wasting time"],["reliable","ishonchli","adjective","/rɪˈlaɪəbl/","able to be trusted or depended on"],["priority","ustuvor vazifa","noun","/praɪˈɒrəti/","something treated as more important than others"],["feedback","fikr-mulohaza","noun","/ˈfiːdbæk/","comments that help improve performance"],["meeting","yig‘ilish","noun","/ˈmiːtɪŋ/","an organised discussion"],["strategy","strategiya","noun","/ˈstrætədʒi/","a plan designed to achieve a goal"],["outcome","natija","noun","/ˈaʊtkʌm/","the result of an action or process"],["budget","byudjet","noun","/ˈbʌdʒɪt/","a plan for spending money"],["responsibility","mas’uliyat","noun","/rɪˌspɒnsəˈbɪləti/","a duty that you are expected to deal with"]
    ],
    technology: [
      ["algorithm","algoritm","noun","/ˈælɡərɪðəm/","a set of rules used to solve a problem"],["device","qurilma","noun","/dɪˈvaɪs/","a piece of electronic equipment"],["privacy","maxfiylik","noun","/ˈprɪvəsi/","control over personal information"],["update","yangilamoq","verb","/ʌpˈdeɪt/","make software or information more current"],["feature","xususiyat","noun","/ˈfiːtʃə/","an important part or function"],["network","tarmoq","noun","/ˈnetwɜːk/","a connected system of computers or people"],["secure","xavfsiz","adjective","/sɪˈkjʊə/","protected from danger or unauthorised access"],["data","ma’lumotlar","noun","/ˈdeɪtə/","information collected for analysis"],["platform","platforma","noun","/ˈplætfɔːm/","a system or service used to provide something"],["access","kirish imkoniyati","noun","/ˈækses/","the right or ability to use something"],["interface","interfeys","noun","/ˈɪntəfeɪs/","the part through which a user interacts with software"],["automation","avtomatlashtirish","noun","/ˌɔːtəˈmeɪʃən/","use of technology to perform tasks automatically"]
    ],
    education: [
      ["curriculum","o‘quv dasturi","noun","/kəˈrɪkjələm/","the subjects and content taught in a course"],["assignment","topshiriq","noun","/əˈsaɪnmənt/","a piece of work given to a learner"],["assessment","baholash","noun","/əˈsesmənt/","the process of measuring learning"],["research","tadqiqot","noun","/rɪˈsɜːtʃ/","careful study to discover facts"],["lecture","ma’ruza","noun","/ˈlektʃə/","an educational talk"],["evidence","dalil","noun","/ˈevɪdəns/","information that supports a conclusion"],["academic","akademik","adjective","/ˌækəˈdemɪk/","related to education or study"],["skill","ko‘nikma","noun","/skɪl/","an ability developed through practice"],["feedback","fikr-mulohaza","noun","/ˈfiːdbæk/","comments intended to improve work"],["progress","rivojlanish","noun","/ˈprəʊɡres/","movement towards a better or higher level"],["scholarship","stipendiya","noun","/ˈskɒləʃɪp/","financial support for study"],["qualification","malaka","noun","/ˌkwɒlɪfɪˈkeɪʃən/","an official achievement showing ability"]
    ],
    society: [
      ["community","hamjamiyat","noun","/kəˈmjuːnəti/","people living or working together"],["inequality","tengsizlik","noun","/ˌɪnɪˈkwɒləti/","an unfair difference in status or resources"],["policy","siyosat/qoidalar","noun","/ˈpɒləsi/","a plan or set of principles used by an organisation"],["citizen","fuqaro","noun","/ˈsɪtɪzn/","a legally recognised member of a country"],["migration","migratsiya","noun","/maɪˈɡreɪʃən/","movement from one place to another"],["housing","uy-joy","noun","/ˈhaʊzɪŋ/","houses and accommodation"],["public","jamoatga oid","adjective","/ˈpʌblɪk/","relating to the general population"],["debate","munozara","noun","/dɪˈbeɪt/","a formal or organised discussion"],["welfare","ijtimoiy farovonlik","noun","/ˈwelfeə/","health, happiness, and basic support"],["access","foydalanish imkoniyati","noun","/ˈækses/","the ability or right to use something"],["opportunity","imkoniyat","noun","/ˌɒpəˈtjuːnəti/","a favourable chance"],["impact","ta’sir","noun","/ˈɪmpækt/","a strong effect on something"]
    ],
    environment: [
      ["emission","chiqindi gaz","noun","/ɪˈmɪʃən/","a gas or substance released into the environment"],["renewable","qayta tiklanuvchi","adjective","/rɪˈnjuːəbl/","able to be replaced naturally"],["conservation","muhofaza qilish","noun","/ˌkɒnsəˈveɪʃən/","protection of nature or resources"],["climate","iqlim","noun","/ˈklaɪmət/","the usual weather conditions of a place"],["resource","resurs","noun","/rɪˈsɔːs/","a useful supply of something"],["waste","chiqindi","noun","/weɪst/","unwanted material"],["sustainable","barqaror","adjective","/səˈsteɪnəbl/","able to continue without causing serious harm"],["habitat","yashash muhiti","noun","/ˈhæbɪtæt/","the natural home of a plant or animal"],["drought","qurg‘oqchilik","noun","/draʊt/","a long period without enough rain"],["recycle","qayta ishlamoq","verb","/ˌriːˈsaɪkl/","process used materials so they can be used again"],["carbon","uglerod","noun","/ˈkɑːbən/","a chemical element found in many fuels and living things"],["biodiversity","biologik xilma-xillik","noun","/ˌbaɪəʊdaɪˈvɜːsəti/","the variety of living things in an area"]
    ],
    health: [
      ["symptom","alomat","noun","/ˈsɪmptəm/","a sign of an illness or condition"],["treatment","davolash","noun","/ˈtriːtmənt/","medical care given for a condition"],["prevention","oldini olish","noun","/prɪˈvenʃən/","action taken to stop something happening"],["diagnosis","tashxis","noun","/ˌdaɪəɡˈnəʊsɪs/","identification of an illness"],["recovery","tiklanish","noun","/rɪˈkʌvəri/","return to health or normal condition"],["routine","odatdagi tartib","noun","/ruːˈtiːn/","a regular way of doing things"],["mental","ruhiy","adjective","/ˈmentl/","related to the mind"],["physical","jismoniy","adjective","/ˈfɪzɪkl/","related to the body"],["nutrition","ovqatlanish","noun","/njuˈtrɪʃən/","the process of getting nutrients from food"],["risk","xavf","noun","/rɪsk/","the possibility of harm"],["patient","bemor","noun","/ˈpeɪʃənt/","a person receiving medical care"],["therapy","terapiya","noun","/ˈθerəpi/","treatment intended to improve a condition"]
    ],
    media: [
      ["headline","sarlavha","noun","/ˈhedlaɪn/","the title of a news story"],["source","manba","noun","/sɔːs/","the origin of information"],["bias","xolis bo‘lmaslik","noun","/ˈbaɪəs/","an unfair preference or viewpoint"],["report","hisobot/xabar","noun","/rɪˈpɔːt/","a written or spoken account of events"],["audience","auditoriya","noun","/ˈɔːdiəns/","people who watch, read, or listen"],["broadcast","efirga uzatmoq","verb","/ˈbrɔːdkɑːst/","send a programme to the public"],["claim","da’vo","noun","/kleɪm/","a statement that something is true"],["journalist","jurnalist","noun","/ˈdʒɜːnəlɪst/","a person who gathers and reports news"],["platform","platforma","noun","/ˈplætfɔːm/","a service where content or communication happens"],["viral","tez tarqaluvchi","adjective","/ˈvaɪrəl/","spreading very quickly online"],["coverage","yoritish","noun","/ˈkʌvərɪdʒ/","the reporting of an event or topic"],["comment","izoh","noun","/ˈkɒment/","an opinion or response"]
    ],
    business: [
      ["revenue","daromad","noun","/ˈrevənjuː/","money earned by an organisation"],["investment","investitsiya","noun","/ɪnˈvestmənt/","money put into something to gain a return"],["market","bozor","noun","/ˈmɑːkɪt/","the area where buyers and sellers interact"],["customer","mijoz","noun","/ˈkʌstəmə/","a person or organisation that buys something"],["profit","foyda","noun","/ˈprɒfɪt/","money left after costs are paid"],["launch","ishga tushirmoq","verb","/lɔːntʃ/","introduce a product or service"],["demand","talab","noun","/dɪˈmɑːnd/","the desire or need for something"],["supply","ta’minot","noun","/səˈplaɪ/","the amount available to meet demand"],["contract","shartnoma","noun","/ˈkɒntrækt/","a formal legal agreement"],["brand","brend","noun","/brænd/","a product identity recognised by customers"],["growth","o‘sish","noun","/ɡrəʊθ/","an increase in size or value"],["competitor","raqobatchi","noun","/kəmˈpetɪtə/","a person or company competing with another"]
    ],
    culture: [
      ["heritage","meros","noun","/ˈherɪtɪdʒ/","traditions and objects passed between generations"],["tradition","an’ana","noun","/trəˈdɪʃən/","a custom passed through generations"],["identity","o‘zlik","noun","/aɪˈdentəti/","the qualities that define a person or group"],["artistic","badiiy","adjective","/ɑːˈtɪstɪk/","related to art"],["festival","festival/bayram","noun","/ˈfestɪvl/","an organised cultural celebration"],["custom","urf-odat","noun","/ˈkʌstəm/","a traditional way of behaving"],["generation","avlod","noun","/ˌdʒenəˈreɪʃən/","people born around the same period"],["influence","ta’sir","noun","/ˈɪnfluəns/","the power to affect someone or something"],["diverse","xilma-xil","adjective","/daɪˈvɜːs/","including many different types of people or things"],["language","til","noun","/ˈlæŋɡwɪdʒ/","a system used for communication"],["value","qadriyat","noun","/ˈvæljuː/","a principle considered important"],["symbol","ramz","noun","/ˈsɪmbəl/","a sign that represents an idea"]
    ],
    science: [
      ["hypothesis","gipoteza","noun","/haɪˈpɒθəsɪs/","an idea tested by investigation"],["method","usul","noun","/ˈmeθəd/","a way of doing something systematically"],["experiment","tajriba","noun","/ɪkˈsperɪmənt/","a scientific test"],["variable","o‘zgaruvchi","noun","/ˈveəriəbl/","a factor that can change"],["finding","topilma/natija","noun","/ˈfaɪndɪŋ/","a result discovered through research"],["theory","nazariya","noun","/ˈθɪəri/","an explanation supported by evidence"],["sample","namuna","noun","/ˈsɑːmpl/","a smaller group representing a larger one"],["measure","o‘lchamoq","verb","/ˈmeʒə/","find the size or amount of something"],["result","natija","noun","/rɪˈzʌlt/","the outcome of an action or study"],["observe","kuzatmoq","verb","/əbˈzɜːv/","watch carefully to notice something"],["evidence","dalil","noun","/ˈevɪdəns/","facts or information supporting a conclusion"],["conclusion","xulosa","noun","/kənˈkluːʒən/","a judgement reached after considering evidence"]
    ],
  };
  const COLLOCATION_BANK: Record<string, string[]> = {
    work: ["meet a deadline", "work closely with", "negotiate a contract", "improve efficiency", "reliable colleague", "set a priority", "constructive feedback", "attend a meeting", "business strategy", "achieve an outcome", "manage a budget", "take responsibility"],
    technology: ["design an algorithm", "electronic device", "protect privacy", "install an update", "use a feature", "network security", "secure access", "analyse data", "digital platform", "gain access", "user interface", "process automation"],
    education: ["follow a curriculum", "complete an assignment", "formal assessment", "conduct research", "attend a lecture", "provide evidence", "academic achievement", "develop a skill", "receive feedback", "make progress", "win a scholarship", "professional qualification"],
    society: ["local community", "reduce inequality", "public policy", "private citizen", "migration patterns", "affordable housing", "public services", "political debate", "social welfare", "equal access", "equal opportunity", "social impact"],
    environment: ["reduce emissions", "renewable energy", "nature conservation", "global climate", "natural resources", "household waste", "sustainable development", "natural habitat", "severe drought", "protect biodiversity", "environmental impact", "carbon footprint"],
    health: ["mental health", "medical treatment", "healthy lifestyle", "sleep quality", "balanced diet", "physical activity", "prevent disease", "clinical evidence", "healthcare system", "medical advice", "public health", "long-term recovery"],
    media: ["news coverage", "reliable source", "publish a report", "verify information", "social media", "media literacy", "public reaction", "headline wording", "online platform", "broadcast live", "journalistic standards", "misleading claim"],
    culture: ["cultural heritage", "local tradition", "artistic expression", "musical performance", "literary work", "cultural identity", "preserve a tradition", "historical site", "creative industry", "cultural exchange", "public exhibition", "shared values"],
    science: ["scientific evidence", "research finding", "conduct an experiment", "control a variable", "test a theory", "representative sample", "measure accurately", "analyse a result", "observe closely", "support a conclusion", "peer-reviewed study", "research method"],
    business: ["business strategy", "financial performance", "market demand", "customer satisfaction", "increase sales", "make an investment", "manage risk", "reduce costs", "launch a product", "competitive advantage", "cash flow", "annual report"],
  };
  const EXAMPLE_TEMPLATES: Record<string, string[]> = {
    work: ["The team needs to {word} before the end of the week.", "We discussed how to {word} more effectively during the meeting."],
    technology: ["The development team decided to {word} before the next release.", "Users need to understand how {word} affects the system."],
    education: ["Students need to {word} if they want to make steady progress.", "The teacher explained how {word} can improve learning outcomes."],
    society: ["The report examines how {word} affects people in the community.", "Policy makers are considering ways to {word} more effectively."],
    environment: ["Scientists are studying how to {word} without damaging the ecosystem.", "The new policy aims to {word} over the next decade."],
    health: ["Doctors often advise patients to {word} when appropriate.", "Research shows why it is important to {word} consistently."],
    media: ["Journalists should {word} before publishing the story.", "The report explains how {word} can affect public understanding."],
    culture: ["The project aims to {word} while respecting local traditions.", "Visitors can learn how communities {word} across generations."],
    science: ["Researchers need to {word} before drawing a conclusion.", "The study explains why scientists {word} under controlled conditions."],
    business: ["The company plans to {word} before the next quarter.", "Managers must consider how to {word} without increasing unnecessary costs."],
  };
  const collocations = COLLOCATION_BANK[domain] ?? COLLOCATION_BANK.work;
  const templates = EXAMPLE_TEMPLATES[domain] ?? EXAMPLE_TEMPLATES.work;
  const words = (domainWords[domain] ?? domainWords.work).map(([word, uz, pos, ipa, definition], i) => {
    const template = templates[i % templates.length]!;
    const example = template.replace("{word}", word);
    return W(level, `${id}-w${i + 1}`, word, uz, pos as any, ipa, definition, example, `${uz} — mavzuga oid kontekstda qo‘llanadi.`, domain, "BookOpen", {
      collocations: [collocations[i] ?? collocations[0]!, collocations[(i + 1) % collocations.length]!], synonyms: [], antonyms: [], family: []
    });
  });
  const phrases = [
    ph(`${id}-p1`, `Let’s look at this from another angle.`, `Buni boshqa tomondan ko‘rib chiqaylik.`, "/lets/", ex, exUz, `Use this phrase to introduce a new point.`),
    ph(`${id}-p2`, `The main point is that…`, `Asosiy nuqta shundaki…`, "/ðə meɪn pɔɪnt/", ex, exUz, `Use it to structure an explanation.`),
    ph(`${id}-p3`, `To some extent, …`, `Ma’lum darajada, …`, "/tə sʌm ɪkˈstent/", ex, exUz, `Use it to qualify a claim.`),
  ];
  const extras: Exercise[] = [
    tr(`${id}-x1`, exUz, ex, "Translate while preserving the grammar and register.", { explanationUz: "Mazmun va grammatikani saqlang." }),
    gap(`${id}-x2`, `Complete: ${ex.replace(/\b\w+\b/, "___")}`, ex.split(" ")[0] ?? "the", "Use the lesson grammar.", "Dars grammatikasidan foydalaning."),
    order(`${id}-x3`, ex.replace(/[.,!?]/g, "").split(" "), ex.replace(/[.,!?]/g, ""), form, form),
    errx(`${id}-x4`, "The structure is not precise.", ex, "Use the target structure for this context.", "Shu kontekst uchun kerakli strukturani ishlating."),
    mcq(`${id}-x5`, `Which structure matches ${topic}?`, [ex, "A random structure", "An unrelated tense", "An incorrect form"], ex, "Choose the structure that matches the lesson goal.", "Dars maqsadiga mos variantni tanlang."),
    { id: `${id}-x6`, type: "question-form", skill: "grammar", prompt: `Turn this statement into a question: ${ex}`, promptUz: "Berilgan gapni savolga aylantiring.", answer: `Can you explain ${topic}?`, explanation: "Form a natural question that asks for information about the lesson topic.", explanationUz: "Dars mavzusi haqida tabiiy axborot savolini tuzing.", },
    { id: `${id}-x7`, type: "transform", skill: "grammar", prompt: `Rewrite the sentence using the target structure: ${ex}`, answer: ex, explanation: "Keep the original meaning while applying the target structure.", explanationUz: "Asl ma’noni saqlagan holda maqsadli grammatik strukturadan foydalaning." },
    { id: `${id}-x8`, type: "find-mistake", skill: "grammar", prompt: `Correct the grammar in this sentence: ${ex.replace(/(is|are|was|were|has|have|had|will|would|can|could|should)/i, "WRONG")}`, text: `WRONG ${ex.replace(/^\S+\s*/, "")}`, answer: ex, explanation: "Restore the correct auxiliary or grammatical form required by the lesson.", explanationUz: "Darsda o‘rganilgan yordamchi fe’l yoki grammatik shaklni to‘g‘rilang." },
    { id: `${id}-x9`, type: "rewrite", skill: "writing", prompt: "Rewrite the idea in a more precise way.", answer: ex, explanation: "Improve precision and register.", explanationUz: "Aniqlik va uslubni yaxshilang." },
    { id: `${id}-x10`, type: "dictation", skill: "listening", prompt: "Listen and type the key sentence.", audioText: ex, answer: ex, explanation: "Listen for grammar and word boundaries.", explanationUz: "Grammatika va so‘z chegaralariga e’tibor bering." },
    { id: `${id}-x11`, type: "listen-gap", skill: "listening", prompt: "Listen and complete the sentence.", audioText: ex, answer: ex.split(" ").slice(0, 2).join(" "), explanation: "Listen for the opening phrase.", explanationUz: "Gapning boshlanishini tinglang." },
  ];
  return pack({
    id, day, level, topic, topicUz, cefrCanDo: cefr, cefrCanDoUz: cefrUz,
    grammar: grammar(gTitle, cefr, form, ex, exUz, `Incorrect ${gTitle} form.`, ex, domain), vocabulary: words, phrases,
    listenTitle: `${topic} listening`, listenTitleUz: `${topicUz} — tinglash`, lines: [
      { en: ex, uz: exUz }, { en: `The discussion focuses on ${words[0]!.word}.`, uz: `Suhbat ${words[0]!.uz} haqida.` }, { en: `A second point is related to ${words[1]!.word}.`, uz: `Ikkinchi nuqta ${words[1]!.uz} bilan bog‘liq.` },
      { en: `The speaker gives an example and explains the consequence.`, uz: `So‘zlovchi misol keltirib, natijani tushuntiradi.` },
      { en: `The listener should separate the main claim from supporting evidence.`, uz: `Tinglovchi asosiy fikrni dalildan ajratishi kerak.` },
      { en: `Finally, the speaker gives a careful conclusion rather than an absolute answer.`, uz: `Oxirida so‘zlovchi mutlaq javob emas, ehtiyotkor xulosa beradi.` },
    ],
    readTitle: `${topic} in context`, readTitleUz: `${topicUz} kontekstda`, readText: `${ex} This text develops the topic through a practical example and a second perspective. The writer explains why the issue matters, identifies a possible benefit and then considers a limitation. Notice how the argument moves from a general claim to a concrete example, then to a qualification and a conclusion. Learners should also notice the target grammar, useful collocations, and reference words that connect the sentences. In real communication, precise language helps a speaker distinguish facts from opinions, evidence from assumptions, and possibility from certainty. A strong learner does not simply memorise one sentence. Instead, the learner notices the pattern, tests it in a new context, compares alternatives, and chooses the form that best matches the intended meaning and register. When reading, underline the main claim, circle supporting details, and write one sentence that summarises the author’s position. When speaking or writing, reuse the structure with a new example from your own experience.`,
    speaking: { prompt: `Discuss ${topic}. Give two points, one example, and one conclusion.`, promptUz: `${topicUz} haqida ikki fikr, bir misol va xulosa ayting.`, scaffolding: [`The main point is…`, `For example…`, `However…`, `Overall…`] },
    writing: { prompt: `Write a structured paragraph about ${topic}. Use the target grammar and at least five lesson words.`, promptUz: `${topicUz} haqida tartibli paragraf yozing.`, minWords: level === "c1" ? 180 : level === "b2" || level === "b2-plus" ? 150 : 120, scaffolding: [`Introduce the issue.`, `Give evidence or an example.`, `Add a qualification.`, `Conclude clearly.`] },
    extras, isReview: false,
  });
}

export const advancedLessons: Lesson[] = [
  makeLesson("b1-plus-53", 53, "b1-plus", "Comparing past and present", "O‘tmish va hozirni taqqoslash", "used to / would", "used to + base verb; would + base verb for repeated past actions", "I used to live here. / We would walk here every Sunday.", "O‘tmish va hozirni taqqoslash haqida aniq va bog‘langan gap tuza olaman.", "work", "I can use used to / would accurately to discuss comparing past and present in a clear, connected way.", "O‘tmish va hozirni taqqoslash mavzusida used to / woulddan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-54", 54, "b1-plus", "Narrative tenses", "Hikoya zamonlari", "Past Perfect + Past Continuous", "Past Perfect for an earlier past event; Past Continuous for background action", "I had left before he arrived. / I was driving when it started.", "Men u yetib kelishidan oldin ketib bo‘lgan edim. / Boshlanganda men mashina haydab ketayotgan edim.", "technology", "I can use past perfect + past continuous accurately to discuss narrative tenses in a clear, connected way.", "Hikoya zamonlari mavzusida Past Perfect + Past Continuousdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-55", 55, "b1-plus", "Future forms in context", "Kontekstdagi kelasi zamon shakllari", "will / going to / present continuous", "Choose the future form from intention, evidence, arrangement, or prediction", "I am meeting her tomorrow. / It is going to rain.", "Men ertaga u bilan uchrashyapman. / Yomg‘ir yog‘adiganga o‘xshaydi.", "education", "I can use will / going to / present continuous accurately to discuss future forms in context in a clear, connected way.", "Kontekstdagi kelasi zamon shakllari mavzusida will / going to / present continuousdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-56", 56, "b1-plus", "Future Perfect and Continuous", "Future Perfect va Continuous", "will have done / will have been doing", "Use future perfect for completion before a future time and future perfect continuous for duration", "By June, I will have finished. / I will have been studying for a year.", "Iyun oyiga kelib, men ishni tugatgan bo‘laman. / O‘sha paytga kelib, bir yil davomida o‘qiyotgan bo‘laman.", "society", "I can use will have done / will have been doing accurately to discuss future perfect and continuous in a clear, connected way.", "Future Perfect va Continuous mavzusida will have done / will have been doingdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-57", 57, "b1-plus", "Modals of deduction", "Taxmin modal fe’llari", "must / might / can’t", "Use must for strong positive deduction, might for possibility, and can’t for strong negative deduction", "She must be busy. / He might be asleep. / It can’t be true.", "U band bo‘lsa kerak. / U uxlayotgan bo‘lishi mumkin. / Bu rost bo‘lishi mumkin emas.", "environment", "I can use must / might / can’t accurately to discuss modals of deduction in a clear, connected way.", "Taxmin modal fe’llari mavzusida must / might / can’tdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-58", 58, "b1-plus", "Modals of obligation and advice", "Majburiyat va maslahat modallari", "should / ought to / have to / need to", "Distinguish advice, external obligation, and necessity", "You should rest. / We have to wear ID badges.", "Dam olishing kerak. / Biz identifikatsiya nishonlarini taqishimiz shart.", "health", "I can use should / ought to / have to / need to accurately to discuss modals of obligation and advice in a clear, connected way.", "Majburiyat va maslahat modallari mavzusida should / ought to / have to / need todan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-59", 59, "b1-plus", "Advanced conditionals", "Murakkab shart gaplar", "mixed conditionals", "Combine past and present results when the time references differ", "If I had studied medicine, I would be a doctor now.", "Agar men tibbiyotni o‘qiganimda, hozir shifokor bo‘lardim.", "media", "I can use mixed conditionals accurately to discuss advanced conditionals in a clear, connected way.", "Murakkab shart gaplar mavzusida mixed conditionalsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-60", 60, "b1-plus", "Reported questions and commands", "Bilvosita savol va buyruqlar", "reported questions / commands", "Backshift and change pronouns, time words, and word order in reported speech", "She asked where I lived. / He told me to wait.", "U qayerda yashashimni so‘radi. / U menga kutib turishni aytdi.", "business", "I can use reported questions / commands accurately to discuss reported questions and commands in a clear, connected way.", "Bilvosita savol va buyruqlar mavzusida reported questions / commandsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-61", 61, "b1-plus", "Relative clauses", "Aniqlovchi qo‘shimcha gaplar", "defining / non-defining relative clauses", "Use relative clauses to identify or add information about people and things", "The book that I bought is useful. / My brother, who lives abroad, called.", "Men sotib olgan kitob foydali. / Chet elda yashaydigan akam qo‘ng‘iroq qildi.", "culture", "I can use defining / non-defining relative clauses accurately to discuss relative clauses in a clear, connected way.", "Aniqlovchi qo‘shimcha gaplar mavzusida defining / non-defining relative clausesdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b1-plus-62", 62, "b1-plus", "Linking ideas clearly", "Fikrlarni aniq bog‘lash", "although / despite / whereas / however", "Use contrast linkers accurately to connect clauses and ideas", "Although it was late, we continued. / Despite the rain, we walked.", "Kech bo‘lganiga qaramay, davom etdik. / Yomg‘irga qaramay, piyoda yurdik.", "science", "I can use although / despite / whereas / however accurately to discuss linking ideas clearly in a clear, connected way.", "Fikrlarni aniq bog‘lash mavzusida although / despite / whereas / howeverdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-63", 63, "b2", "Inversion for emphasis", "Ta’kid uchun inversiya", "negative adverbial inversion", "After negative or restrictive adverbials, auxiliary and subject can invert for emphasis", "Never have I seen such a view.", "Men hech qachon bunday manzarani ko‘rmaganman.", "work", "I can use negative adverbial inversion accurately to discuss inversion for emphasis in a clear, connected way.", "Ta’kid uchun inversiya mavzusida negative adverbial inversiondan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-64", 64, "b2", "Cleft sentences", "Cleft gaplar", "it-clefts / what-clefts", "Use cleft structures to focus attention on one part of a sentence", "It was Ali who solved the problem.", "Muammoni aynan Ali hal qildi.", "technology", "I can use it-clefts / what-clefts accurately to discuss cleft sentences in a clear, connected way.", "Cleft gaplar mavzusida it-clefts / what-cleftsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-65", 65, "b2", "Advanced passive structures", "Murakkab passive", "passive reporting and causative structures", "Use passive reporting verbs and have/get something done", "He is believed to be honest. / I had my phone repaired.", "U halol deb hisoblanadi. / Men telefonimni ta’mirlatdim.", "education", "I can use passive reporting and causative structures accurately to discuss advanced passive structures in a clear, connected way.", "Murakkab passive mavzusida passive reporting and causative structuresdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-66", 66, "b2", "Gerunds and infinitives", "Gerund va infinitiv", "verb patterns", "Some verbs take gerunds, infinitives, or both with meaning changes", "I stopped smoking. / I stopped to smoke.", "Men chekishni to‘xtatdim. / Men chekish uchun to‘xtadim.", "society", "I can use verb patterns accurately to discuss gerunds and infinitives in a clear, connected way.", "Gerund va infinitiv mavzusida verb patternsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-67", 67, "b2", "Participle clauses", "Participle clauses", "present / past participle clauses", "Reduce clauses when the subject relationship is clear", "Having finished the work, she left.", "Ishni tugatgach, u chiqib ketdi.", "environment", "I can use present / past participle clauses accurately to discuss participle clauses in a clear, connected way.", "Participle clauses mavzusida present / past participle clausesdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-68", 68, "b2", "Advanced modal perfects", "O‘tgan modal taxminlar", "must have / might have / should have / can’t have", "Use modal + have + past participle to evaluate past events", "She must have forgotten.", "Ishni tugatgach, u chiqib ketdi.", "health", "I can use must have / might have / should have / can’t have accurately to discuss advanced modal perfects in a clear, connected way.", "O‘tgan modal taxminlar mavzusida must have / might have / should have / can’t havedan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-69", 69, "b2", "Third conditional nuance", "Uchinchi shart gap nozikliklari", "would have / could have / might have", "Express unreal past alternatives with different degrees of possibility", "We could have won if we had defended better.", "U unutgan bo‘lsa kerak.", "media", "I can use would have / could have / might have accurately to discuss third conditional nuance in a clear, connected way.", "Uchinchi shart gap nozikliklari mavzusida would have / could have / might havedan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-70", 70, "b2", "Wish and regret", "Istak va afsus", "wish / if only / would rather", "Use wish and if only for unreal present, past regret, and desired change", "I wish I had listened.", "Agar yaxshiroq himoyalanganimizda, g‘alaba qozonishimiz mumkin edi.", "business", "I can use wish / if only / would rather accurately to discuss wish and regret in a clear, connected way.", "Istak va afsus mavzusida wish / if only / would ratherdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-71", 71, "b2", "Quantifiers and determiners", "Miqdor aniqlovchilari", "few / a few / little / a little / each / every", "Control countability and subtle quantity meanings", "Few people agreed. / A few people stayed.", "Qaniydi, men quloq solganimda edi.", "culture", "I can use few / a few / little / a little / each / every accurately to discuss quantifiers and determiners in a clear, connected way.", "Miqdor aniqlovchilari mavzusida few / a few / little / a little / each / everydan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-72", 72, "b2", "Articles at advanced level", "Yuqori darajadagi artikllar", "a / an / the / zero article", "Use articles with institutions, geography, abstract nouns, and generic reference", "The internet is useful. / Education matters.", "Kam odam rozi bo‘ldi. / Bir nechta odam qolib ketdi.", "science", "I can use a / an / the / zero article accurately to discuss articles at advanced level in a clear, connected way.", "Yuqori darajadagi artikllar mavzusida a / an / the / zero articledan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-73", 73, "b2", "Prepositions and dependent phrases", "Bog‘liq predloglar", "dependent prepositions", "Learn fixed combinations such as interested in, responsible for, depend on", "It depends on the context.", "Internet foydali. / Ta’lim muhim.", "work", "I can use dependent prepositions accurately to discuss prepositions and dependent phrases in a clear, connected way.", "Bog‘liq predloglar mavzusida dependent prepositionsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-74", 74, "b2", "Phrasal verbs in formal contexts", "Formal kontekstdagi phrasal verbs", "separable / inseparable phrasal verbs", "Use common phrasal verbs and distinguish formal alternatives", "We need to carry out the plan.", "Bu kontekstga bog‘liq.", "technology", "I can use separable / inseparable phrasal verbs accurately to discuss phrasal verbs in formal contexts in a clear, connected way.", "Formal kontekstdagi phrasal verbs mavzusida separable / inseparable phrasal verbsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-75", 75, "b2", "Collocations and word choice", "Collocation va so‘z tanlovi", "make/do/take/give collocations", "Choose natural word partnerships rather than translating word by word", "make a decision, take responsibility.", "Biz rejani amalga oshirishimiz kerak.", "education", "I can use make/do/take/give collocations accurately to discuss collocations and word choice in a clear, connected way.", "Collocation va so‘z tanlovi mavzusida make/do/take/give collocationsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-76", 76, "b2", "Concession and qualification", "Istisno va cheklash", "even though / nevertheless / to some extent", "Qualify claims and concede opposing points", "To some extent, this is true.", "qaror qabul qilmoq, mas’uliyatni o‘z zimmasiga olmoq.", "society", "I can use even though / nevertheless / to some extent accurately to discuss concession and qualification in a clear, connected way.", "Istisno va cheklash mavzusida even though / nevertheless / to some extentdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-77", 77, "b2", "Argument structure", "Argument tuzilishi", "claim / evidence / consequence language", "Organise an argument with precise signposting", "The evidence suggests that…", "Ma’lum darajada, bu to‘g‘ri.", "environment", "I can use claim / evidence / consequence language accurately to discuss argument structure in a clear, connected way.", "Argument tuzilishi mavzusida claim / evidence / consequence languagedan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-78", 78, "b2-plus", "Register and formality", "Uslub va rasmiylik", "formal / neutral / informal register", "Choose grammar and vocabulary appropriate to audience and purpose", "Could you please provide the documents?", "Dalillar shuni ko‘rsatadiki…", "health", "I can use formal / neutral / informal register accurately to discuss register and formality in a clear, connected way.", "Uslub va rasmiylik mavzusida formal / neutral / informal registerdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-79", 79, "b2-plus", "Hedging and cautious claims", "Ehtiyotkor fikr bildirish", "may / might / tends to / appears to", "Reduce overstatement in academic and professional claims", "The results appear to indicate…", "Hujjatlarni taqdim eta olasizmi, iltimos?", "media", "I can use may / might / tends to / appears to accurately to discuss hedging and cautious claims in a clear, connected way.", "Ehtiyotkor fikr bildirish mavzusida may / might / tends to / appears todan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-80", 80, "b2-plus", "Nominalisation", "Otlashtirish", "nominalisation in formal writing", "Turn processes into noun phrases for dense formal prose", "The committee reviewed the plan → The review of the plan…", "Natijalar … ekanini ko‘rsatishga o‘xshaydi.", "business", "I can use nominalisation in formal writing accurately to discuss nominalisation in a clear, connected way.", "Otlashtirish mavzusida nominalisation in formal writingdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-81", 81, "b2-plus", "Complex noun phrases", "Murakkab ot birikmalari", "pre/post modification", "Pack precise information into noun phrases", "a rapidly growing technology sector", "Qo‘mita rejani ko‘rib chiqdi → Rejaning ko‘rib chiqilishi…", "culture", "I can use pre/post modification accurately to discuss complex noun phrases in a clear, connected way.", "Murakkab ot birikmalari mavzusida pre/post modificationdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-82", 82, "b2-plus", "Discourse markers", "Diskurs markerlari", "moreover / nonetheless / consequently / namely", "Signal relationships between ideas precisely", "Consequently, costs increased.", "tez sur’atlarda rivojlanayotgan texnologiya sohasi", "science", "I can use moreover / nonetheless / consequently / namely accurately to discuss discourse markers in a clear, connected way.", "Diskurs markerlari mavzusida moreover / nonetheless / consequently / namelydan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-83", 83, "b2-plus", "Ellipsis and substitution", "Ellipsis va substitution", "so / neither / do so / one(s)", "Avoid repetition while keeping reference clear", "I think so. / She bought the red one.", "Natijada, xarajatlar oshdi.", "work", "I can use so / neither / do so / one(s) accurately to discuss ellipsis and substitution in a clear, connected way.", "Ellipsis va substitution mavzusida so / neither / do so / one(s)dan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-84", 84, "b2-plus", "Advanced comparison", "Murakkab taqqoslash", "the more…the more / by far / considerably", "Express degree and proportional relationships", "The more you practise, the more fluent you become.", "Men shunday deb o‘ylayman. / U qizilini sotib oldi.", "technology", "I can use the more…the more / by far / considerably accurately to discuss advanced comparison in a clear, connected way.", "Murakkab taqqoslash mavzusida the more…the more / by far / considerablydan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-85", 85, "b2-plus", "Emphasis and stance", "Ta’kid va munosabat", "do-emphasis / indeed / certainly / clearly", "Strengthen or frame statements without changing core meaning", "I do understand your concern.", "Qancha ko‘p mashq qilsangiz, shuncha ravon gapirasiz.", "education", "I can use do-emphasis / indeed / certainly / clearly accurately to discuss emphasis and stance in a clear, connected way.", "Ta’kid va munosabat mavzusida do-emphasis / indeed / certainly / clearlydan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-86", 86, "b2-plus", "Complex reported discourse", "Murakkab reported speech", "reporting verbs and stance", "Use varied reporting verbs and preserve speaker stance", "The report warns that…", "Sizning tashvishingizni chindan ham tushunaman.", "society", "I can use reporting verbs and stance accurately to discuss complex reported discourse in a clear, connected way.", "Murakkab reported speech mavzusida reporting verbs and stancedan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("b2-plus-87", 87, "b2-plus", "Text cohesion", "Matn bog‘liqligi", "reference / substitution / lexical cohesion", "Create cohesive paragraphs with clear references and lexical links", "This approach… such a result…", "Hisobot shuni ta’kidlaydiki…", "environment", "I can use reference / substitution / lexical cohesion accurately to discuss text cohesion in a clear, connected way.", "Matn bog‘liqligi mavzusida reference / substitution / lexical cohesiondan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-88", 88, "c1", "Advanced tense and aspect", "Yuqori darajadagi zamon va aspekt", "aspect choice and narrative viewpoint", "Select tense and aspect to control viewpoint, duration, completion, and relevance", "By then, she had been working there for years.", "O‘sha paytga kelib, u u yerda yillar davomida ishlab kelayotgan edi.", "health", "I can use aspect choice and narrative viewpoint accurately to discuss advanced tense and aspect in a clear, connected way.", "Yuqori darajadagi zamon va aspekt mavzusida aspect choice and narrative viewpointdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-89", 89, "c1", "Subjunctive and formal recommendations", "Subjunctive va rasmiy tavsiya", "mandative subjunctive", "Use formal base forms after demand, recommend, insist, and suggest", "It is essential that he be informed.", "Unga xabar berilishi juda muhim.", "media", "I can use mandative subjunctive accurately to discuss subjunctive and formal recommendations in a clear, connected way.", "Subjunctive va rasmiy tavsiya mavzusida mandative subjunctivedan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-90", 90, "c1", "Advanced inversion", "Murakkab inversiya", "not only… but also / under no circumstances / little did", "Use marked word order for emphasis and formal style", "Under no circumstances should this be ignored.", "Hech qanday holatda bunga e’tibor berilmasligi kerak.", "business", "I can use not only… but also / under no circumstances / little did accurately to discuss advanced inversion in a clear, connected way.", "Murakkab inversiya mavzusida not only… but also / under no circumstances / little diddan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-91", 91, "c1", "Conditionals in formal argument", "Rasmiy argumentdagi conditionals", "provided that / unless / supposing / were to", "Express conditions precisely in policy, academic, and professional contexts", "Provided that costs remain stable, the plan is viable.", "Xarajatlar barqaror bo‘lib qolsa, reja amalga oshirishga yaroqli.", "culture", "I can use provided that / unless / supposing / were to accurately to discuss conditionals in formal argument in a clear, connected way.", "Rasmiy argumentdagi conditionals mavzusida provided that / unless / supposing / were todan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-92", 92, "c1", "Advanced relative structures", "Murakkab relative structures", "whose / whereby / preposition + which", "Use formal relative structures to create precise links", "the process whereby data is collected", "Ma’lumotlar yig‘iladigan jarayon.", "science", "I can use whose / whereby / preposition + which accurately to discuss advanced relative structures in a clear, connected way.", "Murakkab relative structures mavzusida whose / whereby / preposition + whichdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-93", 93, "c1", "Concession and paradox", "Qarama-qarshilik va paradoks", "however much / no matter how / while", "Express strong concession and complex contrast", "No matter how difficult it is, we continue.", "Qanchalik qiyin bo‘lmasin, biz davom etamiz.", "work", "I can use however much / no matter how / while accurately to discuss concession and paradox in a clear, connected way.", "Qarama-qarshilik va paradoks mavzusida however much / no matter how / whiledan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-94", 94, "c1", "Academic reporting", "Akademik manba bayoni", "it is widely believed / evidence suggests", "Report evidence while separating fact, interpretation, and uncertainty", "Evidence suggests that the effect is limited.", "Dalillar ta’sir cheklanganini ko‘rsatmoqda.", "technology", "I can use it is widely believed / evidence suggests accurately to discuss academic reporting in a clear, connected way.", "Akademik manba bayoni mavzusida it is widely believed / evidence suggestsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-95", 95, "c1", "Precision with modality", "Modal ma’no nozikliklari", "probability, necessity, criticism", "Use modal choices to distinguish certainty, obligation, criticism, and possibility", "You needn’t have done that.", "Buni qilishingiz shart emas edi.", "education", "I can use probability, necessity, criticism accurately to discuss precision with modality in a clear, connected way.", "Modal ma’no nozikliklari mavzusida probability, necessity, criticismdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-96", 96, "c1", "Idiomatic and metaphorical language", "Idiom va metafora", "fixed idioms and metaphorical collocations", "Understand and use common idiomatic language without literal translation", "raise the bar; a grey area", "Darajani ko‘tarish; noaniq/aniq chegarasi bo‘lmagan masala.", "society", "I can use fixed idioms and metaphorical collocations accurately to discuss idiomatic and metaphorical language in a clear, connected way.", "Idiom va metafora mavzusida fixed idioms and metaphorical collocationsdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-97", 97, "c1", "Advanced discourse and coherence", "C1 discourse va coherence", "paragraph progression and synthesis", "Build coherent spoken and written arguments across several ideas", "Taken together, these findings suggest…", "Birgalikda ko‘rib chiqilganda, bu topilmalar shuni ko‘rsatadiki…", "environment", "I can use paragraph progression and synthesis accurately to discuss advanced discourse and coherence in a clear, connected way.", "C1 discourse va coherence mavzusida paragraph progression and synthesisdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-98", 98, "c1", "Paraphrasing and synthesis", "Parafraz va sintez", "nominalisation, synonymy, restructuring", "Rephrase accurately without changing meaning or register", "The study found… → The findings indicate…", "Tadqiqot aniqladi… → Topilmalar shuni ko‘rsatadiki…", "health", "I can use nominalisation, synonymy, restructuring accurately to discuss paraphrasing and synthesis in a clear, connected way.", "Parafraz va sintez mavzusida nominalisation, synonymy, restructuringdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-99", 99, "c1", "Professional communication", "Professional muloqot", "polite requests, negotiation, clarification", "Handle nuanced workplace communication naturally", "Would you be in a position to…?", "Buni amalga oshirish imkoniyatingiz bormi?", "media", "I can use polite requests, negotiation, clarification accurately to discuss professional communication in a clear, connected way.", "Professional muloqot mavzusida polite requests, negotiation, clarificationdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-100", 100, "c1", "Academic writing: claims and evidence", "Akademik yozuv: dalil", "claim, evidence, limitation, implication", "Build balanced academic paragraphs with evidence and qualification", "The evidence supports this claim, although…", "Dalillar bu da’voni qo‘llab-quvvatlaydi, garchi…", "business", "I can use claim, evidence, limitation, implication accurately to discuss academic writing: claims and evidence in a clear, connected way.", "Akademik yozuv: dalil mavzusida claim, evidence, limitation, implicationdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-101", 101, "c1", "Cohesion and information flow", "Cohesion va information flow", "theme/rheme and given/new information", "Arrange information so readers can follow complex arguments", "This issue is particularly relevant because…", "Bu masala ayniqsa muhim, chunki…", "culture", "I can use theme/rheme and given/new information accurately to discuss cohesion and information flow in a clear, connected way.", "Cohesion va information flow mavzusida theme/rheme and given/new informationdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-102", 102, "c1", "C1 mastery review", "C1 yakuniy takrorlash", "integrated grammar and lexis", "Integrate advanced grammar, vocabulary, listening, reading, speaking, and writing", "Use the most precise structure for the communicative goal.", "Eng aniq strukturani kommunikativ maqsadga mos tanlang.", "science", "I can use integrated grammar and lexis accurately to discuss c1 mastery review in a clear, connected way.", "C1 yakuniy takrorlash mavzusida integrated grammar and lexisdan aniq va bog‘langan nutqda foydalana olaman."),
  makeLesson("c1-103", 103, "c1", "C1 grammar diagnostic", "C1 grammatik diagnostika", "integrated tense, aspect, modality and inversion", "Choose the most precise structure for the context", "Under no circumstances should the evidence be ignored, because it may have changed the outcome.", "Hech qanday holatda dalil e’tiborsiz qoldirilmasligi kerak, chunki u natijani o‘zgartirgan bo‘lishi mumkin.", "science", "I can select precise advanced grammar for complex contexts.", "Murakkab kontekstlarda aniq yuqori darajadagi grammatikani tanlay olaman."),
  makeLesson("c1-104", 104, "c1", "C1 vocabulary diagnostic", "C1 lug‘at diagnostikasi", "collocation, idiom and register control", "Select natural and context-appropriate lexical choices", "The proposal raises a number of issues that warrant further consideration.", "Taklif qo‘shimcha ko‘rib chiqishni talab qiladigan bir qator masalalarni ko‘taradi.", "business", "I can choose precise collocations, idioms, and register-appropriate vocabulary.", "Aniq collocation, idiom va uslubga mos lug‘atni tanlay olaman."),
  makeLesson("c1-105", 105, "c1", "C1 integrated skills assessment", "C1 integratsiyalashgan ko‘nikmalar baholashi", "synthesis, paraphrase and discourse", "Synthesize information while preserving meaning and register", "Taken together, the findings provide a compelling but qualified basis for further research.", "Birgalikda ko‘rib chiqilganda, topilmalar keyingi tadqiqot uchun kuchli, ammo ehtiyotkor asos beradi.", "education", "I can synthesise complex information across reading, listening, speaking, and writing.", "Murakkab axborotni reading, listening, speaking va writing orqali sintez qila olaman."),
  makeLesson("c1-106", 106, "c1", "C1 mastery assessment", "C1 yakuniy mastery baholashi", "integrated C1 grammar and discourse", "Select the most precise structure, register and wording for the communicative goal", "Taken together, the evidence suggests that the policy is effective, provided that implementation remains consistent.", "Birgalikda ko‘rib chiqilganda, dalillar siyosat samarali ekanini ko‘rsatadi, agar amalga oshirish izchil qolsa.", "science", "I can communicate precisely and flexibly across academic and professional contexts.", "Akademik va professional muhitda aniq va moslashuvchan muloqot qila olaman."),
];
