import type { Lesson, Word } from "@/lib/types";
import { errx, gap, listen, mcq, order, reading, tr } from "@/lib/content/helpers";

const L = "pre-a1" as const;
function w(
  id: string, word: string, uz: string, pos: Word["pos"], ipa: string,
  definition: string, example: string, exampleUz: string, category: string, icon: string, extra: Partial<Word> = {},
): Word {
  return {
    id, word, uz, pos, ipa, definition, example, exampleUz,
    collocations: extra.collocations ?? [], synonyms: extra.synonyms ?? [], antonyms: extra.antonyms ?? [],
    family: extra.family ?? [], level: L, category, icon,
  };
}

export const lessons: Lesson[] = [
  {
    id: "pre-a1-06",
    day: 6,
    level: L,
    topic: "To be: negatives and questions",
    topicUz: "To be: inkor va savol",
    cefrCanDo: "I can make negative and question forms with am/is/are.",
    cefrCanDoUz: "Am/is/are bilan inkor va savol tuzaman.",
    grammar: {
      title: "Be: not / questions",
      titleUz: "Be: not va savollar",
      meaning: "Add not for negative. Move am/is/are before the person for a question.",
      meaningUz: "Inkor uchun not. Savol uchun am/is/are oldinga chiqadi.",
      form: "I am not. She isn't. They aren't. Am I…? Is he…? Are you…?",
      formUz: "I am not. She isn't. Are you…?",
      why: "English shows yes/no questions with word order, not only intonation.",
      whyUz: "Savol so‘z tartibi bilan yasaladi, faqat ohang bilan emas.",
      examples: [
        { en: "I am not a teacher.", uz: "Men o‘qituvchi emasman." },
        { en: "Is she ready?", uz: "U tayyormi?" },
        { en: "Are they at home?", uz: "Ular uydami?" },
      ],
      negative: {
        form: "be + not (n't)",
        examples: [
          { en: "He is not here. / He isn't here.", uz: "U shu yerda emas." },
          { en: "We are not late. / We aren't late.", uz: "Biz kechikganimiz yo‘q." },
        ],
      },
      question: {
        form: "Be + subject + …? Short answers: Yes, I am. No, I'm not.",
        examples: [
          { en: "Are you a student? Yes, I am.", uz: "O‘quvchimisiz? Ha." },
          { en: "Is it a pen? No, it isn't.", uz: "Bu ruchkami? Yo‘q." },
        ],
      },
      mistakes: [
        { wrong: "You not are ready.", right: "You are not ready.", why: "not comes after am/is/are.", whyUz: "not am/is/are dan keyin." },
        { wrong: "Is you a teacher?", right: "Are you a teacher?", why: "you takes are, even in questions.", whyUz: "you bilan are." },
      ],
      contrast: {
        vs: "statement vs question",
        a: "She is happy.",
        b: "Is she happy?",
        note: "Only the position of is changes.",
        noteUz: "Faqat is o‘rni o‘zgaradi.",
      },
    },
    vocabulary: [
      w("w-not", "not", "emas", "adverb", "/nɒt/", "makes a sentence negative", "I am not late.", "Men kech emasman.", "grammar", "Ban"),
      w("w-yes", "yes", "ha", "interjection", "/jes/", "agree", "Yes, I am.", "Ha.", "greetings", "Check"),
      w("w-no", "no", "yo‘q", "interjection", "/nəʊ/", "disagree", "No, I'm not.", "Yo‘q.", "greetings", "X"),
      w("w-late", "late", "kech", "adjective", "/leɪt/", "after the right time", "I am not late.", "Men kech emasman.", "time", "Clock", { antonyms: ["early"] }),
      w("w-home", "home", "uy", "noun", "/həʊm/", "the place you live", "They are at home.", "Ular uyda.", "place", "House"),
      w("w-at", "at", "da (nuqta)", "preposition", "/æt/", "a point in place or time", "at home, at school", "uyda, maktabda", "place", "MapPin"),
      w("w-question", "question", "savol", "noun", "/ˈkwestʃən/", "something you ask", "This is a question.", "Bu savol.", "school", "CircleHelp"),
      w("w-answer", "answer", "javob", "noun", "/ˈɑːnsə/", "what you say after a question", "The answer is yes.", "Javob — ha.", "school", "MessageSquare", { family: [{ form: "answer", pos: "verb" }] }),
    ],
    phrases: [
      { id: "p-yes-i-am", phrase: "Yes, I am.", uz: "Ha.", ipa: "/jes aɪ æm/", example: "Are you ready? Yes, I am.", exampleUz: "Tayyormisiz? Ha.", speakingTask: "Give a short yes answer." },
      { id: "p-no-im-not", phrase: "No, I'm not.", uz: "Yo‘q.", ipa: "/nəʊ aɪm nɒt/", example: "Are you a teacher? No, I'm not.", exampleUz: "O‘qituvchimisiz? Yo‘q.", speakingTask: "Give a short no answer." },
      { id: "p-are-you", phrase: "Are you ready?", uz: "Tayyormisiz?", ipa: "/ɑː juː ˈredi/", example: "Are you ready for class?", exampleUz: "Darsga tayyormisiz?", speakingTask: "Ask a yes/no question with Are you." },
      { id: "p-is-she", phrase: "Is she at home?", uz: "U uydami?", ipa: "/ɪz ʃiː ət həʊm/", example: "Is she at home now?", exampleUz: "U hozir uydami?", speakingTask: "Ask about a friend with Is she/he." },
    ],
    listening: listen("A short check", "Qisqa tekshiruv", [
      { en: "Are you Omar?", uz: "Siz Omar misiz?" },
      { en: "Yes, I am.", uz: "Ha." },
      { en: "Are you a teacher?", uz: "O‘qituvchimisiz?" },
      { en: "No, I'm not. I am a student.", uz: "Yo‘q. Men o‘quvchiman." },
      { en: "Is Ana here?", uz: "Ana shu yerdami?" },
      { en: "No, she isn't. She is at home.", uz: "Yo‘q. U uyda." },
    ], [
      mcq("pre06-lq1", "Is Omar a teacher?", ["Yes", "No", "We don't know", "He is Ana"], "No", "He says No, I'm not. I am a student.", "U student.", { skill: "listening" }),
      gap("pre06-lq2", "She is at ___.", "home", "She is at home.", "Uyda.", { skill: "listening" }),
    ]),
    reading: reading("Questions in class", "Sinfdagi savollar",
      "Are you ready? Yes, I am. Is it a book? Yes, it is. Are they late? No, they aren't. I am not at home. I am at school. Is she a teacher? Yes, she is.",
      [
        mcq("pre06-rq1", "Are they late?", ["Yes", "No", "Maybe", "She is"], "No", "No, they aren't.", "Yo‘q.", { skill: "reading" }),
        mcq("pre06-rq2", "Where am I?", ["home", "school", "late", "book"], "school", "I am at school.", "Maktabda.", { skill: "reading" }),
      ],
      "Write two questions and two short answers from the text.",
    ),
    speaking: { prompt: "Ask and answer 4 yes/no questions with be.", promptUz: "Be bilan 4 ta ha/yo‘q savol.", scaffolding: ["Are you…?", "Yes, I am.", "Is he…?", "No, he isn't."] },
    writing: { prompt: "Write 4 negatives and 4 questions with am/is/are.", promptUz: "4 inkor va 4 savol yozing.", minWords: 32, scaffolding: ["I am not…", "Are you…?"] },
    exercises: [
      mcq("pre06-e1", "___ you a student?", ["Is", "Am", "Are", "Be"], "Are", "You → Are.", "You — Are."),
      gap("pre06-e2", "I am ___ a teacher.", "not", "I am not.", "I am not."),
      order("pre06-e3", ["she", "Is", "ready"], "Is she ready", "Is + she + adjective.", "Is she…"),
      errx("pre06-e4", "Is you late?", "Are you late", "you takes are.", "you — are."),
      tr("pre06-e5", "Yo‘q, men o‘qituvchi emasman.", "No, I am not a teacher", "No, I'm not a teacher.", { answer: ["No, I am not a teacher", "No, I'm not a teacher"] }),
      mcq("pre06-e6", "He ___ here.", ["am not", "isn't", "aren't", "not is"], "isn't", "He isn't = he is not.", "He isn't."),
      gap("pre06-e7", "___ I late?", "Am", "I → Am I…?", "I — Am I."),
      order("pre06-e8", ["not", "They", "are", "ready"], "They are not ready", "They are not + adjective."),
      tr("pre06-e9", "U uydami?", "Is she at home", "Is she/he at home?", { answer: ["Is she at home", "Is he at home"] }),
      mcq("pre06-e10", "Are they students? — Yes, they ___.", ["am", "is", "are", "be"], "are", "Short answer repeats are.", "Qisqa javob: are."),
    ],
    test: [
      mcq("pre06-t1", "Make a question: She is happy.", ["She is happy?", "Is she happy?", "Does she happy?", "Happy she is?"], "Is she happy?", "Move is before she.", "is oldinga."),
      gap("pre06-t2", "We ___ not at home.", "are", "We are not.", "We are not."),
      errx("pre06-t3", "I isn't ready.", "I am not ready", "I am not / I'm not.", "I am not."),
      tr("pre06-t4", "Siz tayyormisiz?", "Are you ready", "Are you ready?"),
      order("pre06-t5", ["am", "Yes", "I"], "Yes I am", "Yes, I am."),
      mcq("pre06-t6", "It isn't a pen. = It ___ a pen.", ["is no", "are not", "is not", "am not"], "is not", "isn't = is not.", "isn't = is not."),
    ],
  },
  {
    id: "pre-a1-07",
    day: 7,
    level: L,
    topic: "Colours and adjectives",
    topicUz: "Ranglar va sifatlar",
    cefrCanDo: "I can name basic colours and describe things with simple adjectives.",
    cefrCanDoUz: "Asosiy ranglarni aytaman va narsalarni oddiy sifat bilan ta’riflayman.",
    grammar: {
      title: "Adjective + noun",
      titleUz: "Sifat + ot",
      meaning: "Adjectives describe nouns. In English the adjective comes before the noun.",
      meaningUz: "Sifat otni ta’riflaydi va otdan OLDIN keladi.",
      form: "a + adjective + noun → a red book. Be + adjective → The book is red.",
      formUz: "a red book / The book is red.",
      why: "Word order is adjective then noun, unlike some Uzbek patterns with -li after the noun idea.",
      whyUz: "Inglizchada sifat + ot: a red book.",
      examples: [
        { en: "a blue pen", uz: "ko‘k ruchka" },
        { en: "The room is small.", uz: "Xona kichik." },
        { en: "It is a big class.", uz: "Bu katta sinf." },
      ],
      negative: {
        form: "The book is not red. / It isn't small.",
        examples: [{ en: "It is not black. It is white.", uz: "U qora emas. Oq." }],
      },
      question: {
        form: "What colour is it? Is it big?",
        examples: [{ en: "What colour is your bag?", uz: "Sumkangiz nima rang?" }],
      },
      mistakes: [
        { wrong: "a book red", right: "a red book", why: "Adjective before noun.", whyUz: "Sifat otdan oldin." },
        { wrong: "It is a red.", right: "It is red. / It is a red book.", why: "After be, adjective has no a unless a noun follows.", whyUz: "Be dan keyin a kerak emas, agar ot bo‘lmasa." },
      ],
    },
    vocabulary: [
      w("w-red", "red", "qizil", "adjective", "/red/", "the colour of an apple", "a red apple", "qizil olma", "colours", "Palette"),
      w("w-blue", "blue", "ko‘k", "adjective", "/bluː/", "the colour of a clear sky", "a blue pen", "ko‘k ruchka", "colours", "Palette"),
      w("w-green", "green", "yashil", "adjective", "/ɡriːn/", "the colour of grass", "green tea", "yashil choy", "colours", "Palette"),
      w("w-black", "black", "qora", "adjective", "/blæk/", "the darkest colour", "a black bag", "qora sumka", "colours", "Palette", { antonyms: ["white"] }),
      w("w-white", "white", "oq", "adjective", "/waɪt/", "the colour of milk", "a white board", "oq doska", "colours", "Palette"),
      w("w-big", "big", "katta", "adjective", "/bɪɡ/", "large", "a big room", "katta xona", "size", "Maximize2", { synonyms: ["large"], antonyms: ["small"] }),
      w("w-small", "small", "kichik", "adjective", "/smɔːl/", "not big", "a small book", "kichik kitob", "size", "Minimize2", { antonyms: ["big"] }),
      w("w-colour", "colour", "rang", "noun", "/ˈkʌlə/", "red, blue, green…", "What colour is it?", "U nima rang?", "colours", "Palette", { family: [{ form: "colourful", pos: "adjective" }] }),
    ],
    phrases: [
      { id: "p-what-colour", phrase: "What colour is it?", uz: "U nima rang?", ipa: "/wɒt ˈkʌlə ɪz ɪt/", example: "What colour is your pen? It is blue.", exampleUz: "Ruchkangiz nima rang? Ko‘k.", speakingTask: "Ask the colour of three objects." },
      { id: "p-it-is-red", phrase: "It is red.", uz: "U qizil.", ipa: "/ɪt ɪz red/", example: "The apple is red.", exampleUz: "Olma qizil.", speakingTask: "Describe three things by colour." },
      { id: "p-a-small", phrase: "a small bag", uz: "kichik sumka", ipa: "/ə smɔːl bæɡ/", example: "I have a small bag.", exampleUz: "Menda kichik sumka bor.", speakingTask: "Use adjective + noun twice." },
      { id: "p-my-fav", phrase: "My favourite colour is…", uz: "Sevimli rangim…", ipa: "/maɪ ˈfeɪvərɪt ˈkʌlə ɪz/", example: "My favourite colour is green.", exampleUz: "Sevimli rangim yashil.", speakingTask: "Say your favourite colour." },
    ],
    listening: listen("Colours in the bag", "Sumkadagi ranglar", [
      { en: "What colour is your pen?", uz: "Ruchkangiz nima rang?" },
      { en: "It is blue.", uz: "Ko‘k." },
      { en: "And the book?", uz: "Kitobchi?" },
      { en: "The book is green. It is a small book.", uz: "Kitob yashil. Kichik kitob." },
      { en: "Is the bag black?", uz: "Sumka qorami?" },
      { en: "No, it isn't. It is white.", uz: "Yo‘q. U oq." },
    ], [
      mcq("pre07-lq1", "The pen is…", ["red", "blue", "black", "white"], "blue", "It is blue.", "Ko‘k.", { skill: "listening" }),
      gap("pre07-lq2", "The bag is ___.", "white", "It is white.", "Oq.", { skill: "listening" }),
    ]),
    reading: reading("My things", "Mening narsalarim",
      "I have a red apple and a green book. My pen is blue. My bag is black. It is a small bag. The class is big. What colour is your bag? My favourite colour is white.",
      [
        mcq("pre07-rq1", "The apple is…", ["green", "red", "blue", "white"], "red", "a red apple", "qizil olma", { skill: "reading" }),
        mcq("pre07-rq2", "The bag is…", ["big and white", "small and black", "red", "blue"], "small and black", "black + small bag", "qora va kichik", { skill: "reading" }),
      ],
      "List the colours in the text.",
    ),
    speaking: { prompt: "Describe five things in the room by colour and size.", promptUz: "Xonadagi 5 narsani rang va o‘lcham bilan ta’riflang.", scaffolding: ["It is a…", "What colour is it?"] },
    writing: { prompt: "Write 6 sentences: colours and big/small.", promptUz: "Rang va big/small bilan 6 gap.", minWords: 30, scaffolding: ["I have a red…", "The room is…"] },
    exercises: [
      mcq("pre07-e1", "Choose the correct order.", ["a book red", "red a book", "a red book", "book a red"], "a red book", "Adjective before noun.", "Sifat + ot."),
      gap("pre07-e2", "What ___ is it?", "colour", "What colour is it?", "What colour…"),
      order("pre07-e3", ["blue", "is", "pen", "The"], "The pen is blue", "The + noun + is + adjective."),
      errx("pre07-e4", "a bag black", "a black bag", "black before bag.", "sifat oldinda."),
      tr("pre07-e5", "Bu katta xona.", "It is a big room", "It is a big room.", { answer: ["It is a big room", "This is a big room"] }),
      mcq("pre07-e6", "Opposite of big:", ["red", "small", "white", "late"], "small", "big ↔ small.", "katta ↔ kichik."),
      gap("pre07-e7", "My favourite ___ is green.", "colour", "favourite colour", "sevimli rang"),
      order("pre07-e8", ["colour", "What", "is", "it"], "What colour is it", "What colour is it?"),
      tr("pre07-e9", "Ruchka ko‘k.", "The pen is blue", "The pen is blue.", { answer: ["The pen is blue", "It is a blue pen"] }),
      mcq("pre07-e10", "The book is not big. It is ___.", ["red", "small", "I", "please"], "small", "not big → small.", "kichik."),
    ],
    test: [
      mcq("pre07-t1", "a ___ apple", ["red", "reds", "redly", "colour"], "red", "adjective form red.", "red."),
      gap("pre07-t2", "The room is ___. (katta)", "big", "big = katta.", "big."),
      errx("pre07-t3", "It is a blue.", "It is blue", "No a without a noun.", "ot bo‘lmasa a yo‘q."),
      tr("pre07-t4", "U nima rang?", "What colour is it", "What colour is it?"),
      order("pre07-t5", ["small", "a", "bag"], "a small bag", "a + adj + noun."),
      mcq("pre07-t6", "black ↔", ["blue", "green", "white", "big"], "white", "black ↔ white.", "qora ↔ oq."),
    ],
  },
  {
    id: "pre-a1-08",
    day: 8,
    level: L,
    topic: "Family",
    topicUz: "Oila",
    cefrCanDo: "I can name close family members and say who they are.",
    cefrCanDoUz: "Yaqin oila a’zolarini aytaman va kimligini tushuntiraman.",
    grammar: {
      title: "Possessive my / your",
      titleUz: "Egalik: my / your",
      meaning: "My and your show who something belongs to.",
      meaningUz: "My va your egalikni bildiradi.",
      form: "my + noun. your + noun. This is my mother.",
      formUz: "my + ot. your + ot.",
      why: "English uses a special word (my), not only of me.",
      whyUz: "My — alohida so‘z, of me emas.",
      examples: [
        { en: "This is my father.", uz: "Bu mening otam." },
        { en: "Your sister is a student.", uz: "Singlingiz o‘quvchi." },
        { en: "My family is small.", uz: "Oilam kichik." },
      ],
      negative: {
        form: "This is not my bag.",
        examples: [{ en: "He is not my brother. He is my friend.", uz: "U akam emas. Do‘stim." }],
      },
      question: {
        form: "Who is this? Is this your mother?",
        examples: [{ en: "Who is she? She is my sister.", uz: "Bu kim? Singlim." }],
      },
      mistakes: [
        { wrong: "This is I mother.", right: "This is my mother.", why: "Use my, not I, before a noun.", whyUz: "Ot oldida my." },
        { wrong: "Your is teacher.", right: "He is your teacher. / Your teacher is here.", why: "your needs a noun after it, or use he/she.", whyUz: "your dan keyin ot kerak." },
      ],
    },
    vocabulary: [
      w("w-family", "family", "oila", "noun", "/ˈfæməli/", "parents and children together", "My family is here.", "Oilam shu yerda.", "family", "Users", { family: [{ form: "families", pos: "noun" }] }),
      w("w-mother", "mother", "ona", "noun", "/ˈmʌðə/", "a female parent", "My mother is a teacher.", "Onam o‘qituvchi.", "family", "Heart", { synonyms: ["mum", "mom"] }),
      w("w-father", "father", "ota", "noun", "/ˈfɑːðə/", "a male parent", "My father is at home.", "Otam uyda.", "family", "User", { synonyms: ["dad"] }),
      w("w-sister", "sister", "opa / singil", "noun", "/ˈsɪstə/", "a girl with the same parents", "I have one sister.", "Bitta singlim bor.", "family", "User"),
      w("w-brother", "brother", "aka / uka", "noun", "/ˈbrʌðə/", "a boy with the same parents", "He is my brother.", "U akam.", "family", "User"),
      w("w-mother-word", "mum", "ona (oddiy)", "noun", "/mʌm/", "informal mother", "Hi, Mum.", "Salom, ona.", "family", "Heart"),
      w("w-my", "my", "mening", "determiner", "/maɪ/", "belongs to me", "my book, my family", "mening kitobim", "grammar", "User"),
      w("w-your", "your", "sening / sizning", "determiner", "/jɔː/", "belongs to you", "your name", "sizning ismingiz", "grammar", "Users"),
    ],
    phrases: [
      { id: "p-this-is-my", phrase: "This is my mother.", uz: "Bu mening onam.", ipa: "/ðɪs ɪz maɪ ˈmʌðə/", example: "This is my mother, Lola.", exampleUz: "Bu onam, Lola.", speakingTask: "Show a photo and introduce family." },
      { id: "p-i-have", phrase: "I have a brother.", uz: "Akam/ukam bor.", ipa: "/aɪ hæv ə ˈbrʌðə/", example: "I have a brother and a sister.", exampleUz: "Akam va singlim bor.", speakingTask: "Say how many brothers/sisters you have." },
      { id: "p-who-is", phrase: "Who is this?", uz: "Bu kim?", ipa: "/huː ɪz ðɪs/", example: "Who is this? This is my father.", exampleUz: "Bu kim? Otam.", speakingTask: "Ask who people are." },
      { id: "p-family-small", phrase: "My family is small.", uz: "Oilam kichik.", ipa: "/maɪ ˈfæməli ɪz smɔːl/", example: "My family is small but happy.", exampleUz: "Oilam kichik, lekin baxtli.", speakingTask: "Say if your family is big or small." },
    ],
    listening: listen("A family photo", "Oila surati", [
      { en: "Who is this?", uz: "Bu kim?" },
      { en: "This is my father.", uz: "Bu otam." },
      { en: "And she is my mother.", uz: "Va u onam." },
      { en: "Is he your brother?", uz: "U akangizmi?" },
      { en: "Yes. He is ten.", uz: "Ha. U o‘n yoshda." },
      { en: "Your family is happy.", uz: "Oilangiz baxtli." },
    ], [
      mcq("pre08-lq1", "The boy is…", ["father", "mother", "brother", "teacher"], "brother", "He is your brother? Yes.", "Aka.", { skill: "listening" }),
      gap("pre08-lq2", "This is my ___.", "father", "This is my father.", "Ota.", { skill: "listening" }),
    ]),
    reading: reading("My family", "Mening oilam",
      "My name is Sara. This is my family. My mother is a teacher. My father is at home today. I have one brother. He is twelve. I have no sister. My family is small. We are happy.",
      [
        mcq("pre08-rq1", "Sara has…", ["two sisters", "one brother", "no family", "two fathers"], "one brother", "I have one brother.", "Bitta aka.", { skill: "reading" }),
        mcq("pre08-rq2", "Her mother is…", ["twelve", "a teacher", "a brother", "small"], "a teacher", "My mother is a teacher.", "Ona — teacher.", { skill: "reading" }),
      ],
      "Draw a mini family tree in words.",
    ),
    speaking: { prompt: "Talk about your family for 30 seconds.", promptUz: "Oilangiz haqida 30 soniya gapiring.", scaffolding: ["This is my…", "I have…", "My family is…"] },
    writing: { prompt: "Write 6 sentences about your family.", promptUz: "Oila haqida 6 gap.", minWords: 35, scaffolding: ["My mother is…", "I have…"] },
    exercises: [
      mcq("pre08-e1", "This is ___ mother.", ["I", "me", "my", "you"], "my", "my + noun.", "my + ot."),
      gap("pre08-e2", "___ is this? — My father.", "Who", "Who is this?", "Who is this?"),
      order("pre08-e3", ["is", "This", "my", "sister"], "This is my sister", "This is my + family word."),
      errx("pre08-e4", "This is I father.", "This is my father", "my not I.", "my."),
      tr("pre08-e5", "Bu mening onam.", "This is my mother", "This is my mother."),
      mcq("pre08-e6", "A boy in your family:", ["mother", "sister", "brother", "mum"], "brother", "brother = boy.", "aka/uka."),
      gap("pre08-e7", "I ___ one sister.", "have", "I have + person.", "I have."),
      order("pre08-e8", ["family", "My", "is", "small"], "My family is small", "My family is + adjective."),
      tr("pre08-e9", "Oilangiz katta mi?", "Is your family big", "Is your family big?"),
      mcq("pre08-e10", "your + name =", ["I name", "you name", "your name", "he name"], "your name", "your + noun.", "your name."),
    ],
    test: [
      mcq("pre08-t1", "female parent =", ["father", "brother", "mother", "he"], "mother", "mother.", "ona."),
      gap("pre08-t2", "This is ___ brother. (meniki)", "my", "my brother.", "my."),
      errx("pre08-t3", "Who she is?", "Who is she", "Who is she?", "Who is she?"),
      tr("pre08-t4", "Mening oilam kichik.", "My family is small", "My family is small."),
      order("pre08-t5", ["have", "I", "a", "brother"], "I have a brother", "I have a brother."),
      mcq("pre08-t6", "Is this your sister? — Yes, she ___.", ["am", "is", "are", "have"], "is", "Yes, she is.", "Yes, she is."),
    ],
  },
  {
    id: "pre-a1-09",
    day: 9,
    level: L,
    topic: "Classroom things",
    topicUz: "Sinf jihozlari",
    cefrCanDo: "I can name classroom objects and follow simple classroom instructions.",
    cefrCanDoUz: "Sinf narsalarini aytaman va oddiy ko‘rsatmalarga amal qilaman.",
    grammar: {
      title: "A / an and classroom English",
      titleUz: "A / an va sinf tili",
      meaning: "A and an mean one thing, not a special thing. An before a vowel sound.",
      meaningUz: "A/an — bitta, noaniq. Unli tovush oldidan an.",
      form: "a book, a pen, an apple, an English book. Open your book. Sit down.",
      formUz: "a + undosh. an + unli tovush. Buyruq: Open your book.",
      why: "English needs a/an with singular countable nouns when they are new.",
      whyUz: "Yangi birlikdagi sanalsin otlar bilan a/an kerak.",
      examples: [
        { en: "This is a pen.", uz: "Bu ruchka." },
        { en: "That is an apple.", uz: "Bu olma." },
        { en: "Open your book, please.", uz: "Kitobingizni oching, iltimos." },
      ],
      negative: {
        form: "It is not a pen. It is a pencil.",
        examples: [{ en: "This is not a chair. It is a desk.", uz: "Bu stul emas. Parta." }],
      },
      question: {
        form: "What is this? Is it a bag?",
        examples: [{ en: "What is this? It is a pencil.", uz: "Bu nima? Qalam." }],
      },
      mistakes: [
        { wrong: "This is pen.", right: "This is a pen.", why: "Singular countable nouns need a/an.", whyUz: "Birlikdagi otga a/an kerak." },
        { wrong: "a apple", right: "an apple", why: "apple starts with a vowel sound.", whyUz: "apple unli bilan." },
      ],
      contrast: {
        vs: "a vs an",
        a: "a book, a university (yoo-sound)",
        b: "an apple, an hour (vowel sound)",
        note: "Listen to the sound, not only the letter.",
        noteUz: "Harf emas, tovush muhim.",
      },
    },
    vocabulary: [
      w("w-pen", "pen", "ruchka", "noun", "/pen/", "you write with ink", "This is a pen.", "Bu ruchka.", "school", "Pen"),
      w("w-pencil", "pencil", "qalam", "noun", "/ˈpensəl/", "you write and can erase", "a red pencil", "qizil qalam", "school", "Pencil"),
      w("w-bag", "bag", "sumka", "noun", "/bæɡ/", "you carry things in it", "my school bag", "maktab sumkam", "school", "Briefcase"),
      w("w-desk", "desk", "parta", "noun", "/desk/", "a table for study", "Sit at your desk.", "Partangizga o‘tiring.", "school", "Table"),
      w("w-chair", "chair", "stul", "noun", "/tʃeə/", "you sit on it", "This is a chair.", "Bu stul.", "school", "Armchair"),
      w("w-open", "open", "ochmoq", "verb", "/ˈəʊpən/", "make something not closed", "Open your book.", "Kitobni oching.", "school", "BookOpen", { antonyms: ["close"] }),
      w("w-close", "close", "yopmoq", "verb", "/kləʊz/", "make something not open", "Close the door.", "Eshikni yoping.", "school", "DoorClosed", { antonyms: ["open"] }),
      w("w-listen", "listen", "tinglamoq", "verb", "/ˈlɪsən/", "hear with attention", "Listen, please.", "Tinglang, iltimos.", "school", "Ear", { collocations: ["listen to"] }),
    ],
    phrases: [
      { id: "p-what-is-this", phrase: "What is this?", uz: "Bu nima?", ipa: "/wɒt ɪz ðɪs/", example: "What is this? It is a pen.", exampleUz: "Bu nima? Ruchka.", speakingTask: "Point and ask What is this?" },
      { id: "p-open-book", phrase: "Open your book, please.", uz: "Kitobingizni oching, iltimos.", ipa: "/ˈəʊpən jɔː bʊk pliːz/", example: "Open your book at page two.", exampleUz: "Kitobni 2-betdan oching.", speakingTask: "Give two classroom instructions." },
      { id: "p-sit-down", phrase: "Sit down, please.", uz: "O‘tiring, iltimos.", ipa: "/sɪt daʊn pliːz/", example: "Please sit down at your desk.", exampleUz: "Partaga o‘tiring.", speakingTask: "Say sit down and stand up." },
      { id: "p-this-is-a", phrase: "This is a pencil.", uz: "Bu qalam.", ipa: "/ðɪs ɪz ə ˈpensəl/", example: "This is a pencil. That is a pen.", exampleUz: "Bu qalam. U ruchka.", speakingTask: "Name four classroom objects." },
    ],
    listening: listen("In the classroom", "Sinfda", [
      { en: "Good morning. Sit down, please.", uz: "Xayrli tong. O‘tiring." },
      { en: "Open your book.", uz: "Kitobni oching." },
      { en: "What is this?", uz: "Bu nima?" },
      { en: "It is a pencil.", uz: "Qalam." },
      { en: "Listen, please.", uz: "Tinglang." },
      { en: "Now close your books.", uz: "Endi kitoblarni yoping." },
    ], [
      mcq("pre09-lq1", "First instruction:", ["Close your books", "Sit down", "Go home", "Spell"], "Sit down", "Sit down, please.", "O‘tiring.", { skill: "listening" }),
      gap("pre09-lq2", "It is a ___.", "pencil", "It is a pencil.", "Qalam.", { skill: "listening" }),
    ]),
    reading: reading("Room 3", "3-xona",
      "This is Room 3. It is a small class. This is a desk and this is a chair. That is a bag. It is black. Open your book, please. This is a pen and that is a pencil. Listen to the teacher.",
      [
        mcq("pre09-rq1", "The bag is…", ["blue", "black", "red", "green"], "black", "It is black.", "Qora.", { skill: "reading" }),
        mcq("pre09-rq2", "Room 3 is…", ["big", "small", "a pen", "late"], "small", "a small class", "Kichik.", { skill: "reading" }),
      ],
      "List the classroom objects.",
    ),
    speaking: { prompt: "Give and follow 5 classroom commands.", promptUz: "5 ta sinf buyrug‘ini ayting.", scaffolding: ["Sit down.", "Open your book.", "Listen, please."] },
    writing: { prompt: "Write 7 sentences about your classroom.", promptUz: "Sinfingiz haqida 7 gap.", minWords: 35, scaffolding: ["This is a…", "That is an…"] },
    exercises: [
      mcq("pre09-e1", "___ apple", ["a", "an", "the the", "two"], "an", "vowel sound → an.", "an apple."),
      gap("pre09-e2", "This is ___ pen.", "a", "a + consonant sound.", "a pen."),
      order("pre09-e3", ["your", "Open", "book"], "Open your book", "Imperative + your + noun."),
      errx("pre09-e4", "This is pen.", "This is a pen", "Need a.", "a kerak."),
      tr("pre09-e5", "Bu nima?", "What is this", "What is this?"),
      mcq("pre09-e6", "You sit on a…", ["pen", "chair", "pencil", "bag"], "chair", "chair for sitting.", "stul."),
      gap("pre09-e7", "___ down, please.", "Sit", "Sit down, please.", "O‘tiring."),
      order("pre09-e8", ["is", "What", "this"], "What is this", "What is this?"),
      tr("pre09-e9", "Kitobingizni oching.", "Open your book", "Open your book."),
      mcq("pre09-e10", "Close is the opposite of…", ["sit", "open", "listen", "pen"], "open", "open ↔ close.", "ochmoq ↔ yopmoq."),
    ],
    test: [
      mcq("pre09-t1", "an is used before…", ["book", "pen", "apple", "desk"], "apple", "vowel sound.", "unli."),
      gap("pre09-t2", "___ your books.", "Close", "Close your books.", "Yoping."),
      errx("pre09-t3", "a English book", "an English book", "English starts with a vowel sound.", "an English."),
      tr("pre09-t4", "Bu qalam.", "This is a pencil", "This is a pencil."),
      order("pre09-t5", ["a", "is", "This", "desk"], "This is a desk", "This is a + noun."),
      mcq("pre09-t6", "Listen, ___.", ["colour", "please", "family", "twenty"], "please", "polite instruction.", "iltimos."),
    ],
  },
  {
    id: "pre-a1-10",
    day: 10,
    level: L,
    topic: "Starter review",
    topicUz: "Boshlanish takrori",
    cefrCanDo: "I can use letters, numbers, greetings, pronouns and be together.",
    cefrCanDoUz: "Harf, raqam, salom, olmosh va be’ni birga ishlataman.",
    isReview: true,
    grammar: {
      title: "Putting it together",
      titleUz: "Hammasini birlashtirish",
      meaning: "We recycle alphabet, numbers, greetings, pronouns, be, colours and family.",
      meaningUz: "Alifbo, raqam, salom, olmosh, be, rang va oilani takrorlaymiz.",
      form: "My name is… I am… She is… This is a… What colour…? How old…?",
      formUz: "O‘tilgan barcha shakllar.",
      why: "Review makes new language automatic.",
      whyUz: "Takror avtomatlashtiradi.",
      examples: [
        { en: "Hello. My name is Ali. I am twelve.", uz: "Salom. Ismim Ali. O‘n ikkiman." },
        { en: "This is my mother. She is a teacher.", uz: "Bu onam. U o‘qituvchi." },
        { en: "It is a small red bag.", uz: "Bu kichik qizil sumka." },
      ],
      negative: { form: "I am not… She isn't…", examples: [{ en: "I am not a teacher. I am a student.", uz: "O‘qituvchi emasman. O‘quvchiman." }] },
      question: { form: "How are you? How old are you? What is this?", examples: [{ en: "How old are you? I am twenty.", uz: "Yoshingiz? Yigirma." }] },
      mistakes: [
        { wrong: "I have 12 years. This is I bag.", right: "I am 12. This is my bag.", why: "Age with be. Possessive my.", whyUz: "Yosh — be. Egalik — my." },
        { wrong: "She are my sister.", right: "She is my sister.", why: "she + is.", whyUz: "she is." },
      ],
    },
    vocabulary: [
      w("w-tomorrow", "tomorrow", "ertaga", "adverb", "/təˈmɒrəʊ/", "the day after today", "See you tomorrow.", "Ertaga ko‘rishamiz.", "time", "Calendar"),
      w("w-today", "today", "bugun", "adverb", "/təˈdeɪ/", "this day", "I am here today.", "Bugun shu yerdaman.", "time", "Sun"),
      w("w-class", "class", "sinf / dars", "noun", "/klɑːs/", "a group of students or a lesson", "We are in class.", "Biz darsdamiz.", "school", "School"),
      w("w-good", "good", "yaxshi", "adjective", "/ɡʊd/", "positive quality", "It is a good book.", "Yaxshi kitob.", "feelings", "ThumbsUp", { antonyms: ["bad"] }),
      w("w-bad", "bad", "yomon", "adjective", "/bæd/", "not good", "This is not a bad day.", "Yomon kun emas.", "feelings", "ThumbsDown", { antonyms: ["good"] }),
      w("w-page", "page", "bet", "noun", "/peɪdʒ/", "one side in a book", "Open page ten.", "O‘ninchi betni oching.", "school", "FileText"),
      w("w-door", "door", "eshik", "noun", "/dɔː/", "you open it to go in", "Close the door.", "Eshikni yoping.", "school", "Door"),
      w("w-window", "window", "deraza", "noun", "/ˈwɪndəʊ/", "glass in the wall", "The window is big.", "Deraza katta.", "school", "AppWindow"),
    ],
    phrases: [
      { id: "p-lets-start", phrase: "Let's start.", uz: "Boshlaylik.", ipa: "/lets stɑːt/", example: "Are you ready? Let's start.", exampleUz: "Tayyormisiz? Boshlaylik.", speakingTask: "Start a mini dialogue." },
      { id: "p-i-dont-know", phrase: "I don't know.", uz: "Bilmayman.", ipa: "/aɪ dəʊnt nəʊ/", example: "What is this? I don't know.", exampleUz: "Bu nima? Bilmayman.", speakingTask: "Use I don't know honestly, then ask." },
      { id: "p-again", phrase: "Once more, please.", uz: "Yana bir marta, iltimos.", ipa: "/wʌns mɔː pliːz/", example: "Once more, please. Thank you.", exampleUz: "Yana bir marta. Rahmat.", speakingTask: "Ask for a repeat." },
      { id: "p-full-intro", phrase: "Hello, my name is… I am…", uz: "Salom, ismim… men…", ipa: "/həˈləʊ maɪ neɪm ɪz/", example: "Hello, my name is Lola. I am 18. I am a student.", exampleUz: "Salom, Lola. 18. O‘quvchi.", speakingTask: "Give a 4-sentence self-introduction." },
    ],
    listening: listen("A full conversation", "To‘liq suhbat", [
      { en: "Hello. My name is Bek.", uz: "Salom. Ismim Bek." },
      { en: "Hi Bek. How are you?", uz: "Salom Bek. Qalaysiz?" },
      { en: "I'm fine, thanks. How old are you?", uz: "Yaxshi. Yoshingiz?" },
      { en: "I am twenty. This is my sister.", uz: "Yigirma. Bu singlim." },
      { en: "Nice to meet you. What colour is your bag?", uz: "Tanishganimdan xursandman. Sumka nima rang?" },
      { en: "It is a small black bag. See you tomorrow.", uz: "Kichik qora sumka. Ertaga ko‘rishamiz." },
    ], [
      mcq("pre10-lq1", "Bek is…", ["12", "20", "a teacher", "Ana"], "20", "I am twenty.", "20.", { skill: "listening" }),
      gap("pre10-lq2", "The bag is ___.", "black", "small black bag", "qora", { skill: "listening" }),
    ]),
    reading: reading("Starter letter", "Boshlanish xati",
      "Hello. My name is Noila. I am a student. I am not a teacher. I am nineteen. This is my family. My father is at home. My mother is a teacher. I have a blue pen and a red book. What is your name? How old are you? See you in class tomorrow.",
      [
        mcq("pre10-rq1", "Noila is…", ["a teacher", "nineteen and a student", "twelve", "Bek"], "nineteen and a student", "student + 19", "19 va student", { skill: "reading" }),
        mcq("pre10-rq2", "Her pen is…", ["red", "black", "blue", "green"], "blue", "a blue pen", "ko‘k", { skill: "reading" }),
      ],
      "Write a similar letter about you.",
    ),
    speaking: { prompt: "Introduce yourself: name, age, family, one object and its colour.", promptUz: "Ism, yosh, oila, bitta narsa va rangi.", scaffolding: ["Hello, my name is…", "I am…", "This is my…"] },
    writing: { prompt: "Write 80–100 characters more than 8 sentences about you using this week's language.", promptUz: "Shu hafta tili bilan 8+ gap yozing.", minWords: 50, scaffolding: ["Hello…", "I am…", "My family…"] },
    exercises: [
      mcq("pre10-e1", "I ___ 18.", ["have", "am", "is", "are"], "am", "Age with am.", "yosh — am."),
      gap("pre10-e2", "How ___ you?", "are", "How are you?", "How are you?"),
      order("pre10-e3", ["is", "This", "my", "mother"], "This is my mother", "This is my + noun."),
      errx("pre10-e4", "She are a teacher.", "She is a teacher", "she is.", "she is."),
      tr("pre10-e5", "Mening ismim Ali.", "My name is Ali", "My name is Ali."),
      mcq("pre10-e6", "a ___ book", ["red", "I", "am", "who"], "red", "adjective + noun.", "sifat+ot."),
      gap("pre10-e7", "___ do you spell that?", "How", "How do you spell that?", "How do you spell…"),
      order("pre10-e8", ["old", "you", "are", "How"], "How old are you", "How old are you?"),
      tr("pre10-e9", "Bu nima?", "What is this", "What is this?"),
      mcq("pre10-e10", "They ___ not at home.", ["am", "is", "are", "be"], "are", "they are not.", "they are not."),
    ],
    test: [
      mcq("pre10-t1", "Choose the correct sentence.", ["I is student.", "I am a student.", "I student am.", "Am I student yes."], "I am a student.", "I am a + noun.", "I am a student."),
      gap("pre10-t2", "Nice to ___ you.", "meet", "Nice to meet you.", "meet."),
      errx("pre10-t3", "This is I bag.", "This is my bag", "my bag.", "my."),
      tr("pre10-t4", "Qalaysiz?", "How are you", "How are you?"),
      order("pre10-t5", ["name", "is", "My", "Noila"], "My name is Noila", "My name is…"),
      mcq("pre10-t6", "Open your book, ___.", ["sorry", "please", "family", "twenty"], "please", "polite.", "please."),
      gap("pre10-t7", "She ___ my sister.", "is", "she is.", "is."),
      mcq("pre10-t8", "11 =", ["twelve", "eleven", "twenty", "one"], "eleven", "11 eleven.", "eleven."),
    ],
  },
];
