import type { Lesson, Word } from "@/lib/types";
import { errx, gap, listen, mcq, order, reading, tr } from "@/lib/content/helpers";

const L = "pre-a1" as const;

function w(
  id: string,
  word: string,
  uz: string,
  pos: Word["pos"],
  ipa: string,
  definition: string,
  example: string,
  exampleUz: string,
  category: string,
  icon: string,
  extra: Partial<Word> = {},
): Word {
  return {
    id,
    word,
    uz,
    pos,
    ipa,
    definition,
    example,
    exampleUz,
    collocations: extra.collocations ?? [],
    synonyms: extra.synonyms ?? [],
    antonyms: extra.antonyms ?? [],
    family: extra.family ?? [],
    level: L,
    category,
    icon,
  };
}

export const lessons: Lesson[] = [
  {
    id: "pre-a1-01",
    day: 1,
    level: L,
    topic: "The English alphabet",
    topicUz: "Ingliz alifbosi",
    cefrCanDo: "I can recognise English letters and spell my name.",
    cefrCanDoUz: "Ingliz harflarini taniman va ismimni harflab ayta olaman.",
    grammar: {
      title: "Letters and sounds",
      titleUz: "Harflar va tovushlar",
      meaning: "English has 26 letters. Each letter has a name (A, B, C) and one or more sounds.",
      meaningUz: "Ingliz tilida 26 ta harf bor. Har bir harfning nomi va tovushi bor.",
      form: "Capital letters: A B C … Z. Small letters: a b c … z.",
      formUz: "Katta harflar: A B C. Kichik harflar: a b c.",
      why: "We use capital letters for names and at the start of a sentence.",
      whyUz: "Katta harf ismlar va gap boshida ishlatiladi.",
      examples: [
        { en: "My name is Shodlik.", uz: "Mening ismim Shodlik." },
        { en: "A is for apple.", uz: "A — apple uchun." },
        { en: "B is for book.", uz: "B — book uchun." },
      ],
      negative: {
        form: "We do not start a name with a small letter.",
        examples: [{ en: "Not: my name is ali. → My name is Ali.", uz: "Ism katta harf bilan yoziladi." }],
      },
      question: {
        form: "How do you spell it?",
        examples: [{ en: "How do you spell your name?", uz: "Ismingiz qanday harflanadi?" }],
      },
      mistakes: [
        {
          wrong: "i am lola",
          right: "I am Lola",
          why: "I and names need a capital letter.",
          whyUz: "I va ismlar katta harf bilan yoziladi.",
        },
        {
          wrong: "how do you spel it?",
          right: "How do you spell it?",
          why: "Spell has two l's. Questions start with a capital.",
          whyUz: "Spell ikkita l bilan yoziladi.",
        },
      ],
    },
    vocabulary: [
      w("w-letter", "letter", "harf", "noun", "/ˈletə/", "a character in the alphabet", "A is a letter.", "A — bu harf.", "alphabet", "Type", { collocations: ["capital letter", "small letter"], family: [{ form: "letters", pos: "noun" }] }),
      w("w-alphabet", "alphabet", "alifbo", "noun", "/ˈælfəbet/", "all the letters from A to Z", "The English alphabet has 26 letters.", "Ingliz alifbosida 26 harf bor.", "alphabet", "BookOpen"),
      w("w-name", "name", "ism", "noun", "/neɪm/", "what a person is called", "My name is Sara.", "Mening ismim Sara.", "people", "User", { collocations: ["first name", "full name"] }),
      w("w-spell", "spell", "harflab aytmoq", "verb", "/spel/", "say the letters of a word", "Please spell your name.", "Ismingizni harflab ayting.", "alphabet", "Pencil"),
      w("w-capital", "capital letter", "katta harf", "noun", "/ˈkæpɪtl ˈletə/", "A, B, C — not a, b, c", "Names start with a capital letter.", "Ismlar katta harf bilan boshlanadi.", "alphabet", "CaseSensitive"),
      w("w-apple", "apple", "olma", "noun", "/ˈæpəl/", "a round fruit", "I like this apple.", "Bu olma menga yoqadi.", "food", "Apple", { collocations: ["red apple", "an apple"] }),
      w("w-book", "book", "kitob", "noun", "/bʊk/", "pages you read", "This is my book.", "Bu mening kitobim.", "school", "Book"),
      w("w-english", "English", "ingliz tili", "noun", "/ˈɪŋɡlɪʃ/", "the language of this course", "I study English.", "Men ingliz tilini o‘rganaman.", "study", "Languages"),
    ],
    phrases: [
      { id: "p-spell-name", phrase: "How do you spell that?", uz: "Buni qanday harflaysiz?", ipa: "/haʊ duː juː spel ðæt/", example: "How do you spell your name?", exampleUz: "Ismingizni qanday harflaysiz?", speakingTask: "Ask a friend to spell their name." },
      { id: "p-my-name", phrase: "My name is…", uz: "Mening ismim…", ipa: "/maɪ neɪm ɪz/", example: "My name is Aziz.", exampleUz: "Mening ismim Aziz.", speakingTask: "Say your name." },
      { id: "p-repeat", phrase: "Can you repeat that?", uz: "Qaytaringchi?", ipa: "/kæn juː rɪˈpiːt ðæt/", example: "Sorry, can you repeat that?", exampleUz: "Kechirasiz, qaytaringchi?", speakingTask: "Ask someone to repeat." },
      { id: "p-a-for", phrase: "A is for apple.", uz: "A — apple uchun.", ipa: "/eɪ ɪz fə ˈæpəl/", example: "B is for book.", exampleUz: "B — book uchun.", speakingTask: "Say three letters with example words." },
    ],
    listening: listen(
      "Spelling names",
      "Ismlarni harflash",
      [
        { en: "Hello. What is your name?", uz: "Salom. Ismingiz nima?" },
        { en: "My name is Omar.", uz: "Mening ismim Omar." },
        { en: "How do you spell that?", uz: "Qanday harlaysiz?" },
        { en: "O-M-A-R.", uz: "O-M-A-R." },
        { en: "Nice to meet you, Omar.", uz: "Tanishganimdan xursandman, Omar." },
        { en: "Nice to meet you too.", uz: "Men ham." },
      ],
      [
        mcq("pre01-lq1", "What is his name?", ["Ali", "Omar", "Sara", "Lola"], "Omar", "He says: My name is Omar.", "U: My name is Omar, deydi.", { skill: "listening" }),
        gap("pre01-lq2", "How do you ___ that?", "spell", "The question is How do you spell that?", "Savol: How do you spell that?", { skill: "listening" }),
      ],
    ),
    reading: reading(
      "My name",
      "Mening ismim",
      "Hello. My name is Ana. I am a student. I study English. A is for apple. B is for book. C is for cat. Please spell your name. My name is A-N-A. Nice to meet you.",
      [
        mcq("pre01-rq1", "What is her name?", ["Omar", "Ana", "Book", "Cat"], "Ana", "The text says My name is Ana.", "Matnda My name is Ana.", { skill: "reading" }),
        mcq("pre01-rq2", "A is for…", ["book", "cat", "apple", "name"], "apple", "A is for apple.", "A — apple.", { skill: "reading" }),
      ],
      "Say the letters of your name.",
    ),
    speaking: {
      prompt: "Spell your first name slowly.",
      promptUz: "Ismingizni sekin harflab ayting.",
      scaffolding: ["My name is…", "It is spelled…"],
    },
    writing: {
      prompt: "Write 4 sentences: your name, one letter example, and How do you spell that?",
      promptUz: "4 ta gap yozing: ism, bitta harf misoli va How do you spell that?",
      minWords: 20,
      scaffolding: ["My name is…", "A is for…"],
    },
    exercises: [
      mcq("pre01-e1", "English has ___ letters.", ["20", "24", "26", "30"], "26", "The English alphabet has 26 letters.", "26 ta harf bor."),
      mcq("pre01-e2", "Names start with a ___ letter.", ["small", "capital", "number", "sound"], "capital", "Names start with a capital letter.", "Ismlar katta harf bilan."),
      gap("pre01-e3", "How do you ___ your name?", "spell", "We spell names letter by letter.", "Ism harflab aytiladi."),
      order("pre01-e4", ["is", "My", "name", "Lola"], "My name is Lola", "Subject + name is + name.", "My name is + ism."),
      errx("pre01-e5", "my name is ali", "My name is Ali", "Capital I is not needed here but My and Ali need capitals.", "My va Ali katta harf."),
      tr("pre01-e6", "Mening ismim Sara.", "My name is Sara", "My name is + name."),
      mcq("pre01-e7", "Choose the capital letter.", ["b", "m", "A", "s"], "A", "A is a capital letter.", "A — katta harf."),
      gap("pre01-e8", "The English ___ has 26 letters.", "alphabet", "Alphabet = all letters A–Z.", "Alifbo — barcha harflar."),
      order("pre01-e9", ["you", "do", "How", "spell", "it"], "How do you spell it", "Question word + do + subject + verb.", "How do you + verb."),
      tr("pre01-e10", "Buni qanday harlaysiz?", "How do you spell that", "A very common classroom phrase."),
    ],
    test: [
      mcq("pre01-t1", "B is for…", ["apple", "book", "name", "letter"], "book", "B is for book.", "B — book."),
      gap("pre01-t2", "My ___ is Aziz.", "name", "My name is…", "My name is…"),
      order("pre01-t3", ["name", "is", "My", "Omar"], "My name is Omar", "Fixed phrase.", "Tayyor ibora."),
      errx("pre01-t4", "i study english", "I study English", "I and English take capitals.", "I va English katta harf."),
      tr("pre01-t5", "Ismingiz nima?", "What is your name", "What is your name?"),
      mcq("pre01-t6", "A small letter is…", ["A", "B", "a", "I"], "a", "a is small; A is capital.", "a — kichik harf."),
    ],
  },
  {
    id: "pre-a1-02",
    day: 2,
    level: L,
    topic: "Numbers 0–20",
    topicUz: "Raqamlar 0–20",
    cefrCanDo: "I can say numbers from 0 to 20 and give my age.",
    cefrCanDoUz: "0 dan 20 gacha raqamlarni aytaman va yoshimni ayta olaman.",
    grammar: {
      title: "Numbers and age",
      titleUz: "Raqamlar va yosh",
      meaning: "We use numbers to count and to say age: I am 18.",
      meaningUz: "Raqamlar sanash va yosh aytish uchun: I am 18.",
      form: "0 zero, 1 one … 10 ten, 11 eleven … 20 twenty. Age: I am + number.",
      formUz: "Yosh: I am + raqam.",
      why: "English says I am 20, not I have 20 years.",
      whyUz: "Inglizchada I am 20, I have 20 years emas.",
      examples: [
        { en: "I am ten.", uz: "Men o‘n yoshdaman." },
        { en: "She is twenty.", uz: "U yigirma yoshda." },
        { en: "Two books.", uz: "Ikki kitob." },
      ],
      negative: {
        form: "I am not + number.",
        examples: [{ en: "I am not five. I am six.", uz: "Men besh emasman. Oltiman." }],
      },
      question: {
        form: "How old are you?",
        examples: [{ en: "How old are you? I am twelve.", uz: "Yoshingiz nechida? O‘n ikkiman." }],
      },
      mistakes: [
        { wrong: "I have 10 years.", right: "I am 10.", why: "Use be, not have, for age.", whyUz: "Yosh uchun be ishlatiladi, have emas." },
        { wrong: "How many years you have?", right: "How old are you?", why: "The fixed question is How old are you?", whyUz: "Savol: How old are you?" },
      ],
      contrast: {
        vs: "How many vs How old",
        a: "How many books?",
        b: "How old are you?",
        note: "How many = count things. How old = age.",
        noteUz: "How many — narsalar. How old — yosh.",
      },
    },
    vocabulary: [
      w("w-zero", "zero", "nol", "numeral", "/ˈzɪərəʊ/", "0", "Zero means 0.", "Zero — 0.", "numbers", "Hash"),
      w("w-one", "one", "bir", "numeral", "/wʌn/", "1", "I have one book.", "Menda bitta kitob bor.", "numbers", "Hash"),
      w("w-two", "two", "ikki", "numeral", "/tuː/", "2", "Two apples.", "Ikki olma.", "numbers", "Hash"),
      w("w-three", "three", "uch", "numeral", "/θriː/", "3", "Three letters.", "Uch harf.", "numbers", "Hash"),
      w("w-five", "five", "besh", "numeral", "/faɪv/", "5", "Five students.", "Besh o‘quvchi.", "numbers", "Hash"),
      w("w-ten", "ten", "o‘n", "numeral", "/ten/", "10", "Ten is a round number.", "O‘n — yaxlit son.", "numbers", "Hash"),
      w("w-twelve", "twelve", "o‘n ikki", "numeral", "/twelv/", "12", "There are twelve months.", "O‘n ikki oy bor.", "numbers", "Hash"),
      w("w-twenty", "twenty", "yigirma", "numeral", "/ˈtwenti/", "20", "I am twenty.", "Men yigirmaman.", "numbers", "Hash"),
      w("w-old", "old", "yosh (nechida)", "adjective", "/əʊld/", "used in How old…", "How old are you?", "Yoshingiz nechida?", "people", "Calendar", { antonyms: ["young"] }),
      w("w-age", "age", "yosh", "noun", "/eɪdʒ/", "how many years a person has", "What is your age?", "Yoshingiz nechida?", "people", "Hourglass"),
    ],
    phrases: [
      { id: "p-how-old", phrase: "How old are you?", uz: "Yoshingiz nechida?", ipa: "/haʊ əʊld ɑː juː/", example: "How old are you? I am sixteen.", exampleUz: "Yoshingiz nechida? O‘n olti.", speakingTask: "Ask someone's age politely." },
      { id: "p-i-am-n", phrase: "I am eighteen.", uz: "Men o‘n sakkizman.", ipa: "/aɪ æm eɪˈtiːn/", example: "I am eighteen years old.", exampleUz: "Men o‘n sakkiz yoshdaman.", speakingTask: "Say your age." },
      { id: "p-how-many", phrase: "How many…?", uz: "Nechta…?", ipa: "/haʊ ˈmeni/", example: "How many books?", exampleUz: "Nechta kitob?", speakingTask: "Ask how many pens you see." },
      { id: "p-phone", phrase: "My number is…", uz: "Raqamim…", ipa: "/maɪ ˈnʌmbə ɪz/", example: "My number is 10.", exampleUz: "Raqamim 10.", speakingTask: "Say a number 0–20." },
    ],
    listening: listen(
      "How old are you?",
      "Yoshingiz nechida?",
      [
        { en: "Hi, Lola. How old are you?", uz: "Salom, Lola. Yoshingiz nechida?" },
        { en: "I am twelve.", uz: "O‘n ikkiman." },
        { en: "And your brother?", uz: "Akangizchi?" },
        { en: "He is ten.", uz: "U o‘n yoshda." },
        { en: "How many books have you got?", uz: "Nechta kitobingiz bor?" },
        { en: "Three.", uz: "Uchta." },
      ],
      [
        mcq("pre02-lq1", "How old is Lola?", ["10", "12", "20", "3"], "12", "She says I am twelve.", "U twelve deydi.", { skill: "listening" }),
        gap("pre02-lq2", "He is ___.", "ten", "The brother is ten.", "Aka o‘n yoshda.", { skill: "listening" }),
      ],
    ),
    reading: reading(
      "Class numbers",
      "Sinf raqamlari",
      "This is my class. I am thirteen. My friend Ali is fourteen. We have twenty students. We have ten books and five pens. How old are you? I am not five. I am thirteen. One, two, three — let's count together.",
      [
        mcq("pre02-rq1", "How many students?", ["10", "5", "20", "13"], "20", "Twenty students.", "Yigirma o‘quvchi.", { skill: "reading" }),
        mcq("pre02-rq2", "Ali is…", ["13", "14", "20", "5"], "14", "Ali is fourteen.", "Ali fourteen.", { skill: "reading" }),
      ],
      "Write three numbers from the text.",
    ),
    speaking: { prompt: "Count from 0 to 20, then say your age.", promptUz: "0 dan 20 gacha sanang, keyin yoshingizni ayting.", scaffolding: ["Zero, one, two…", "I am…"] },
    writing: { prompt: "Write 5 sentences with numbers: age, books, friends.", promptUz: "Raqamlar bilan 5 gap yozing.", minWords: 25, scaffolding: ["I am…", "I have two…"] },
    exercises: [
      mcq("pre02-e1", "How old are you? — I ___ 18.", ["have", "am", "is", "do"], "am", "Age uses I am + number.", "Yosh: I am + son."),
      mcq("pre02-e2", "11 is…", ["ten", "twelve", "eleven", "twenty"], "eleven", "11 = eleven.", "11 — eleven."),
      gap("pre02-e3", "How ___ are you?", "old", "How old are you?", "How old are you?"),
      order("pre02-e4", ["am", "I", "twenty"], "I am twenty", "I am + number.", "I am + raqam."),
      errx("pre02-e5", "I have 9 years.", "I am 9", "Do not use have for age.", "Yoshda have yo‘q."),
      tr("pre02-e6", "Yoshingiz nechida?", "How old are you", "Fixed question."),
      mcq("pre02-e7", "0 is…", ["one", "ten", "zero", "two"], "zero", "0 = zero.", "0 — zero."),
      gap("pre02-e8", "She ___ fifteen.", "is", "He/she/it + is.", "He/she/it + is."),
      order("pre02-e9", ["many", "How", "books"], "How many books", "How many + noun.", "How many + ot."),
      tr("pre02-e10", "Men o‘n yoshdaman.", "I am ten", "I am + number."),
    ],
    test: [
      mcq("pre02-t1", "Choose the correct age sentence.", ["I have 7 years.", "I am 7.", "I do 7.", "I years 7."], "I am 7.", "Be + number.", "Be + son."),
      gap("pre02-t2", "20 is ___.", "twenty", "20 = twenty.", "20 — twenty."),
      errx("pre02-t3", "How many old are you?", "How old are you", "How old, not How many old.", "How old."),
      tr("pre02-t4", "U yigirma yoshda.", "She is twenty", "Or He is twenty — both accepted if listed.", { answer: ["She is twenty", "He is twenty", "He is 20", "She is 20"] }),
      mcq("pre02-t5", "12 is…", ["twenty", "two", "twelve", "ten"], "twelve", "12 = twelve.", "12 — twelve."),
      order("pre02-t6", ["old", "you", "are", "How"], "How old are you", "Question word order.", "So‘z tartibi."),
    ],
  },
  {
    id: "pre-a1-03",
    day: 3,
    level: L,
    topic: "Greetings",
    topicUz: "Salomlashuv",
    cefrCanDo: "I can greet people, say goodbye and use please and thank you.",
    cefrCanDoUz: "Salomlashaman, xayrlashaman, please va thank you deyman.",
    grammar: {
      title: "Hello and goodbye",
      titleUz: "Salom va xayr",
      meaning: "Greetings start and end a conversation. Time of day changes the greeting.",
      meaningUz: "Salomlashuv suhbatni boshlaydi va tugatadi.",
      form: "Hello / Hi. Good morning / afternoon / evening. Goodbye / Bye. Please. Thank you. Sorry.",
      formUz: "Hello, Hi, Good morning, Goodbye, Please, Thank you, Sorry.",
      why: "Polite words make English sound friendly and correct in class and shops.",
      whyUz: "Iltifotli so‘zlar tilni do‘stona qiladi.",
      examples: [
        { en: "Good morning, teacher.", uz: "Xayrli tong, o‘qituvchi." },
        { en: "Thank you.", uz: "Rahmat." },
        { en: "See you tomorrow.", uz: "Ertaga ko‘rishamiz." },
      ],
      negative: {
        form: "We do not say Good night to greet someone in the evening — that is for going to bed.",
        examples: [{ en: "Good evening (hello at night). Good night (going to sleep).", uz: "Good evening — salom. Good night — tunu xayr." }],
      },
      question: {
        form: "How are you?",
        examples: [{ en: "Hi! How are you? I'm fine, thanks.", uz: "Salom! Qalaysiz? Yaxshi, rahmat." }],
      },
      mistakes: [
        { wrong: "Good night, teacher. (at 6pm in class)", right: "Good evening, teacher.", why: "Good night is for bedtime.", whyUz: "Good night — uxlash oldidan." },
        { wrong: "Thanks you", right: "Thank you", why: "Thank you is two words, or just Thanks.", whyUz: "Thank you yoki Thanks." },
      ],
    },
    vocabulary: [
      w("w-hello", "hello", "salom", "interjection", "/həˈləʊ/", "a greeting", "Hello, Ana.", "Salom, Ana.", "greetings", "Hand", { synonyms: ["hi"] }),
      w("w-hi", "hi", "salom (oddiy)", "interjection", "/haɪ/", "informal hello", "Hi, Omar.", "Salom, Omar.", "greetings", "Hand"),
      w("w-goodbye", "goodbye", "xayr", "interjection", "/ˌɡʊdˈbaɪ/", "said when you leave", "Goodbye, class.", "Xayr, sinf.", "greetings", "DoorOpen", { synonyms: ["bye"] }),
      w("w-please", "please", "iltimos", "adverb", "/pliːz/", "a polite word with a request", "Sit down, please.", "O‘tiring, iltimos.", "greetings", "Heart"),
      w("w-thank-you", "thank you", "rahmat", "phrase", "/θæŋk juː/", "said when someone helps you", "Thank you, teacher.", "Rahmat, o‘qituvchi.", "greetings", "HeartHandshake", { synonyms: ["thanks"] }),
      w("w-sorry", "sorry", "kechirasiz", "adjective", "/ˈsɒri/", "said after a small mistake", "Sorry I am late.", "Kechirasiz, kechikdim.", "greetings", "MessageCircleWarning"),
      w("w-morning", "morning", "ertalab", "noun", "/ˈmɔːnɪŋ/", "the first part of the day", "Good morning.", "Xayrli tong.", "time", "Sunrise"),
      w("w-fine", "fine", "yaxshi", "adjective", "/faɪn/", "well; OK", "I'm fine, thanks.", "Yaxshiman, rahmat.", "greetings", "Smile", { synonyms: ["OK", "well"] }),
    ],
    phrases: [
      { id: "p-how-are", phrase: "How are you?", uz: "Qalaysiz?", ipa: "/haʊ ɑː juː/", example: "How are you? I'm fine.", exampleUz: "Qalaysiz? Yaxshi.", speakingTask: "Greet a classmate and ask how they are.", dialogue: [["A", "Hi! How are you?"], ["B", "I'm fine, thank you. And you?"]] },
      { id: "p-good-morning", phrase: "Good morning.", uz: "Xayrli tong.", ipa: "/ɡʊd ˈmɔːnɪŋ/", example: "Good morning, everyone.", exampleUz: "Xayrli tong, hammaga.", speakingTask: "Say the correct greeting for now." },
      { id: "p-see-you", phrase: "See you tomorrow.", uz: "Ertaga ko‘rishamiz.", ipa: "/siː juː təˈmɒrəʊ/", example: "Bye! See you tomorrow.", exampleUz: "Xayr! Ertaga ko‘rishamiz.", speakingTask: "Say goodbye to the class." },
      { id: "p-nice-meet", phrase: "Nice to meet you.", uz: "Tanishganimdan xursandman.", ipa: "/naɪs tə miːt juː/", example: "Hello, I'm Lola. Nice to meet you.", exampleUz: "Salom, men Lola. Tanishganimdan xursandman.", speakingTask: "Introduce yourself and say Nice to meet you." },
    ],
    listening: listen(
      "In the morning",
      "Ertalab",
      [
        { en: "Good morning, Mr Karimov.", uz: "Xayrli tong, janob Karimov." },
        { en: "Good morning, Sara. How are you?", uz: "Xayrli tong, Sara. Qalaysiz?" },
        { en: "I'm fine, thank you.", uz: "Yaxshiman, rahmat." },
        { en: "Sit down, please.", uz: "O‘tiring, iltimos." },
        { en: "Thank you.", uz: "Rahmat." },
        { en: "See you tomorrow.", uz: "Ertaga ko‘rishamiz." },
      ],
      [
        mcq("pre03-lq1", "What time of day is it?", ["night", "morning", "afternoon", "evening"], "morning", "They say Good morning.", "Good morning deyishadi.", { skill: "listening" }),
        gap("pre03-lq2", "I'm ___, thank you.", "fine", "I'm fine, thank you.", "I'm fine.", { skill: "listening" }),
      ],
    ),
    reading: reading(
      "At the school door",
      "Maktab eshigida",
      "Good morning. My name is Mr Aziz. Hello, students. How are you? Please come in. Sit down, please. Thank you. See you tomorrow. Goodbye.",
      [
        mcq("pre03-rq1", "The teacher says…", ["Good night", "Good morning", "Happy birthday", "Good job only"], "Good morning", "The first line is Good morning.", "Birinchi qator Good morning.", { skill: "reading" }),
        mcq("pre03-rq2", "Sit down, ___ .", ["sorry", "please", "zero", "spell"], "please", "Please makes a request polite.", "Please iltimosni yumshatadi.", { skill: "reading" }),
      ],
      "List three greetings from the text.",
    ),
    speaking: { prompt: "Act a 4-line greeting: hello, how are you, thank you, goodbye.", promptUz: "4 qatorli salomlashuv o‘ynang.", scaffolding: ["Hello!", "How are you?", "I'm fine, thanks.", "Goodbye."] },
    writing: { prompt: "Write a short dialogue of 6 lines with greetings.", promptUz: "6 qatorli salomlashuv dialogini yozing.", minWords: 30, scaffolding: ["A: Hello", "B: Hi, how are you?"] },
    exercises: [
      mcq("pre03-e1", "Choose a morning greeting.", ["Good night", "Good morning", "See you", "Sorry"], "Good morning", "Morning = Good morning.", "Ertalab Good morning."),
      gap("pre03-e2", "How ___ you?", "are", "How are you?", "How are you?"),
      order("pre03-e3", ["meet", "to", "Nice", "you"], "Nice to meet you", "Fixed phrase.", "Tayyor ibora."),
      errx("pre03-e4", "Thanks you, teacher.", "Thank you, teacher", "Thank you or Thanks, not Thanks you.", "Thanks you emas."),
      tr("pre03-e5", "Rahmat.", "Thank you", "Thank you / Thanks.", { answer: ["Thank you", "Thanks"] }),
      mcq("pre03-e6", "You leave. You say…", ["Hello", "Good morning", "Goodbye", "Please"], "Goodbye", "Goodbye when you leave.", "Ketayotganda Goodbye."),
      gap("pre03-e7", "Sit down, ___.", "please", "Please is polite.", "Please — iltimos."),
      tr("pre03-e8", "Qalaysiz?", "How are you", "How are you?"),
      order("pre03-e9", ["you", "See", "tomorrow"], "See you tomorrow", "See you + time.", "See you + vaqt."),
      mcq("pre03-e10", "I'm fine, ___.", ["please", "spell", "thanks", "zero"], "thanks", "I'm fine, thanks.", "I'm fine, thanks."),
    ],
    test: [
      mcq("pre03-t1", "Polite request word:", ["sorry", "please", "hello", "bye"], "please", "Please.", "Please."),
      gap("pre03-t2", "Good ___, teacher. (7am)", "morning", "7am is morning.", "7:00 — morning."),
      errx("pre03-t3", "How you are?", "How are you", "Verb before you in this question.", "How are you."),
      tr("pre03-t4", "Xayr.", "Goodbye", "Goodbye / Bye.", { answer: ["Goodbye", "Bye"] }),
      order("pre03-t5", ["are", "How", "you"], "How are you", "Fixed order.", "Tartib."),
      mcq("pre03-t6", "Nice to ___ you.", ["spell", "meet", "count", "sit"], "meet", "Nice to meet you.", "Nice to meet you."),
    ],
  },
  {
    id: "pre-a1-04",
    day: 4,
    level: L,
    topic: "Pronouns",
    topicUz: "Olmoshlar",
    cefrCanDo: "I can use I, you, he, she, we, they to talk about people.",
    cefrCanDoUz: "Odamlar haqida I, you, he, she, we, they ishlataman.",
    grammar: {
      title: "Subject pronouns",
      titleUz: "Ega olmoshlari",
      meaning: "Pronouns replace names: Ana → she. Ali and I → we.",
      meaningUz: "Olmosh ism o‘rnida: Ana → she.",
      form: "I, you, he, she, it, we, they",
      formUz: "I, you, he, she, it, we, they",
      why: "We do not repeat names every sentence.",
      whyUz: "Har gapda ismni takrorlamaymiz.",
      examples: [
        { en: "I am a student.", uz: "Men o‘quvchiman." },
        { en: "She is a teacher.", uz: "U (ayol) o‘qituvchi." },
        { en: "They are friends.", uz: "Ular do‘stlar." },
      ],
      negative: {
        form: "Pronoun + be + not",
        examples: [{ en: "He is not a teacher.", uz: "U o‘qituvchi emas." }],
      },
      question: {
        form: "Be + pronoun…?",
        examples: [{ en: "Are you a student?", uz: "Siz o‘quvchimisiz?" }],
      },
      mistakes: [
        { wrong: "Me am a student.", right: "I am a student.", why: "Subject form is I, not me.", whyUz: "Ega — I, me emas." },
        { wrong: "She is teacher he.", right: "She is a teacher. He is a student.", why: "One pronoun per subject. Do not mix she/he in one phrase.", whyUz: "Har ega uchun bitta olmosh." },
      ],
      contrast: {
        vs: "he vs she vs they",
        a: "He is Ali. She is Lola.",
        b: "They are Ali and Lola.",
        note: "he = male, she = female, they = two or more people.",
        noteUz: "he — erkak, she — ayol, they — ikki yoki ko‘p.",
      },
    },
    vocabulary: [
      w("w-i", "I", "men", "pronoun", "/aɪ/", "the speaker", "I am here.", "Men shu yerdaman.", "people", "User"),
      w("w-you", "you", "sen / siz", "pronoun", "/juː/", "the listener", "You are a student.", "Siz o‘quvchisiz.", "people", "Users"),
      w("w-he", "he", "u (erkak)", "pronoun", "/hiː/", "a man or boy", "He is Omar.", "U Omar.", "people", "User"),
      w("w-she", "she", "u (ayol)", "pronoun", "/ʃiː/", "a woman or girl", "She is Ana.", "U Ana.", "people", "User"),
      w("w-we", "we", "biz", "pronoun", "/wiː/", "I and another person", "We are friends.", "Biz do‘stmiz.", "people", "Users"),
      w("w-they", "they", "ular", "pronoun", "/ðeɪ/", "two or more people or things", "They are teachers.", "Ular o‘qituvchilar.", "people", "Users"),
      w("w-it", "it", "u (narsa)", "pronoun", "/ɪt/", "a thing or animal", "It is a book.", "Bu kitob.", "things", "Box"),
      w("w-friend", "friend", "do‘st", "noun", "/frend/", "a person you like", "She is my friend.", "U mening do‘stim.", "people", "Heart", { family: [{ form: "friends", pos: "noun" }, { form: "friendly", pos: "adjective" }] }),
    ],
    phrases: [
      { id: "p-i-am", phrase: "I am a student.", uz: "Men o‘quvchiman.", ipa: "/aɪ æm ə ˈstjuːdnt/", example: "I am a student of English.", exampleUz: "Men ingliz tili o‘quvchisiman.", speakingTask: "Say who you are with I am." },
      { id: "p-this-is", phrase: "This is my friend.", uz: "Bu mening do‘stim.", ipa: "/ðɪs ɪz maɪ frend/", example: "This is my friend Ali.", exampleUz: "Bu mening do‘stim Ali.", speakingTask: "Introduce a friend." },
      { id: "p-he-is", phrase: "He is a teacher.", uz: "U o‘qituvchi.", ipa: "/hiː ɪz ə ˈtiːtʃə/", example: "He is my teacher.", exampleUz: "U mening o‘qituvchim.", speakingTask: "Point to a man and say He is…" },
      { id: "p-they-are", phrase: "They are students.", uz: "Ular o‘quvchilar.", ipa: "/ðeɪ ɑː ˈstjuːdnts/", example: "They are in my class.", exampleUz: "Ular mening sinfimda.", speakingTask: "Talk about two classmates." },
    ],
    listening: listen(
      "Who is who?",
      "Kim kim?",
      [
        { en: "This is Ana. She is a student.", uz: "Bu Ana. U o‘quvchi." },
        { en: "This is Omar. He is a student too.", uz: "Bu Omar. U ham o‘quvchi." },
        { en: "I am their teacher.", uz: "Men ularning o‘qituvchisiman." },
        { en: "We are in class now.", uz: "Biz hozir sinfdamiz." },
        { en: "They are good friends.", uz: "Ular yaxshi do‘stlar." },
        { en: "It is an English book.", uz: "Bu inglizcha kitob." },
      ],
      [
        mcq("pre04-lq1", "Ana is a…", ["teacher", "book", "student", "number"], "student", "She is a student.", "U student.", { skill: "listening" }),
        gap("pre04-lq2", "___ are good friends.", "They", "They = Ana and Omar.", "They — Ana va Omar.", { skill: "listening" }),
      ],
    ),
    reading: reading(
      "Our class",
      "Bizning sinf",
      "I am Lola. I am a student. This is Ali. He is a student. This is Miss Noila. She is a teacher. We are in Room 2. They are my friends. It is a small class.",
      [
        mcq("pre04-rq1", "Miss Noila is…", ["he", "a student", "a teacher", "a book"], "a teacher", "She is a teacher.", "U teacher.", { skill: "reading" }),
        mcq("pre04-rq2", "I am Lola. Lola =", ["he", "she", "they", "it"], "she", "Lola is female → she.", "Lola — she.", { skill: "reading" }),
      ],
      "Replace the names with pronouns.",
    ),
    speaking: { prompt: "Introduce three people using I, he/she, they.", promptUz: "I, he/she, they bilan uch kishini tanishtiring.", scaffolding: ["I am…", "He is…", "She is…", "They are…"] },
    writing: { prompt: "Write 6 sentences with six different pronouns.", promptUz: "Olti xil olmosh bilan 6 gap yozing.", minWords: 30, scaffolding: ["I am…", "You are…", "It is…"] },
    exercises: [
      mcq("pre04-e1", "Ana is a girl. ___ is a student.", ["He", "She", "They", "I"], "She", "Female → she.", "Ayol — she."),
      gap("pre04-e2", "Ali is a boy. ___ is ten.", "He", "Male → he.", "Erkak — he."),
      order("pre04-e3", ["am", "I", "a", "student"], "I am a student", "I + am + a + noun.", "I am a + ot."),
      errx("pre04-e4", "Me is a teacher.", "I am a teacher", "Subject I + am.", "I am."),
      tr("pre04-e5", "Ular do‘stlar.", "They are friends", "They are + noun."),
      mcq("pre04-e6", "A book: ___ is a book.", ["he", "she", "it", "they"], "it", "Things take it.", "Narsa — it."),
      gap("pre04-e7", "You and I = ___.", "we", "I + another person = we.", "Men + boshqa = we."),
      order("pre04-e8", ["are", "They", "teachers"], "They are teachers", "They + are.", "They are."),
      tr("pre04-e9", "Men o‘quvchiman.", "I am a student", "I am a student."),
      mcq("pre04-e10", "Choose the pronoun for two people.", ["he", "she", "it", "they"], "they", "Two or more → they.", "Ikki kishi — they."),
    ],
    test: [
      mcq("pre04-t1", "Omar = ___", ["she", "he", "it", "I"], "he", "Omar is male.", "Omar — he."),
      gap("pre04-t2", "___ are students. (Ali and I)", "We", "Ali and I = we.", "Ali va men = we."),
      errx("pre04-t3", "She am a teacher.", "She is a teacher", "She + is.", "She is."),
      tr("pre04-t4", "Bu kitob.", "It is a book", "It is a book."),
      order("pre04-t5", ["is", "She", "my", "friend"], "She is my friend", "She is my friend."),
      mcq("pre04-t6", "You ___ a student.", ["am", "is", "are", "be"], "are", "You + are.", "You are."),
    ],
  },
  {
    id: "pre-a1-05",
    day: 5,
    level: L,
    topic: "The verb to be",
    topicUz: "To be fe’li",
    cefrCanDo: "I can make simple sentences with am, is and are.",
    cefrCanDoUz: "Am, is, are bilan oddiy gap tuzaman.",
    grammar: {
      title: "Verb to be (affirmative)",
      titleUz: "To be (tasdiq)",
      meaning: "Be links a person or thing to a name, job, feeling or place.",
      meaningUz: "Be odam yoki narsani ism, kasb, holat yoki joyga bog‘laydi.",
      form: "I am. You/we/they are. He/she/it is.",
      formUz: "I am. You/we/they are. He/she/it is.",
      why: "English needs a verb even when Uzbek uses faqatman / o‘qituvchi.",
      whyUz: "Ingliz tilida fe’l shart. O‘zbekchada bo‘lishi shart emas.",
      examples: [
        { en: "I am happy.", uz: "Men xursandman." },
        { en: "She is in Tashkent.", uz: "U Toshkentda." },
        { en: "They are ready.", uz: "Ular tayyor." },
      ],
      negative: {
        form: "I am not. He is not (isn't). They are not (aren't).",
        examples: [{ en: "I am not late.", uz: "Men kechikganim yo‘q." }],
      },
      question: {
        form: "Am I…? Is she…? Are you…?",
        examples: [{ en: "Are you ready?", uz: "Tayyormisiz?" }],
      },
      mistakes: [
        { wrong: "I is a student.", right: "I am a student.", why: "I always takes am.", whyUz: "I bilan doim am." },
        { wrong: "They is here.", right: "They are here.", why: "They takes are.", whyUz: "They bilan are." },
      ],
      contrast: {
        vs: "am / is / are",
        a: "I am / he is",
        b: "you are / they are",
        note: "One form per subject. Never mix.",
        noteUz: "Har ega uchun o‘z shakli.",
      },
    },
    vocabulary: [
      w("w-am", "am", "man / -man", "verb", "/æm/", "form of be with I", "I am ready.", "Men tayyorman.", "grammar", "Check"),
      w("w-is", "is", "-dir (u)", "verb", "/ɪz/", "form of be with he/she/it", "She is here.", "U shu yerda.", "grammar", "Check"),
      w("w-are", "are", "-siz / -lar", "verb", "/ɑː/", "form of be with you/we/they", "You are right.", "Siz to‘g‘risiz.", "grammar", "Check"),
      w("w-student", "student", "o‘quvchi", "noun", "/ˈstjuːdnt/", "a person who studies", "I am a student.", "Men o‘quvchiman.", "school", "GraduationCap"),
      w("w-teacher", "teacher", "o‘qituvchi", "noun", "/ˈtiːtʃə/", "a person who teaches", "She is a teacher.", "U o‘qituvchi.", "school", "School", { family: [{ form: "teach", pos: "verb" }] }),
      w("w-happy", "happy", "xursand", "adjective", "/ˈhæpi/", "feeling good", "I am happy today.", "Bugun xursandman.", "feelings", "Smile", { antonyms: ["sad"] }),
      w("w-here", "here", "shu yerda", "adverb", "/hɪə/", "in this place", "We are here.", "Biz shu yerdamiz.", "place", "MapPin", { antonyms: ["there"] }),
      w("w-ready", "ready", "tayyor", "adjective", "/ˈredi/", "prepared to start", "Are you ready?", "Tayyormisiz?", "feelings", "CircleCheck"),
    ],
    phrases: [
      { id: "p-i-am-ready", phrase: "I am ready.", uz: "Men tayyorman.", ipa: "/aɪ æm ˈredi/", example: "Teacher, I am ready.", exampleUz: "O‘qituvchi, men tayyorman.", speakingTask: "Say when you are ready." },
      { id: "p-she-is-here", phrase: "She is here.", uz: "U shu yerda.", ipa: "/ʃiː ɪz hɪə/", example: "Ana? She is here.", exampleUz: "Ana? U shu yerda.", speakingTask: "Say where a classmate is." },
      { id: "p-we-are", phrase: "We are in class.", uz: "Biz sinfdamiz.", ipa: "/wiː ɑː ɪn klɑːs/", example: "We are in class now.", exampleUz: "Biz hozir sinfdamiz.", speakingTask: "Say where you are." },
      { id: "p-it-is-ok", phrase: "It is OK.", uz: "Hammasi joyida.", ipa: "/ɪt ɪz əʊˈkeɪ/", example: "Don't worry. It is OK.", exampleUz: "Xavotir olma. Hammasi joyida.", speakingTask: "Reassure a friend." },
    ],
    listening: listen(
      "Are you ready?",
      "Tayyormisiz?",
      [
        { en: "Good morning. I am Mr Karim.", uz: "Xayrli tong. Men janob Karim." },
        { en: "You are in English class.", uz: "Siz ingliz tili darsidasiz." },
        { en: "She is your teacher today. I am not.", uz: "Bugun u sizning o‘qituvchingiz. Men emasman." },
        { en: "Are you ready?", uz: "Tayyormisiz?" },
        { en: "Yes, we are ready.", uz: "Ha, biz tayyormiz." },
        { en: "Good. It is time to start.", uz: "Yaxshi. Boshlash vaqti." },
      ],
      [
        mcq("pre05-lq1", "Who is the teacher today?", ["Mr Karim", "She", "They", "I"], "She", "She is your teacher today.", "Bugun she teacher.", { skill: "listening" }),
        gap("pre05-lq2", "Yes, we ___ ready.", "are", "We are ready.", "We are.", { skill: "listening" }),
      ],
    ),
    reading: reading(
      "I am here",
      "Men shu yerdaman",
      "I am Aziz. I am a student. I am here today. My sister is a teacher. She is not here. We are happy. You are in my class. They are at home. It is a good day.",
      [
        mcq("pre05-rq1", "Aziz is a…", ["teacher", "student", "book", "class"], "student", "I am a student.", "I am a student.", { skill: "reading" }),
        mcq("pre05-rq2", "His sister is…", ["here", "not here", "a student", "happy only"], "not here", "She is not here.", "She is not here.", { skill: "reading" }),
      ],
      "Copy all be-forms from the text.",
    ),
    speaking: { prompt: "Make 5 sentences: I am / he is / she is / we are / they are.", promptUz: "5 gap tuzing: am/is/are.", scaffolding: ["I am…", "He is…"] },
    writing: { prompt: "Write 8 short sentences with am, is, are.", promptUz: "Am, is, are bilan 8 qisqa gap.", minWords: 32, scaffolding: ["I am…", "It is…"] },
    exercises: [
      mcq("pre05-e1", "I ___ a student.", ["is", "are", "am", "be"], "am", "I + am.", "I am."),
      mcq("pre05-e2", "She ___ a teacher.", ["am", "is", "are", "be"], "is", "She + is.", "She is."),
      gap("pre05-e3", "They ___ ready.", "are", "They + are.", "They are."),
      order("pre05-e4", ["is", "She", "happy"], "She is happy", "Subject + is + adjective.", "Ega + is + sifat."),
      errx("pre05-e5", "You is here.", "You are here", "You + are.", "You are."),
      tr("pre05-e6", "Men tayyorman.", "I am ready", "I am ready."),
      gap("pre05-e7", "He ___ not a teacher.", "is", "He is not.", "He is not."),
      mcq("pre05-e8", "We ___ in class.", ["am", "is", "are", "be"], "are", "We + are.", "We are."),
      order("pre05-e9", ["you", "Are", "ready"], "Are you ready", "Are + subject + adjective.", "Are you…"),
      tr("pre05-e10", "Ular uyda.", "They are at home", "They are at home."),
    ],
    test: [
      mcq("pre05-t1", "It ___ a book.", ["am", "is", "are", "be"], "is", "It + is.", "It is."),
      gap("pre05-t2", "I ___ not late.", "am", "I am not.", "I am not."),
      errx("pre05-t3", "We is happy.", "We are happy", "We + are.", "We are."),
      tr("pre05-t4", "Siz o‘quvchisiz.", "You are a student", "You are a student."),
      order("pre05-t5", ["am", "I", "here"], "I am here", "I am here."),
      mcq("pre05-t6", "Are they ready? — Yes, they ___.", ["am", "is", "are", "be"], "are", "Short answer uses are.", "Qisqa javob: are."),
    ],
  },
];
