/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhrasesRouteImport } from './routes/phrases'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LearnSkillIdRouteImport } from './routes/learn.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasesRoute = PhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSkillIdRoute = LearnSkillIdRouteImport.update({
  id: '/learn/$skillId',
  path: '/learn/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/phrases': typeof PhrasesRoute
  '/progress': typeof ProgressRoute
  '/learn/$skillId': typeof LearnSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/phrases': typeof PhrasesRoute
  '/progress': typeof ProgressRoute
  '/learn/$skillId': typeof LearnSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/phrases': typeof PhrasesRoute
  '/progress': typeof ProgressRoute
  '/learn/$skillId': typeof LearnSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/phrases' | '/progress' | '/learn/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/phrases' | '/progress' | '/learn/$skillId'
  id: '__root__' | '/' | '/phrases' | '/progress' | '/learn/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhrasesRoute: typeof PhrasesRoute
  ProgressRoute: typeof ProgressRoute
  LearnSkillIdRoute: typeof LearnSkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrases': {
      id: '/phrases'
      path: '/phrases'
      fullPath: '/phrases'
      preLoaderRoute: typeof PhrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$skillId': {
      id: '/learn/$skillId'
      path: '/learn/$skillId'
      fullPath: '/learn/$skillId'
      preLoaderRoute: typeof LearnSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhrasesRoute: PhrasesRoute,
  ProgressRoute: ProgressRoute,
  LearnSkillIdRoute: LearnSkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
