/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpeakRouteImport } from './routes/speak'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as LearnLessonIdRouteImport } from './routes/learn_.$lessonId'
import { Route as PracticeSkillRouteImport } from './routes/practice_.$skill'
import { Route as VocabWordIdRouteImport } from './routes/vocab.$wordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakRoute = SpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn_/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSkillRoute = PracticeSkillRouteImport.update({
  id: '/practice_/$skill',
  path: '/practice/$skill',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabWordIdRoute = VocabWordIdRouteImport.update({
  id: '/vocab/$wordId',
  path: '/vocab/$wordId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/mistakes': typeof MistakesRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/speak': typeof SpeakRoute
  '/tutor': typeof TutorRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/practice/$skill': typeof PracticeSkillRoute
  '/vocab/$wordId': typeof VocabWordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/mistakes': typeof MistakesRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/speak': typeof SpeakRoute
  '/tutor': typeof TutorRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/practice/$skill': typeof PracticeSkillRoute
  '/vocab/$wordId': typeof VocabWordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/learn': typeof LearnRoute
  '/mistakes': typeof MistakesRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/speak': typeof SpeakRoute
  '/tutor': typeof TutorRoute
  '/learn_/$lessonId': typeof LearnLessonIdRoute
  '/practice_/$skill': typeof PracticeSkillRoute
  '/vocab/$wordId': typeof VocabWordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/learn'
    | '/mistakes'
    | '/onboarding'
    | '/placement'
    | '/practice'
    | '/progress'
    | '/review'
    | '/settings'
    | '/speak'
    | '/learn/$lessonId'
    | '/practice/$skill'
    | '/vocab/$wordId'
    | '/tutor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/learn'
    | '/mistakes'
    | '/onboarding'
    | '/placement'
    | '/practice'
    | '/progress'
    | '/review'
    | '/settings'
    | '/speak'
    | '/learn/$lessonId'
    | '/practice/$skill'
    | '/vocab/$wordId'
    | '/tutor'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/learn'
    | '/mistakes'
    | '/onboarding'
    | '/placement'
    | '/practice'
    | '/progress'
    | '/review'
    | '/settings'
    | '/speak'
    | '/learn_/$lessonId'
    | '/practice_/$skill'
    | '/vocab/$wordId'
    | '/tutor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRoute
  LearnRoute: typeof LearnRoute
  MistakesRoute: typeof MistakesRoute
  OnboardingRoute: typeof OnboardingRoute
  PlacementRoute: typeof PlacementRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SpeakRoute: typeof SpeakRoute
  TutorRoute: typeof TutorRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  PracticeSkillRoute: typeof PracticeSkillRoute
  VocabWordIdRoute: typeof VocabWordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speak': {
      id: '/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof SpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn_/$lessonId': {
      id: '/learn_/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice_/$skill': {
      id: '/practice_/$skill'
      path: '/practice/$skill'
      fullPath: '/practice/$skill'
      preLoaderRoute: typeof PracticeSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab/$wordId': {
      id: '/vocab/$wordId'
      path: '/vocab/$wordId'
      fullPath: '/vocab/$wordId'
      preLoaderRoute: typeof VocabWordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRoute,
  LearnRoute: LearnRoute,
  MistakesRoute: MistakesRoute,
  OnboardingRoute: OnboardingRoute,
  PlacementRoute: PlacementRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SpeakRoute: SpeakRoute,
  TutorRoute: TutorRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  PracticeSkillRoute: PracticeSkillRoute,
  VocabWordIdRoute: VocabWordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
